.\" This man page was written by Markus Koschany in February 2015. It is provided
.\" under the GNU General Public License 3 or (at your option) any later version.
.TH cavepacker 6 "February 2015" "cavepacker" "games"
.SH NAME
cavepacker \- Sokoban game
 
.SH SYNOPSIS
.PP
\fBcavepacker\fR [\fIoption\fR]
.SH DESCRIPTION
\fBcavepacker\fP CavePacker is a sokoban game.
Keep your cave tidy. To do this, make sure that all the spreaded packages are
put onto their targets. You can only push, pulling is not allowed.

You get higher ratings for lesser moves you need. The first few maps might be
easy to solve - but the more you progress in the game, the harder the maps
will be. 

There is also a multiplayer mode available.
.SH OPTIONS
.TP
\fB\-server\fR
Start the server for the game (headless mode).

