.\" This man page was written by Markus Koschany in February 2015. It is provided
.\" under the GNU General Public License 3 or (at your option) any later version.
.TH cavepacker 6 "February 2015" "cavepacker" "games"
.SH NAME
cavepacker \- Sokoban game

.SH SYNOPSIS
.PP
\fBcavepacker\fR [\fIoption\fR]
.SH DESCRIPTION
\fBcavepacker\fP CavePacker is a sokoban game.
Keep your cave tidy. To do this, make sure that all the spread packages are
put onto their targets. You can only push, pulling is not allowed.

You get higher ratings for lesser moves you need. The first few maps might be
easy to solve - but the more you progress in the game, the harder the maps
will be.

There is also a multiplayer mode available.
.SH OPTIONS
.TP
\fB\-server\fR
Start the server for the game (headless mode).
.TP
\fB\-set <varname> <value>\fR
Change the value of a config variable.

.SH CONSOLE COMMANDS
Open the in-game console with SHIFT+ESC. Just type a config variable name there
to get the current value. The console commands can also be triggered from the
commandline by just putting a \fB\-\fR in front of it.
.TP
\fB\-loglevel <LEVEL>\fR
Possible level values are: TRACE, DEBUG, INFO, WARN, ERROR

.SH CONFIG VARIABLES
These variables can be modified by using the \fB\-set\fR command - or by
providing default values for some of them in the config.lua file in the asset
directory. You can override any file by putting it into the same subdir as in
your installation folder into ~/.local/share/cavepacker
.TP
\fBalreadyrated\fR

.TP
\fBblue\fR

.TP
\fBdebug\fR

.TP
\fBdebugSleep\fR

.TP
\fBdebugentity\fR

.TP
\fBdebugui\fR

.TP
\fBeditor-lastmap\fR

.TP
\fBforcefingercontrol\fR

.TP
\fBfpslimit\fR

.TP
\fBfrontend\fR
Change the rendering frontend that is used by the game. Possible values are:
sdl, opengl and opengles2

.TP
\fBfullscreen\fR
Set to false to start in windowed mode - also see \fBwidth\fR and \fBheight\fR
vars.
.TP
\fBgamecontroller\fR

.TP
\fBgamecontrollertriggeraxis\fR

.TP
\fBgoogleplaystate\fR

.TP
\fBgrabmouse\fR

.TP
\fBgreen\fR

.TP
\fBheight\fR
-1 will pick the desktop height
.TP
\fBlanguage\fR

.TP
\fBlaunchcount\fR

.TP
\fBmaxzoom\fR

.TP
\fBminzoom\fR

.TP
\fBmode\fR

.TP
\fBmousespeed\fR

.TP
\fBmusicvolume\fR

.TP
\fBname\fR
The user name that is used in multiplayer games
.TP
\fBncurses\fR
If you start in headless mode via \fB\-server\fR you can disable the ncurses
interface by setting this to false
.TP
\fBnetwork\fR

.TP
\fBparticles\fR

.TP
\fBpersister\fR

.TP
\fBport\fR

.TP
\fBred\fR

.TP
\fBrenderer\fR
If you have \fBfrontend\fR set to sdl, you can change the renderer that sdl is
using. Refer to the SDL documentation for a list of valid options here.
.TP
\fBrendertotexture\fR

.TP
\fBservername\fR

.TP
\fBshowcursor\fR

.TP
\fBshowfps\fR

.TP
\fBsolvestepmillis\fR

.TP
\fBsound\fR

.TP
\fBsoundengine\fR

.TP
\fBtestscreenpadding\fR

.TP
\fBtexturesize\fR

.TP
\fBvolume\fR

.TP
\fBvsync\fR

.TP
\fBwidth\fR
-1 will pick the desktop width

.SH HOMEPAGE
http://www.caveproductions.org

.SH COPYRIGHT
Copyright \[co] 2014\-2016 by Martin Gerhardy.
Source code licensed under GPL3 - assets under CC-BY-SA 3.0.
