.\" This man page was written by Markus Koschany in February 2015. It is provided
.\" under the GNU General Public License 3 or (at your option) any later version.
.TH caveexpress 6 "February 2015" "caveexpress" "games"
.SH NAME
caveexpress \- 2D platformer with physics-based gameplay
 
.SH SYNOPSIS
.PP
\fBcaveexpress\fR [\fIoption\fR]
.SH DESCRIPTION
\fBCaveexpress\fP is a classic 2D platformer with physics-based gameplay and dozens of levels.
Master your pedal-powered flying machine to pick up packages from your cave-dwelling clients
and drop them off at the collection point.
 
But beware! Mighty mastodons, terrifying pterodactyls and others would
rather see you extinct.
.SH OPTIONS
.TP
\fB\-server\fR
Start the server for the game (headless mode).

