-- create a new campaign
local c = Campaign.new("letters")
-- set an ingame icon for this campaign
c:setSetting("icon", "icon-campaign-rock")
-- set the on screen message when this campaign is activated
c:setSetting("text", "Letters")
-- now add all maps
c:addMaps("letter-01")
c:addMaps("letter-02")
c:addMaps("letter-03")
c:addMaps("letter-04")
c:addMaps("letter-05")
c:addMaps("letter-06")
c:addMaps("letter-07")
c:addMaps("letter-08")
c:addMaps("letter-09")
c:addMaps("letter-10")
c:addMaps("letter-11")
c:addMaps("letter-12")
c:addMaps("letter-13")
c:addMaps("letter-14")
c:addMaps("letter-15")
c:addMaps("letter-16")
c:addMaps("letter-17")
c:addMaps("letter-18")
c:addMaps("letter-19")
c:addMaps("letter-20")
c:addMaps("letter-21")
c:addMaps("letter-22")
c:addMaps("letter-23")
c:addMaps("letter-24")
c:unlock()
