sprites = {
	["arrow-white"] = { type = "decal", width = 1.29, height = 0.77, rotateable = 90, },
	["arrow-yellow"] = { type = "decal", width = 1.29, height = 0.77, rotateable = 90, },
	["barrel-blue-down"] = { type = "moveable", width = 0.54, height = 0.375, rotateable = 90, },
	["barrel-blue"] = { type = "moveable", width = 0.43, height = 0.43, rotateable = 90, },
	["barrel-red-down"] = { type = "moveable", width = 0.54, height = 0.375, rotateable = 90, },
	["barrel-red"] = { type = "moveable", width = 0.43, height = 0.43, rotateable = 90, },
	["barrier-red"] = { type = "road", width = 1.5, height = 0.5, rotateable = 45, },
	["barrier-red-race"] = { type = "road", width = 1.5, height = 0.5, rotateable = 45, },
	["barrier-white"] = { type = "road", width = 1.5, height = 0.5, rotateable = 45, },
	["barrier-white-race"] = { type = "road", width = 1.5, height = 0.5, rotateable = 45, },
	["car-black-1"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-black-2"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-black-3"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-black-4"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-black-5"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-blue-1"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-blue-2"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-blue-3"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-blue-4"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-blue-5"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-green-1"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-green-2"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-green-3"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-green-4"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-green-5"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-red-1"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-red-2"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-red-3"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-red-4"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-red-5"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-yellow-1"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-yellow-2"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-yellow-3"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-yellow-4"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["car-yellow-5"] = { type = "vehicle", width = 0.54, height = 0.94, },
	["character-black-blue"] = { type = "moveable", },
	["character-black-green"] = { type = "moveable", },
	["character-black-red"] = { type = "moveable", },
	["character-black-white"] = { type = "moveable", },
	["character-blonde-blue"] = { type = "moveable", },
	["character-blonde-green"] = { type = "moveable", },
	["character-blonde-red"] = { type = "moveable", },
	["character-blonde-white"] = { type = "moveable", },
	["character-brown-blue"] = { type = "moveable", },
	["character-brown-green"] = { type = "moveable", },
	["character-brown-red"] = { type = "moveable", },
	["character-brown-white"] = { type = "moveable", },
	["cone-down"] = { type = "moveable", width = 0.33, height = 0.33, },
	["cone-straight"] = { type = "moveable", width = 0.33, height = 0.33, },
	["land-dirt01"] = { type = "land", },
	["land-dirt02"] = { type = "land", },
	["land-dirt03"] = { type = "land", },
	["land-dirt04"] = { type = "land", },
	["land-dirt05"] = { type = "land", },
	["land-dirt06"] = { type = "land", },
	["land-dirt07"] = { type = "land", },
	["land-dirt08"] = { type = "land", },
	["land-dirt09"] = { type = "land", },
	["land-dirt10"] = { type = "land", },
	["land-dirt11"] = { type = "land", },
	["land-dirt12"] = { type = "land", },
	["land-dirt13"] = { type = "land", },
	["land-dirt14"] = { type = "land", },
	["land-grass01"] = { type = "land", },
	["land-grass02"] = { type = "land", },
	["land-grass03"] = { type = "land", },
	["land-grass04"] = { type = "land", },
	["land-grass05"] = { type = "land", },
	["land-grass06"] = { type = "land", },
	["land-grass07"] = { type = "land", },
	["land-grass08"] = { type = "land", },
	["land-grass09"] = { type = "land", },
	["land-grass10"] = { type = "land", },
	["land-grass11"] = { type = "land", },
	["land-grass12"] = { type = "land", },
	["land-grass13"] = { type = "land", },
	["land-grass14"] = { type = "land", },
	["land-sand01"] = { type = "land", },
	["land-sand02"] = { type = "land", },
	["land-sand03"] = { type = "land", },
	["land-sand04"] = { type = "land", },
	["land-sand05"] = { type = "land", },
	["land-sand06"] = { type = "land", },
	["land-sand07"] = { type = "land", },
	["land-sand08"] = { type = "land", },
	["land-sand09"] = { type = "land", },
	["land-sand10"] = { type = "land", },
	["land-sand11"] = { type = "land", },
	["land-sand12"] = { type = "land", },
	["land-sand13"] = { type = "land", },
	["land-sand14"] = { type = "land", },
	["lights"] = { type = "solid", },
	["light-white"] = { type = "lights", },
	["light-yellow"] = { type = "lights", },
	["motorcycle-black"] = { type = "vehicle", },
	["motorcycle-blue"] = { type = "vehicle", },
	["motorcycle-green"] = { type = "vehicle", },
	["motorcycle-red"] = { type = "vehicle", },
	["motorcycle-yellow"] = { type = "vehicle", },
	["oil"] = { type = "oil", },
	["racer-black"] = { type = "racer", },
	["racer-blue"] = { type = "racer", },
	["racer-green"] = { type = "racer", },
	["racer-red"] = { type = "racer", },
	["racer-yellow"] = { type = "racer", },
	["road-asphalt01"] = { type = "road", },
	["road-asphalt02"] = { type = "road", },
	["road-asphalt03"] = { type = "road", },
	["road-asphalt04"] = { type = "road", },
	["road-asphalt05"] = { type = "road", },
	["road-asphalt06"] = { type = "road", },
	["road-asphalt07"] = { type = "road", },
	["road-asphalt08"] = { type = "road", },
	["road-asphalt09"] = { type = "road", },
	["road-asphalt10"] = { type = "road", },
	["road-asphalt11"] = { type = "road", },
	["road-asphalt12"] = { type = "road", },
	["road-asphalt13"] = { type = "road", },
	["road-asphalt14"] = { type = "road", },
	["road-asphalt15"] = { type = "road", },
	["road-asphalt16"] = { type = "road", },
	["road-asphalt17"] = { type = "road", },
	["road-asphalt18"] = { type = "road", },
	["road-asphalt19"] = { type = "road", },
	["road-asphalt20"] = { type = "road", },
	["road-asphalt21"] = { type = "road", },
	["road-asphalt22"] = { type = "road", },
	["road-asphalt23"] = { type = "road", },
	["road-asphalt24"] = { type = "road", },
	["road-asphalt25"] = { type = "road", },
	["road-asphalt26"] = { type = "road", },
	["road-asphalt27"] = { type = "road", },
	["road-asphalt28"] = { type = "road", },
	["road-asphalt29"] = { type = "road", },
	["road-asphalt30"] = { type = "road", },
	["road-asphalt31"] = { type = "road", },
	["road-asphalt32"] = { type = "road", },
	["road-asphalt33"] = { type = "road", },
	["road-asphalt34"] = { type = "road", },
	["road-asphalt35"] = { type = "road", },
	["road-asphalt36"] = { type = "road", },
	["road-asphalt37"] = { type = "road", },
	["road-asphalt38"] = { type = "road", },
	["road-asphalt39"] = { type = "road", },
	["road-asphalt40"] = { type = "road", },
	["road-asphalt41"] = { type = "road", },
	["road-asphalt42"] = { type = "road", },
	["road-asphalt43"] = { type = "road", },
	["road-asphalt44"] = { type = "road", },
	["road-asphalt45"] = { type = "road", },
	["road-asphalt46"] = { type = "road", },
	["road-asphalt47"] = { type = "road", },
	["road-asphalt48"] = { type = "road", },
	["road-asphalt49"] = { type = "road", },
	["road-asphalt50"] = { type = "road", },
	["road-asphalt51"] = { type = "road", },
	["road-asphalt52"] = { type = "road", },
	["road-asphalt53"] = { type = "road", },
	["road-asphalt54"] = { type = "road", },
	["road-asphalt55"] = { type = "road", },
	["road-asphalt56"] = { type = "road", },
	["road-asphalt57"] = { type = "road", },
	["road-asphalt58"] = { type = "road", },
	["road-asphalt59"] = { type = "road", },
	["road-asphalt60"] = { type = "road", },
	["road-asphalt61"] = { type = "road", },
	["road-asphalt62"] = { type = "road", },
	["road-asphalt63"] = { type = "road", },
	["road-asphalt64"] = { type = "road", },
	["road-asphalt65"] = { type = "road", },
	["road-asphalt66"] = { type = "road", },
	["road-asphalt67"] = { type = "road", },
	["road-asphalt68"] = { type = "road", },
	["road-asphalt69"] = { type = "road", },
	["road-asphalt70"] = { type = "road", },
	["road-asphalt71"] = { type = "road", },
	["road-asphalt72"] = { type = "road", },
	["road-asphalt73"] = { type = "road", },
	["road-asphalt74"] = { type = "road", },
	["road-asphalt75"] = { type = "road", },
	["road-asphalt76"] = { type = "road", },
	["road-asphalt77"] = { type = "road", },
	["road-asphalt78"] = { type = "road", },
	["road-asphalt79"] = { type = "road", },
	["road-asphalt80"] = { type = "road", },
	["road-asphalt81"] = { type = "road", },
	["road-asphalt82"] = { type = "road", },
	["road-asphalt83"] = { type = "road", },
	["road-asphalt84"] = { type = "road", },
	["road-asphalt85"] = { type = "road", },
	["road-asphalt86"] = { type = "road", },
	["road-asphalt87"] = { type = "road", },
	["road-asphalt88"] = { type = "road", },
	["road-asphalt89"] = { type = "road", },
	["road-asphalt90"] = { type = "road", },
	["road-dirt01"] = { type = "road", },
	["road-dirt02"] = { type = "road", },
	["road-dirt03"] = { type = "road", },
	["road-dirt04"] = { type = "road", },
	["road-dirt05"] = { type = "road", },
	["road-dirt06"] = { type = "road", },
	["road-dirt07"] = { type = "road", },
	["road-dirt08"] = { type = "road", },
	["road-dirt09"] = { type = "road", },
	["road-dirt10"] = { type = "road", },
	["road-dirt11"] = { type = "road", },
	["road-dirt12"] = { type = "road", },
	["road-dirt13"] = { type = "road", },
	["road-dirt14"] = { type = "road", },
	["road-dirt15"] = { type = "road", },
	["road-dirt16"] = { type = "road", },
	["road-dirt17"] = { type = "road", },
	["road-dirt18"] = { type = "road", },
	["road-dirt19"] = { type = "road", },
	["road-dirt20"] = { type = "road", },
	["road-dirt21"] = { type = "land", },
	["road-dirt22"] = { type = "road", },
	["road-dirt23"] = { type = "road", },
	["road-dirt24"] = { type = "road", },
	["road-dirt25"] = { type = "road", },
	["road-dirt26"] = { type = "road", },
	["road-dirt27"] = { type = "road", },
	["road-dirt28"] = { type = "road", },
	["road-dirt29"] = { type = "road", },
	["road-dirt30"] = { type = "road", },
	["road-dirt31"] = { type = "road", },
	["road-dirt32"] = { type = "road", },
	["road-dirt33"] = { type = "road", },
	["road-dirt34"] = { type = "road", },
	["road-dirt35"] = { type = "road", },
	["road-dirt36"] = { type = "road", },
	["road-dirt37"] = { type = "road", },
	["road-dirt38"] = { type = "road", },
	["road-dirt39"] = { type = "road", },
	["road-dirt40"] = { type = "road", },
	["road-dirt41"] = { type = "road", },
	["road-dirt42"] = { type = "road", },
	["road-dirt43"] = { type = "road", },
	["road-dirt44"] = { type = "road", },
	["road-dirt45"] = { type = "road", },
	["road-dirt46"] = { type = "road", },
	["road-dirt47"] = { type = "road", },
	["road-dirt48"] = { type = "road", },
	["road-dirt49"] = { type = "road", },
	["road-dirt50"] = { type = "road", },
	["road-dirt51"] = { type = "road", },
	["road-dirt52"] = { type = "road", },
	["road-dirt53"] = { type = "road", },
	["road-dirt54"] = { type = "road", },
	["road-dirt55"] = { type = "road", },
	["road-dirt56"] = { type = "road", },
	["road-dirt57"] = { type = "road", },
	["road-dirt58"] = { type = "road", },
	["road-dirt59"] = { type = "road", },
	["road-dirt60"] = { type = "road", },
	["road-dirt61"] = { type = "road", },
	["road-dirt62"] = { type = "road", },
	["road-dirt63"] = { type = "road", },
	["road-dirt64"] = { type = "road", },
	["road-dirt65"] = { type = "road", },
	["road-dirt66"] = { type = "road", },
	["road-dirt67"] = { type = "road", },
	["road-dirt68"] = { type = "road", },
	["road-dirt69"] = { type = "road", },
	["road-dirt70"] = { type = "road", },
	["road-dirt71"] = { type = "road", },
	["road-dirt72"] = { type = "road", },
	["road-dirt73"] = { type = "road", },
	["road-dirt74"] = { type = "road", },
	["road-dirt75"] = { type = "road", },
	["road-dirt76"] = { type = "road", },
	["road-dirt77"] = { type = "road", },
	["road-dirt78"] = { type = "road", },
	["road-dirt79"] = { type = "road", },
	["road-dirt80"] = { type = "road", },
	["road-dirt81"] = { type = "road", },
	["road-dirt82"] = { type = "road", },
	["road-dirt83"] = { type = "road", },
	["road-dirt84"] = { type = "road", },
	["road-dirt85"] = { type = "road", },
	["road-dirt86"] = { type = "road", },
	["road-dirt87"] = { type = "road", },
	["road-dirt88"] = { type = "road", },
	["road-dirt89"] = { type = "road", },
	["road-dirt90"] = { type = "road", },
	["road-sand01"] = { type = "road", },
	["road-sand02"] = { type = "road", },
	["road-sand03"] = { type = "road", },
	["road-sand04"] = { type = "road", },
	["road-sand05"] = { type = "road", },
	["road-sand06"] = { type = "road", },
	["road-sand07"] = { type = "road", },
	["road-sand08"] = { type = "road", },
	["road-sand09"] = { type = "road", },
	["road-sand10"] = { type = "road", },
	["road-sand11"] = { type = "road", },
	["road-sand12"] = { type = "road", },
	["road-sand13"] = { type = "road", },
	["road-sand14"] = { type = "road", },
	["road-sand15"] = { type = "road", },
	["road-sand16"] = { type = "road", },
	["road-sand17"] = { type = "road", },
	["road-sand18"] = { type = "road", },
	["road-sand19"] = { type = "road", },
	["road-sand20"] = { type = "road", },
	["road-sand21"] = { type = "road", },
	["road-sand22"] = { type = "road", },
	["road-sand23"] = { type = "road", },
	["road-sand24"] = { type = "road", },
	["road-sand25"] = { type = "road", },
	["road-sand26"] = { type = "road", },
	["road-sand27"] = { type = "road", },
	["road-sand28"] = { type = "road", },
	["road-sand29"] = { type = "road", },
	["road-sand30"] = { type = "road", },
	["road-sand31"] = { type = "road", },
	["road-sand32"] = { type = "road", },
	["road-sand33"] = { type = "road", },
	["road-sand34"] = { type = "road", },
	["road-sand35"] = { type = "road", },
	["road-sand36"] = { type = "road", },
	["road-sand37"] = { type = "road", },
	["road-sand38"] = { type = "road", },
	["road-sand39"] = { type = "road", },
	["road-sand40"] = { type = "road", },
	["road-sand41"] = { type = "road", },
	["road-sand42"] = { type = "road", },
	["road-sand43"] = { type = "road", },
	["road-sand44"] = { type = "road", },
	["road-sand45"] = { type = "road", },
	["road-sand46"] = { type = "road", },
	["road-sand47"] = { type = "road", },
	["road-sand48"] = { type = "road", },
	["road-sand49"] = { type = "road", },
	["road-sand50"] = { type = "road", },
	["road-sand51"] = { type = "road", },
	["road-sand52"] = { type = "road", },
	["road-sand53"] = { type = "road", },
	["road-sand54"] = { type = "road", },
	["road-sand55"] = { type = "road", },
	["road-sand56"] = { type = "road", },
	["road-sand57"] = { type = "road", },
	["road-sand58"] = { type = "road", },
	["road-sand59"] = { type = "road", },
	["road-sand60"] = { type = "road", },
	["road-sand61"] = { type = "road", },
	["road-sand62"] = { type = "road", },
	["road-sand63"] = { type = "road", },
	["road-sand64"] = { type = "road", },
	["road-sand65"] = { type = "road", },
	["road-sand66"] = { type = "road", },
	["road-sand67"] = { type = "road", },
	["road-sand68"] = { type = "road", },
	["road-sand69"] = { type = "road", },
	["road-sand70"] = { type = "road", },
	["road-sand71"] = { type = "road", },
	["road-sand72"] = { type = "road", },
	["road-sand73"] = { type = "road", },
	["road-sand74"] = { type = "road", },
	["road-sand75"] = { type = "road", },
	["road-sand76"] = { type = "road", },
	["road-sand77"] = { type = "road", },
	["road-sand78"] = { type = "road", },
	["road-sand79"] = { type = "road", },
	["road-sand80"] = { type = "road", },
	["road-sand81"] = { type = "road", },
	["road-sand82"] = { type = "road", },
	["road-sand83"] = { type = "road", },
	["road-sand84"] = { type = "road", },
	["road-sand85"] = { type = "road", },
	["road-sand86"] = { type = "road", },
	["road-sand87"] = { type = "road", },
	["road-sand88"] = { type = "road", },
	["road-sand89"] = { type = "road", },
	["road-sand90"] = { type = "road", },
	["rock01"] = { type = "solid", },
	["rock02"] = { type = "solid", },
	["rock03"] = { type = "solid", },
	["rock04"] = { type = "solid", },
	["rock05"] = { type = "solid", },
	["rock06"] = { type = "solid", },
	["rock07"] = { type = "solid", },
	["rock08"] = { type = "solid", },
	["rock09"] = { type = "solid", },
	["rock10"] = { type = "solid", },
	["rock11"] = { type = "solid", },
	["rock12"] = { type = "solid", },
	["rock13"] = { type = "solid", },
	["rock14"] = { type = "solid", },
	["rock15"] = { type = "solid", },
	["rock16"] = { type = "solid", },
	["rock17"] = { type = "solid", },
	["rock18"] = { type = "solid", },
	["rock19"] = { type = "solid", },
	["rock20"] = { type = "solid", },
	["rock21"] = { type = "solid", },
	["rock22"] = { type = "solid", },
	["rock23"] = { type = "solid", },
	["rock24"] = { type = "solid", },
	["skidmark-long-1"] = { type = "decal", },
	["skidmark-long-2"] = { type = "decal", },
	["skidmark-long-3"] = { type = "decal", },
	["skidmark-short-1"] = { type = "decal", },
	["skidmark-short-2"] = { type = "decal", },
	["skidmark-short-3"] = { type = "decal", },
	["tent-blue-large"] = { type = "solid", width = 2, height = 2, rotateable = 90, },
	["tent-blue"] = { type = "solid", },
	["tent-red-large"] = { type = "solid", width = 2, height = 2, rotateable = 90, },
	["tent-red"] = { type = "solid", },
	["tires-red-alt"] = { type = "solid", width = 0.3, height = 0.3, },
	["tires-red"] = { type = "solid", width = 0.3, height = 0.3, },
	["tires-white-alt"] = { type = "solid", width = 0.3, height = 0.3, },
	["tires-white"] = { type = "solid", width = 0.3, height = 0.3, },
	["tree-large"] = { type = "solid", width = 1.5, height = 1.5, rotateable = 10,},
	["tree-small"] = { type = "solid", width = 1, height = 1, rotateable = 10, },
	["tribune-empty"] = { type = "solid", width = 3, height = 1, rotateable = 45, },
	["tribune-full"] = { type = "solid", width = 3, height = 1, rotateable = 45, },
	["tribune-overhang-red"] = { type = "solid", width = 3, height = 0.5, rotateable = 45, },
	["tribune-overhang-striped"] = { type = "solid", width = 3, height = 0.5, rotateable = 45, },
}
