function getName()
	return "Map 16"
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-rock-ice-03", 0, 0)
	map:addTile("tile-rock-ice-03", 0, 1)
	map:addTile("tile-rock-ice-03", 0, 2)
	map:addTile("tile-rock-ice-02", 0, 3)
	map:addTile("tile-rock-ice-03", 0, 4)
	map:addTile("tile-rock-ice-01", 0, 5)
	map:addTile("tile-background-ice-04", 0, 6)
	map:addTile("tile-background-ice-05", 0, 7)
	map:addTile("tile-background-ice-07", 1, 0)
	map:addTile("tile-background-ice-03", 1, 1)
	map:addTile("tile-ground-ice-02", 1, 2)
	map:addTile("tile-rock-ice-02", 1, 3)
	map:addTile("tile-rock-ice-03", 1, 4)
	map:addTile("tile-rock-ice-02", 1, 5)
	map:addTile("tile-background-ice-05", 1, 6)
	map:addTile("tile-background-ice-01", 1, 7)
	map:addTile("tile-background-ice-01", 2, 0)
	map:addTile("tile-background-ice-02", 2, 1)
	map:addTile("tile-ground-ice-04", 2, 2)
	map:addTile("tile-rock-ice-02", 2, 3)
	map:addTile("tile-rock-ice-03", 2, 4)
	map:addTile("tile-rock-ice-01", 2, 5)
	map:addTile("tile-background-ice-02", 2, 6)
	map:addTile("tile-background-ice-06", 2, 7)
	map:addTile("tile-background-ice-06", 3, 0)
	map:addTile("tile-background-ice-07", 3, 1)
	map:addTile("tile-background-ice-03", 3, 2)
	map:addTile("tile-background-ice-01", 3, 3)
	map:addTile("tile-ground-ice-01", 3, 4)
	map:addTile("tile-rock-ice-03", 3, 5)
	map:addTile("tile-ground-ledge-ice-left-02", 3, 6)
	map:addTile("tile-background-ice-05", 3, 7)
	map:addTile("tile-background-ice-06", 4, 0)
	map:addTile("tile-background-ice-06", 4, 1)
	map:addTile("tile-background-ice-04", 4, 2)
	map:addTile("tile-ground-ice-04", 4, 4)
	map:addTile("tile-rock-ice-02", 4, 5)
	map:addTile("tile-ground-ledge-ice-left-01", 4, 6)
	map:addTile("tile-background-ice-03", 4, 7)
	map:addTile("tile-background-ice-04", 5, 0)
	map:addTile("tile-background-ice-07", 5, 1)
	map:addTile("tile-background-ice-03", 5, 2)
	map:addTile("tile-background-ice-03", 5, 3)
	map:addTile("tile-ground-ice-04", 5, 4)
	map:addTile("tile-rock-ice-big-01", 5, 5)
	map:addTile("tile-rock-ice-03", 5, 7)
	map:addTile("tile-background-ice-06", 6, 0)
	map:addTile("tile-background-ice-03", 6, 1)
	map:addTile("tile-background-ice-big-01", 6, 2)
	map:addTile("tile-ground-ice-04", 6, 4)
	map:addTile("tile-rock-ice-01", 6, 7)
	map:addTile("tile-background-ice-06", 7, 0)
	map:addTile("tile-background-ice-01", 7, 1)
	map:addTile("tile-ground-ice-04", 7, 4)
	map:addTile("tile-packagetarget-ice-01-idle", 7, 5, 90)
	map:addTile("tile-rock-ice-01", 7, 6)
	map:addTile("tile-rock-ice-02", 7, 7)
	map:addTile("tile-background-ice-01", 8, 0)
	map:addTile("tile-background-ice-01", 8, 1)
	map:addTile("tile-background-ice-01", 8, 2)
	map:addTile("tile-background-ice-06", 8, 3)
	map:addTile("tile-background-ice-02", 8, 4)
	map:addTile("tile-background-ice-06", 8, 5)
	map:addTile("tile-rock-slope-ice-right-01", 8, 6)
	map:addTile("tile-rock-ice-01", 8, 7)
	map:addTile("tile-background-ice-07", 9, 0)
	map:addTile("tile-background-ice-05", 9, 1)
	map:addTile("tile-background-ice-06", 9, 2)
	map:addTile("tile-background-ice-01", 9, 3)
	map:addTile("tile-background-ice-02", 9, 4)
	map:addTile("tile-background-ice-06", 9, 5)
	map:addTile("tile-background-ice-01", 9, 6)
	map:addTile("tile-rock-slope-ice-right-01", 9, 7)
	map:addTile("tile-background-ice-02", 10, 0)
	map:addTile("tile-background-ice-01", 10, 1)
	map:addTile("tile-background-ice-05", 10, 2)
	map:addTile("tile-background-ice-01", 10, 3)
	map:addTile("tile-background-ice-04", 10, 4)
	map:addTile("tile-background-ice-03", 10, 5)
	map:addTile("tile-background-ice-06", 10, 6)
	map:addTile("tile-background-ice-03", 10, 7)
	map:addTile("tile-background-ice-06", 11, 0)
	map:addTile("tile-background-ice-05", 11, 1)
	map:addTile("tile-background-ice-06", 11, 2)
	map:addTile("tile-ground-ledge-ice-left-02", 11, 3)
	map:addTile("tile-background-ice-01", 11, 4)
	map:addTile("tile-background-ice-06", 11, 5)
	map:addTile("tile-background-ice-01", 11, 6)
	map:addTile("tile-background-ice-05", 11, 7)
	map:addTile("tile-background-ice-07", 12, 0)
	map:addTile("tile-background-ice-04", 12, 1)
	map:addTile("tile-ground-ice-03", 12, 3)
	map:addTile("tile-rock-ice-big-01", 12, 4)
	map:addTile("tile-background-ice-02", 12, 6)
	map:addTile("tile-background-ice-02", 12, 7)
	map:addTile("tile-rock-ice-01", 13, 0)
	map:addTile("tile-rock-ice-02", 13, 1)
	map:addTile("tile-rock-ice-03", 13, 2)
	map:addTile("tile-rock-ice-03", 13, 3)
	map:addTile("tile-rock-ice-big-01", 13, 6)
	map:addTile("tile-rock-ice-02", 14, 0)
	map:addTile("tile-rock-ice-01", 14, 1)
	map:addTile("tile-rock-ice-03", 14, 2)
	map:addTile("tile-rock-ice-03", 14, 3)
	map:addTile("tile-rock-ice-03", 14, 4)
	map:addTile("tile-rock-ice-01", 14, 5)
	map:addTile("tile-rock-ice-03", 15, 0)
	map:addTile("tile-rock-ice-02", 15, 1)
	map:addTile("tile-rock-ice-03", 15, 2)
	map:addTile("tile-rock-ice-01", 15, 3)
	map:addTile("tile-rock-ice-02", 15, 4)
	map:addTile("tile-rock-ice-02", 15, 5)
	map:addTile("tile-rock-ice-03", 15, 6)
	map:addTile("tile-rock-ice-01", 15, 7)

	map:addCave("tile-cave-ice-01", 4, 3, "none", 5000)
	map:addCave("tile-cave-ice-01", 12, 2, "none", 5000)

	map:addEmitter("tree", 1, 0, 1, 0)

	map:setSetting("fishnpc", "true")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "8")
	map:setSetting("packagetransfercount", "2")
	map:addStartPosition("11", "2")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "20")
	map:setSetting("theme", "ice")
	map:setSetting("waterheight", "1.4")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "16")
	map:setSetting("wind", "0.0")
end
