function getName()
	return "Map 01"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-cave-art-01", 0, 0)
	map:addTile("tile-background-ice-03", 0, 1)
	map:addTile("tile-background-ice-02", 0, 2)
	map:addTile("tile-background-ice-04", 0, 3)
	map:addTile("tile-background-ice-cave-art-01", 0, 4)
	map:addTile("tile-background-ice-01", 0, 5)
	map:addTile("tile-ground-ledge-ice-left-02", 0, 6)
	map:addTile("tile-background-ice-03", 0, 7)
	map:addTile("tile-background-ice-04", 0, 8)
	map:addTile("tile-background-ice-02", 1, 0)
	map:addTile("tile-background-ice-05", 1, 1)
	map:addTile("tile-background-ice-07", 1, 2)
	map:addTile("tile-background-ice-07", 1, 3)
	map:addTile("tile-background-ice-01", 1, 4)
	map:addTile("tile-ground-ledge-ice-left-01", 1, 6)
	map:addTile("tile-background-ice-02", 1, 7)
	map:addTile("tile-background-ice-07", 1, 8)
	map:addTile("tile-background-ice-07", 2, 0)
	map:addTile("tile-background-ice-02", 2, 1)
	map:addTile("tile-background-ice-05", 2, 2)
	map:addTile("tile-background-ice-07", 2, 3)
	map:addTile("tile-background-ice-06", 2, 4)
	map:addTile("tile-background-ice-window-02", 2, 5)
	map:addTile("tile-ground-ledge-ice-right-01", 2, 6)
	map:addTile("tile-background-ice-01", 2, 7)
	map:addTile("tile-background-ice-07", 2, 8)
	map:addTile("tile-background-ice-03", 3, 0)
	map:addTile("tile-background-ice-04", 3, 1)
	map:addTile("tile-background-ice-02", 3, 2)
	map:addTile("tile-background-ice-05", 3, 3)
	map:addTile("tile-background-ice-07", 3, 4)
	map:addTile("tile-background-ice-07", 3, 5)
	map:addTile("tile-ground-ledge-ice-right-02", 3, 6)
	map:addTile("tile-background-ice-07", 3, 7)
	map:addTile("tile-background-ice-06", 3, 8)
	map:addTile("tile-background-ice-01", 4, 0)
	map:addTile("tile-background-ice-02", 4, 1)
	map:addTile("tile-background-ice-04", 4, 2)
	map:addTile("tile-background-ice-03", 4, 3)
	map:addTile("tile-background-ice-cave-art-01", 4, 4)
	map:addTile("tile-background-ice-04", 4, 5)
	map:addTile("tile-background-ice-04", 4, 6)
	map:addTile("tile-background-ice-cave-art-01", 4, 7)
	map:addTile("tile-background-ice-06", 4, 8)
	map:addTile("tile-background-ice-04", 5, 0)
	map:addTile("tile-background-ice-cave-art-01", 5, 1)
	map:addTile("tile-background-ice-07", 5, 2)
	map:addTile("tile-background-ice-cave-art-01", 5, 3)
	map:addTile("tile-background-ice-07", 5, 4)
	map:addTile("tile-background-ice-07", 5, 5)
	map:addTile("tile-background-ice-04", 5, 6)
	map:addTile("tile-background-ice-06", 5, 7)
	map:addTile("tile-background-ice-02", 5, 8)
	map:addTile("tile-background-ice-07", 6, 0)
	map:addTile("tile-background-ice-05", 6, 1)
	map:addTile("tile-background-ice-03", 6, 2)
	map:addTile("tile-background-ice-02", 6, 3)
	map:addTile("tile-ground-ledge-ice-left-02", 6, 4)
	map:addTile("tile-background-ice-07", 6, 5)
	map:addTile("tile-background-ice-02", 6, 6)
	map:addTile("tile-background-ice-06", 6, 7)
	map:addTile("tile-background-ice-03", 6, 8)
	map:addTile("tile-background-ice-big-01", 7, 0)
	map:addTile("tile-background-ice-05", 7, 2)
	map:addTile("tile-background-ice-cave-art-01", 7, 3)
	map:addTile("tile-ground-ledge-ice-left-01", 7, 4)
	map:addTile("tile-background-ice-07", 7, 5)
	map:addTile("tile-background-ice-02", 7, 6)
	map:addTile("tile-background-ice-02", 7, 7)
	map:addTile("tile-background-ice-cave-art-01", 7, 8)
	map:addTile("tile-background-ice-03", 8, 2)
	map:addTile("tile-background-ice-02", 8, 3)
	map:addTile("tile-packagetarget-ice-01-idle", 8, 4)
	map:addTile("tile-rock-slope-ice-left-02", 8, 5)
	map:addTile("tile-background-ice-07", 8, 6)
	map:addTile("tile-background-ice-04", 8, 7)
	map:addTile("tile-background-ice-01", 8, 8)
	map:addTile("tile-background-ice-03", 9, 0)
	map:addTile("tile-background-ice-01", 9, 1)
	map:addTile("tile-background-ice-02", 9, 2)
	map:addTile("tile-background-ice-05", 9, 3)
	map:addTile("tile-ground-ice-02", 9, 4)
	map:addTile("tile-rock-ice-big-01", 9, 5)
	map:addTile("tile-rock-ice-02", 9, 7)
	map:addTile("tile-rock-ice-01", 9, 8)
	map:addTile("tile-background-ice-cave-art-01", 10, 0)
	map:addTile("tile-background-ice-06", 10, 1)
	map:addTile("tile-background-ice-05", 10, 2)
	map:addTile("tile-background-ice-01", 10, 3)
	map:addTile("tile-ground-ice-04", 10, 4)
	map:addTile("tile-rock-ice-01", 10, 7)
	map:addTile("tile-rock-ice-02", 10, 8)
	map:addTile("tile-background-ice-06", 11, 0)
	map:addTile("tile-background-ice-01", 11, 1)
	map:addTile("tile-background-ice-cave-art-01", 11, 2)
	map:addTile("tile-background-ice-05", 11, 3)
	map:addTile("tile-ground-ice-03", 11, 4)
	map:addTile("tile-background-ice-07", 11, 5)
	map:addTile("tile-background-ice-cave-art-01", 11, 6)
	map:addTile("tile-ground-ledge-ice-right-01", 11, 8)
	map:addTile("tile-background-ice-03", 12, 0)
	map:addTile("tile-background-ice-01", 12, 1)
	map:addTile("tile-background-ice-02", 12, 2)
	map:addTile("tile-background-ice-06", 12, 3)
	map:addTile("tile-ground-ledge-ice-right-02", 12, 4)
	map:addTile("tile-background-ice-07", 12, 5)
	map:addTile("tile-background-ice-06", 12, 6)
	map:addTile("tile-background-ice-window-01", 12, 7)
	map:addTile("tile-ground-ledge-ice-right-02", 12, 8)
	map:addTile("tile-background-ice-07", 13, 0)
	map:addTile("tile-background-ice-07", 13, 1)
	map:addTile("tile-background-ice-cave-art-01", 13, 2)
	map:addTile("tile-background-ice-05", 13, 3)
	map:addTile("tile-background-ice-02", 13, 4)
	map:addTile("tile-background-ice-06", 13, 5)
	map:addTile("tile-background-ice-07", 13, 6)
	map:addTile("tile-background-ice-big-01", 13, 7)
	map:addTile("tile-background-ice-02", 14, 0)
	map:addTile("tile-background-ice-06", 14, 1)
	map:addTile("tile-background-ice-02", 14, 2)
	map:addTile("tile-background-ice-06", 14, 3)
	map:addTile("tile-background-ice-03", 14, 4)
	map:addTile("tile-background-ice-04", 14, 5)
	map:addTile("tile-background-ice-02", 14, 6)
	map:addTile("tile-background-ice-cave-art-01", 15, 0)
	map:addTile("tile-background-ice-06", 15, 1)
	map:addTile("tile-background-ice-03", 15, 2)
	map:addTile("tile-background-ice-07", 15, 3)
	map:addTile("tile-background-ice-07", 15, 4)
	map:addTile("tile-background-ice-07", 15, 5)
	map:addTile("tile-background-ice-07", 15, 6)
	map:addTile("tile-background-ice-05", 15, 7)
	map:addTile("tile-background-ice-07", 15, 8)

	map:addCave("tile-cave-ice-01", 1, 5)
	map:addCave("tile-cave-ice-02", 11, 7, "", 2000)

	map:addEmitter("item-stone", 10, 3, 1, 0, "")

	map:setSetting("width", "16")
	map:setSetting("height", "9")
	map:setSetting("fishnpc", "true")
	map:setSetting("flyingnpc", "true")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "4")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "40")
	map:setSetting("sideborderfail", "false")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "0.7")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
	map:addStartPosition("0", "5")
end
