function getName()
	return "Map 18"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-06", 0, 0)
	map:addTile("tile-ground-ice-01", 0, 2)
	map:addTile("tile-rock-ice-big-01", 0, 3)
	map:addTile("tile-background-ice-01", 0, 5)
	map:addTile("tile-background-ice-01", 0, 6)
	map:addTile("tile-background-ice-cave-art-01", 0, 7)
	map:addTile("tile-ground-ice-03", 0, 8)
	map:addTile("tile-rock-ice-big-01", 0, 9)
	map:addTile("tile-rock-ice-02", 0, 11)
	map:addTile("tile-background-ice-03", 1, 0)
	map:addTile("tile-background-ice-window-02", 1, 1)
	map:addTile("tile-ground-ice-01", 1, 2)
	map:addTile("tile-background-ice-01", 1, 5)
	map:addTile("tile-background-ice-06", 1, 6)
	map:addTile("tile-ground-ice-01", 1, 8)
	map:addTile("tile-rock-ice-03", 1, 11)
	map:addTile("tile-background-ice-02", 2, 0)
	map:addTile("tile-background-ice-03", 2, 1)
	map:addTile("tile-ground-ice-05", 2, 2)
	map:addTile("tile-background-ice-02", 2, 3)
	map:addTile("tile-background-ice-04", 2, 4)
	map:addTile("tile-background-ice-big-01", 2, 5)
	map:addTile("tile-background-ice-window-01", 2, 7)
	map:addTile("tile-ground-ice-03", 2, 8)
	map:addTile("tile-rock-ice-03", 2, 9)
	map:addTile("tile-rock-ice-02", 2, 10)
	map:addTile("tile-rock-ice-02", 2, 11)
	map:addTile("tile-background-ice-07", 3, 0)
	map:addTile("tile-background-ice-07", 3, 1)
	map:addTile("tile-background-ice-05", 3, 2)
	map:addTile("tile-background-ice-03", 3, 3)
	map:addTile("tile-background-ice-07", 3, 4)
	map:addTile("tile-background-ice-04", 3, 7)
	map:addTile("tile-ground-ice-01", 3, 8)
	map:addTile("tile-rock-ice-02", 3, 9)
	map:addTile("tile-rock-ice-03", 3, 10)
	map:addTile("tile-rock-ice-03", 3, 11)
	map:addTile("tile-background-ice-06", 4, 0)
	map:addTile("tile-background-ice-big-01", 4, 1)
	map:addTile("tile-background-ice-07", 4, 3)
	map:addTile("tile-background-ice-03", 4, 4)
	map:addTile("tile-background-ice-06", 4, 5)
	map:addTile("tile-background-ice-07", 4, 6)
	map:addTile("tile-background-ice-07", 4, 7)
	map:addTile("tile-ground-ice-02", 4, 8)
	map:addTile("tile-ground-ice-01", 4, 9)
	map:addTile("tile-rock-ice-01", 4, 10)
	map:addTile("tile-rock-ice-02", 4, 11)
	map:addTile("tile-background-ice-04", 5, 0)
	map:addTile("tile-background-ice-07", 5, 3)
	map:addTile("tile-ground-ice-02", 5, 4)
	map:addTile("tile-rock-ice-01", 5, 5)
	map:addTile("tile-rock-ice-01", 5, 6)
	map:addTile("tile-rock-ice-big-01", 5, 7)
	map:addTile("tile-rock-ice-03", 5, 9)
	map:addTile("tile-rock-ice-03", 5, 10)
	map:addTile("tile-rock-ice-03", 5, 11)
	map:addTile("tile-background-ice-05", 6, 0)
	map:addTile("tile-background-ice-02", 6, 1)
	map:addTile("tile-background-ice-04", 6, 2)
	map:addTile("tile-background-ice-04", 6, 3)
	map:addTile("tile-ground-ice-03", 6, 4)
	map:addTile("tile-rock-slope-ice-right-02", 6, 5)
	map:addTile("tile-rock-slope-ice-right-01", 6, 6)
	map:addTile("tile-rock-ice-02", 6, 9)
	map:addTile("tile-rock-ice-01", 6, 10)
	map:addTile("tile-rock-ice-03", 6, 11)
	map:addTile("tile-background-ice-05", 7, 0)
	map:addTile("tile-background-ice-02", 7, 1)
	map:addTile("tile-background-ice-01", 7, 2)
	map:addTile("tile-background-ice-03", 7, 3)
	map:addTile("tile-ground-ice-02", 7, 4)
	map:addTile("tile-ground-ledge-ice-left-01", 7, 5)
	map:addTile("tile-background-ice-07", 7, 6)
	map:addTile("tile-packagetarget-ice-01-idle", 7, 7)
	map:addTile("tile-ground-ice-04", 7, 8)
	map:addTile("tile-rock-ice-01", 7, 9)
	map:addTile("tile-rock-ice-03", 7, 10)
	map:addTile("tile-rock-ice-03", 7, 11)
	map:addTile("tile-background-ice-04", 8, 0)
	map:addTile("tile-background-ice-01", 8, 1)
	map:addTile("tile-background-ice-03", 8, 2)
	map:addTile("tile-background-ice-07", 8, 3)
	map:addTile("tile-ground-ice-03", 8, 4)
	map:addTile("tile-rock-ice-01", 8, 5)
	map:addTile("tile-rock-slope-ice-left-02", 8, 6)
	map:addTile("tile-geyser-ice-01-active", 8, 7)
	map:addTile("tile-rock-ice-03", 8, 9)
	map:addTile("tile-rock-ice-big-01", 8, 10)
	map:addTile("tile-background-ice-03", 9, 0)
	map:addTile("tile-background-ice-07", 9, 1)
	map:addTile("tile-background-ice-02", 9, 2)
	map:addTile("tile-background-ice-06", 9, 3)
	map:addTile("tile-ground-ledge-ice-right-02", 9, 4)
	map:addTile("tile-background-ice-big-01", 9, 5)
	map:addTile("tile-rock-slope-ice-left-01", 9, 7)
	map:addTile("tile-rock-ice-02", 9, 8)
	map:addTile("tile-rock-ice-02", 9, 9)
	map:addTile("tile-background-ice-big-01", 10, 0)
	map:addTile("tile-background-ice-01", 10, 2)
	map:addTile("tile-background-ice-01", 10, 3)
	map:addTile("tile-background-ice-03", 10, 4)
	map:addTile("tile-rock-slope-ice-right-01", 10, 7)
	map:addTile("tile-rock-ice-02", 10, 8)
	map:addTile("tile-rock-ice-02", 10, 9)
	map:addTile("tile-rock-ice-02", 10, 10)
	map:addTile("tile-rock-ice-03", 10, 11)
	map:addTile("tile-background-ice-01", 11, 2)
	map:addTile("tile-background-ice-03", 11, 3)
	map:addTile("tile-background-ice-07", 11, 4)
	map:addTile("tile-background-ice-07", 11, 5)
	map:addTile("tile-background-ice-07", 11, 6)
	map:addTile("tile-background-ice-02", 11, 7)
	map:addTile("tile-background-ice-02", 11, 8)
	map:addTile("tile-ground-ice-01", 11, 9)
	map:addTile("tile-rock-ice-big-01", 11, 10)
	map:addTile("tile-background-ice-03", 12, 0)
	map:addTile("tile-background-ice-02", 12, 1)
	map:addTile("tile-background-ice-cave-art-01", 12, 2)
	map:addTile("tile-background-ice-04", 12, 3)
	map:addTile("tile-background-ice-06", 12, 4)
	map:addTile("tile-background-ice-02", 12, 5)
	map:addTile("tile-ground-ice-05", 12, 6)
	map:addTile("tile-background-ice-01", 12, 7)
	map:addTile("tile-background-ice-02", 12, 8)
	map:addTile("tile-ground-ice-03", 12, 9)
	map:addTile("tile-ground-ledge-ice-left-02", 13, 0)
	map:addTile("tile-background-ice-01", 13, 1)
	map:addTile("tile-ground-ice-05", 13, 3)
	map:addTile("tile-background-ice-05", 13, 4)
	map:addTile("tile-ground-ice-05", 13, 6)
	map:addTile("tile-background-ice-04", 13, 7)
	map:addTile("tile-ground-ice-04", 13, 9)
	map:addTile("tile-rock-ice-02", 13, 10)
	map:addTile("tile-rock-ice-03", 13, 11)
	map:addTile("tile-ground-ledge-ice-left-01", 14, 0)
	map:addTile("tile-background-ice-06", 14, 1)
	map:addTile("tile-background-ice-window-02", 14, 2)
	map:addTile("tile-ground-ice-05", 14, 3)
	map:addTile("tile-background-ice-07", 14, 4)
	map:addTile("tile-background-ice-window-01", 14, 5)
	map:addTile("tile-ground-ice-05", 14, 6)
	map:addTile("tile-background-ice-06", 14, 7)
	map:addTile("tile-background-ice-window-02", 14, 8)
	map:addTile("tile-ground-ice-04", 14, 9)
	map:addTile("tile-rock-ice-big-01", 14, 10)
	map:addTile("tile-rock-ice-01", 15, 0)
	map:addTile("tile-rock-ice-02", 15, 1)
	map:addTile("tile-rock-ice-03", 15, 2)
	map:addTile("tile-rock-ice-02", 15, 3)
	map:addTile("tile-rock-ice-01", 15, 4)
	map:addTile("tile-rock-ice-02", 15, 5)
	map:addTile("tile-rock-ice-03", 15, 6)
	map:addTile("tile-rock-ice-02", 15, 7)
	map:addTile("tile-rock-ice-01", 15, 8)
	map:addTile("tile-ground-ice-03", 15, 9)

	map:addCave("tile-cave-ice-01", 0, 1, "none", 2000)
	map:addCave("tile-cave-ice-01", 1, 7, "none", 1000)
	map:addCave("tile-cave-ice-01", 13, 2, "none", 2000)
	map:addCave("tile-cave-ice-01", 13, 5, "none", 3000)
	map:addCave("tile-cave-ice-01", 13, 8, "none", 500)

	map:addEmitter("tree", 5, 2, 1, 0, "")
	map:addEmitter("npc-walking", 5, 3, 1, 0, "")
	map:addEmitter("item-stone", 8, 3, 1, 0, "")

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "12")
	map:setSetting("packagetransfercount", "3")
	map:addStartPosition("11", "8")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "40")
	map:setSetting("theme", "ice")
	map:setSetting("waterheight", "1")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "16")
	map:setSetting("wind", "0.0")
end
