function getName()
	return "Map 04"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-06", 0, 0)
	map:addTile("tile-background-ice-05", 0, 1)
	map:addTile("tile-background-ice-06", 0, 2)
	map:addTile("tile-background-ice-07", 0, 3)
	map:addTile("tile-background-ice-07", 0, 4)
	map:addTile("tile-background-ice-07", 0, 5)
	map:addTile("tile-background-ice-cave-art-01", 0, 6)
	map:addTile("tile-background-ice-03", 0, 7)
	map:addTile("tile-background-ice-04", 0, 8)
	map:addTile("tile-background-ice-02", 0, 9)
	map:addTile("tile-background-ice-02", 0, 10)
	map:addTile("tile-background-ice-03", 0, 11)
	map:addTile("tile-background-ice-big-01", 1, 0)
	map:addTile("tile-background-ice-06", 1, 2)
	map:addTile("tile-background-ice-04", 1, 3)
	map:addTile("tile-background-ice-07", 1, 4)
	map:addTile("tile-background-ice-06", 1, 5)
	map:addTile("tile-background-ice-05", 1, 6)
	map:addTile("tile-background-ice-01", 1, 7)
	map:addTile("tile-background-ice-05", 1, 8)
	map:addTile("tile-background-ice-01", 1, 9)
	map:addTile("tile-background-ice-05", 1, 10)
	map:addTile("tile-background-ice-06", 1, 11)
	map:addTile("tile-background-ice-01", 2, 2)
	map:addTile("tile-background-ice-01", 2, 3)
	map:addTile("tile-ground-ledge-ice-left-01", 2, 4)
	map:addTile("tile-background-ice-04", 2, 5)
	map:addTile("tile-background-ice-01", 2, 6)
	map:addTile("tile-background-ice-big-01", 2, 7)
	map:addTile("tile-background-ice-04", 2, 9)
	map:addTile("tile-background-ice-06", 2, 10)
	map:addTile("tile-background-ice-03", 2, 11)
	map:addTile("tile-background-ice-03", 3, 0)
	map:addTile("tile-background-ice-07", 3, 1)
	map:addTile("tile-background-ice-06", 3, 2)
	map:addTile("tile-background-ice-04", 3, 3)
	map:addTile("tile-ground-ice-02", 3, 4)
	map:addTile("tile-rock-ice-02", 3, 5)
	map:addTile("tile-background-ice-02", 3, 6)
	map:addTile("tile-background-ice-06", 3, 9)
	map:addTile("tile-background-ice-cave-art-01", 3, 10)
	map:addTile("tile-background-ice-06", 3, 11)
	map:addTile("tile-background-ice-06", 4, 0)
	map:addTile("tile-background-ice-01", 4, 1)
	map:addTile("tile-background-ice-05", 4, 2)
	map:addTile("tile-background-ice-02", 4, 3)
	map:addTile("tile-ground-ice-03", 4, 4)
	map:addTile("tile-rock-ice-03", 4, 5)
	map:addTile("tile-ground-ledge-ice-left-02", 4, 6)
	map:addTile("tile-background-ice-03", 4, 7)
	map:addTile("tile-background-ice-big-01", 4, 8)
	map:addTile("tile-background-ice-03", 4, 10)
	map:addTile("tile-background-ice-03", 4, 11)
	map:addTile("tile-background-ice-03", 5, 0)
	map:addTile("tile-background-ice-03", 5, 1)
	map:addTile("tile-ground-ledge-ice-left-02", 5, 2)
	map:addTile("tile-ground-ice-04", 5, 4)
	map:addTile("tile-rock-ice-big-01", 5, 5)
	map:addTile("tile-background-ice-04", 5, 7)
	map:addTile("tile-background-ice-01", 5, 10)
	map:addTile("tile-background-ice-03", 5, 11)
	map:addTile("tile-background-ice-01", 6, 0)
	map:addTile("tile-background-ice-05", 6, 1)
	map:addTile("tile-ground-ice-02", 6, 2)
	map:addTile("tile-rock-ice-big-01", 6, 3)
	map:addTile("tile-background-ice-03", 6, 7)
	map:addTile("tile-background-ice-03", 6, 8)
	map:addTile("tile-background-ice-04", 6, 9)
	map:addTile("tile-background-ice-04", 6, 10)
	map:addTile("tile-background-ice-06", 6, 11)
	map:addTile("tile-background-ice-01", 7, 0)
	map:addTile("tile-background-ice-05", 7, 1)
	map:addTile("tile-ground-ice-01", 7, 2)
	map:addTile("tile-rock-ice-03", 7, 5)
	map:addTile("tile-rock-ice-02", 7, 6)
	map:addTile("tile-background-ice-02", 7, 7)
	map:addTile("tile-background-ice-cave-art-01", 7, 8)
	map:addTile("tile-background-ice-03", 7, 9)
	map:addTile("tile-background-ice-03", 7, 10)
	map:addTile("tile-background-ice-03", 7, 11)
	map:addTile("tile-background-ice-01", 8, 0)
	map:addTile("tile-background-ice-03", 8, 1)
	map:addTile("tile-ground-ledge-ice-right-02", 8, 2)
	map:addTile("tile-background-ice-cave-art-01", 8, 3)
	map:addTile("tile-ground-ice-01", 8, 4)
	map:addTile("tile-rock-ice-03", 8, 5)
	map:addTile("tile-ground-ledge-ice-right-01", 8, 6)
	map:addTile("tile-background-ice-05", 8, 7)
	map:addTile("tile-background-ice-02", 8, 8)
	map:addTile("tile-background-ice-04", 8, 9)
	map:addTile("tile-background-ice-03", 8, 10)
	map:addTile("tile-background-ice-06", 8, 11)
	map:addTile("tile-background-ice-04", 9, 0)
	map:addTile("tile-background-ice-01", 9, 1)
	map:addTile("tile-background-ice-06", 9, 2)
	map:addTile("tile-ground-ice-04", 9, 4)
	map:addTile("tile-rock-slope-ice-right-02", 9, 5)
	map:addTile("tile-background-ice-04", 9, 6)
	map:addTile("tile-background-ice-04", 9, 7)
	map:addTile("tile-background-ice-02", 9, 8)
	map:addTile("tile-background-ice-03", 9, 9)
	map:addTile("tile-background-ice-03", 9, 10)
	map:addTile("tile-background-ice-03", 9, 11)
	map:addTile("tile-background-ice-04", 10, 0)
	map:addTile("tile-background-ice-03", 10, 1)
	map:addTile("tile-background-ice-cave-art-01", 10, 2)
	map:addTile("tile-background-ice-06", 10, 3)
	map:addTile("tile-background-ice-07", 10, 4)
	map:addTile("tile-background-ice-07", 10, 5)
	map:addTile("tile-background-ice-01", 10, 6)
	map:addTile("tile-background-ice-07", 10, 7)
	map:addTile("tile-background-ice-06", 10, 8)
	map:addTile("tile-ground-ice-03", 10, 9)
	map:addTile("tile-rock-ice-01", 10, 10)
	map:addTile("tile-rock-ice-03", 10, 11)
	map:addTile("tile-background-ice-07", 11, 0)
	map:addTile("tile-background-ice-04", 11, 1)
	map:addTile("tile-background-ice-07", 11, 2)
	map:addTile("tile-background-ice-03", 11, 3)
	map:addTile("tile-background-ice-big-01", 11, 4)
	map:addTile("tile-background-ice-big-01", 11, 6)
	map:addTile("tile-background-ice-01", 11, 8)
	map:addTile("tile-ground-ice-01", 11, 9)
	map:addTile("tile-rock-ice-03", 11, 10)
	map:addTile("tile-rock-ice-01", 11, 11)
	map:addTile("tile-background-ice-cave-art-01", 12, 0)
	map:addTile("tile-background-ice-cave-art-01", 12, 1)
	map:addTile("tile-background-ice-04", 12, 2)
	map:addTile("tile-ground-ledge-ice-left-02", 12, 3)
	map:addTile("tile-background-ice-06", 12, 8)
	map:addTile("tile-ground-ice-01", 12, 9)
	map:addTile("tile-rock-ice-02", 12, 10)
	map:addTile("tile-rock-ice-02", 12, 11)
	map:addTile("tile-background-ice-big-01", 13, 0)
	map:addTile("tile-background-ice-04", 13, 2)
	map:addTile("tile-rock-slope-ice-right-01", 13, 3)
	map:addTile("tile-rock-slope-ice-left-02", 13, 4)
	map:addTile("tile-background-ice-05", 13, 5)
	map:addTile("tile-background-ice-04", 13, 6)
	map:addTile("tile-background-ice-06", 13, 7)
	map:addTile("tile-waterfall-ice-01", 13, 8)
	map:addTile("tile-rock-ice-01", 13, 10)
	map:addTile("tile-rock-ice-02", 13, 11)
	map:addTile("tile-ground-ice-02", 14, 2)
	map:addTile("tile-rock-slope-ice-left-02", 14, 3)
	map:addTile("tile-rock-slope-ice-right-01", 14, 4)
	map:addTile("tile-ground-ledge-ice-right-02", 14, 5)
	map:addTile("tile-background-ice-01", 14, 6)
	map:addTile("tile-background-ice-cave-art-01", 14, 7)
	map:addTile("tile-background-ice-04", 14, 8)
	map:addTile("tile-packagetarget-ice-01-idle", 14, 9)
	map:addTile("tile-rock-ice-03", 14, 10)
	map:addTile("tile-rock-ice-01", 14, 11)
	map:addTile("tile-background-ice-04", 15, 0)
	map:addTile("tile-background-ice-01", 15, 1)
	map:addTile("tile-ground-ice-02", 15, 2)
	map:addTile("tile-rock-ice-01", 15, 3)
	map:addTile("tile-rock-slope-ice-left-02", 15, 4)
	map:addTile("tile-rock-slope-ice-left-01", 15, 5)
	map:addTile("tile-background-ice-02", 15, 6)
	map:addTile("tile-background-ice-05", 15, 7)
	map:addTile("tile-geyser-ice-01-active", 15, 8)
	map:addTile("tile-rock-ice-03", 15, 10)
	map:addTile("tile-rock-ice-01", 15, 11)

	map:addCave("tile-cave-ice-01", 5, 3, "none", 5000)
	map:addCave("tile-cave-ice-02", 9, 3, "none", 5000)

	map:addEmitter("npc-walking", 11, 8, 1, 0, "")
	map:addEmitter("item-stone", 13.2, 7, 1, 0, "")

	map:setSetting("width", "16")
	map:setSetting("height", "12")
	map:setSetting("fishnpc", "true")
	map:setSetting("flyingnpc", "true")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "3")
	map:setSetting("playerX", "2")
	map:setSetting("playerY", "3")
	map:setSetting("points", "120")
	map:setSetting("referencetime", "40")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "2")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
