function getName()
	return "Map 20"
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-rock-ice-01", 0, 0)
	map:addTile("tile-ground-ledge-ice-right-01", 0, 1)
	map:addTile("tile-background-ice-05", 0, 2)
	map:addTile("tile-background-ice-05", 0, 3)
	map:addTile("tile-background-ice-05", 0, 4)
	map:addTile("tile-ground-ice-01", 0, 5)
	map:addTile("tile-rock-ice-01", 0, 6)
	map:addTile("tile-rock-ice-big-01", 0, 7)
	map:addTile("tile-rock-ice-01", 0, 9)
	map:addTile("tile-rock-ice-big-01", 0, 10)
	map:addTile("tile-rock-ice-02", 1, 0)
	map:addTile("tile-ground-ledge-ice-right-02", 1, 1)
	map:addTile("tile-background-ice-01", 1, 2)
	map:addTile("tile-background-ice-06", 1, 3)
	map:addTile("tile-background-ice-01", 1, 4)
	map:addTile("tile-rock-ice-03", 1, 5)
	map:addTile("tile-rock-ice-01", 1, 6)
	map:addTile("tile-rock-ice-02", 1, 9)
	map:addTile("tile-rock-slope-ice-right-02", 2, 0)
	map:addTile("tile-background-ice-05", 2, 1)
	map:addTile("tile-background-ice-05", 2, 2)
	map:addTile("tile-background-ice-06", 2, 3)
	map:addTile("tile-background-ice-06", 2, 4)
	map:addTile("tile-ground-ledge-ice-right-01", 2, 6)
	map:addTile("tile-background-ice-07", 2, 7)
	map:addTile("tile-background-ice-05", 2, 8)
	map:addTile("tile-ground-ice-03", 2, 9)
	map:addTile("tile-rock-ice-02", 2, 10)
	map:addTile("tile-rock-ice-01", 2, 11)
	map:addTile("tile-background-ice-06", 3, 0)
	map:addTile("tile-background-ice-04", 3, 1)
	map:addTile("tile-background-ice-05", 3, 2)
	map:addTile("tile-background-ice-01", 3, 3)
	map:addTile("tile-background-ice-07", 3, 4)
	map:addTile("tile-background-ice-window-02", 3, 5)
	map:addTile("tile-ground-ice-05", 3, 6)
	map:addTile("tile-background-ice-07", 3, 7)
	map:addTile("tile-background-ice-07", 3, 8)
	map:addTile("tile-packagetarget-ice-01-idle", 3, 9)
	map:addTile("tile-rock-ice-big-01", 3, 10)
	map:addTile("tile-background-ice-big-01", 4, 0)
	map:addTile("tile-background-ice-02", 4, 2)
	map:addTile("tile-background-ice-06", 4, 3)
	map:addTile("tile-background-ice-01", 4, 4)
	map:addTile("tile-background-ice-01", 4, 5)
	map:addTile("tile-background-ice-02", 4, 6)
	map:addTile("tile-background-ice-01", 4, 7)
	map:addTile("tile-background-ice-01", 4, 8)
	map:addTile("tile-ground-ice-03", 4, 9)
	map:addTile("tile-background-ice-window-01", 5, 2)
	map:addTile("tile-ground-ice-05", 5, 3)
	map:addTile("tile-background-ice-04", 5, 4)
	map:addTile("tile-background-ice-03", 5, 5)
	map:addTile("tile-background-ice-04", 5, 6)
	map:addTile("tile-background-ice-big-01", 5, 7)
	map:addTile("tile-background-ice-big-01", 5, 9)
	map:addTile("tile-background-ice-05", 5, 11)
	map:addTile("tile-background-ice-07", 6, 0)
	map:addTile("tile-background-ice-03", 6, 1)
	map:addTile("tile-ground-ice-05", 6, 3)
	map:addTile("tile-background-ice-01", 6, 4)
	map:addTile("tile-background-ice-04", 6, 5)
	map:addTile("tile-ground-ice-05", 6, 6)
	map:addTile("tile-background-ice-05", 6, 11)
	map:addTile("tile-rock-ice-03", 7, 0)
	map:addTile("tile-rock-ice-01", 7, 1)
	map:addTile("tile-rock-ice-03", 7, 2)
	map:addTile("tile-rock-ice-02", 7, 3)
	map:addTile("tile-rock-ice-01", 7, 4)
	map:addTile("tile-rock-ice-02", 7, 5)
	map:addTile("tile-rock-shim-ice-01", 7, 6)
	map:addTile("tile-background-ice-06", 7, 7)
	map:addTile("tile-background-ice-02", 7, 8)
	map:addTile("tile-background-ice-01", 7, 9)
	map:addTile("tile-background-ice-05", 7, 10)
	map:addTile("tile-background-ice-05", 7, 11)
	map:addTile("tile-background-ice-03", 8, 0)
	map:addTile("tile-background-ice-04", 8, 1)
	map:addTile("tile-ground-ice-05", 8, 3)
	map:addTile("tile-background-ice-01", 8, 4)
	map:addTile("tile-background-ice-06", 8, 5)
	map:addTile("tile-ground-ice-05", 8, 6)
	map:addTile("tile-background-ice-04", 8, 7)
	map:addTile("tile-background-ice-07", 8, 8)
	map:addTile("tile-ground-ice-04", 8, 9)
	map:addTile("tile-rock-slope-ice-left-02", 8, 10)
	map:addTile("tile-background-ice-05", 8, 11)
	map:addTile("tile-background-ice-02", 9, 0)
	map:addTile("tile-background-ice-06", 9, 1)
	map:addTile("tile-background-ice-window-02", 9, 2)
	map:addTile("tile-ground-ice-05", 9, 3)
	map:addTile("tile-background-ice-01", 9, 4)
	map:addTile("tile-background-ice-05", 9, 5)
	map:addTile("tile-background-ice-06", 9, 6)
	map:addTile("tile-background-ice-02", 9, 7)
	map:addTile("tile-background-ice-window-02", 9, 8)
	map:addTile("tile-ground-ice-04", 9, 9)
	map:addTile("tile-rock-ice-01", 9, 10)
	map:addTile("tile-rock-ice-01", 9, 11)
	map:addTile("tile-background-ice-04", 10, 0)
	map:addTile("tile-background-ice-06", 10, 1)
	map:addTile("tile-background-ice-01", 10, 2)
	map:addTile("tile-background-ice-03", 10, 3)
	map:addTile("tile-background-ice-05", 10, 4)
	map:addTile("tile-background-ice-04", 10, 5)
	map:addTile("tile-background-ice-01", 10, 6)
	map:addTile("tile-background-ice-07", 10, 7)
	map:addTile("tile-ground-ice-01", 10, 9)
	map:addTile("tile-rock-ice-03", 10, 10)
	map:addTile("tile-rock-ice-02", 10, 11)
	map:addTile("tile-background-ice-04", 11, 0)
	map:addTile("tile-background-ice-06", 11, 1)
	map:addTile("tile-background-ice-01", 11, 2)
	map:addTile("tile-background-ice-04", 11, 3)
	map:addTile("tile-background-ice-01", 11, 4)
	map:addTile("tile-background-ice-03", 11, 5)
	map:addTile("tile-background-ice-05", 11, 6)
	map:addTile("tile-background-ice-01", 11, 7)
	map:addTile("tile-background-ice-07", 11, 8)
	map:addTile("tile-ground-ice-04", 11, 9)
	map:addTile("tile-rock-ice-01", 11, 10)
	map:addTile("tile-rock-ice-02", 11, 11)
	map:addTile("tile-background-ice-05", 12, 0)
	map:addTile("tile-background-ice-06", 12, 1)
	map:addTile("tile-background-ice-05", 12, 2)
	map:addTile("tile-background-ice-03", 12, 3)
	map:addTile("tile-background-ice-02", 12, 4)
	map:addTile("tile-background-ice-03", 12, 5)
	map:addTile("tile-background-ice-06", 12, 6)
	map:addTile("tile-background-ice-07", 12, 7)
	map:addTile("tile-background-ice-05", 12, 8)
	map:addTile("tile-ground-ice-04", 12, 9)
	map:addTile("tile-rock-ice-big-01", 12, 10)
	map:addTile("tile-ground-ledge-ice-left-02", 13, 0)
	map:addTile("tile-background-ice-06", 13, 1)
	map:addTile("tile-background-ice-06", 13, 2)
	map:addTile("tile-ground-ice-05", 13, 3)
	map:addTile("tile-background-ice-02", 13, 4)
	map:addTile("tile-background-ice-01", 13, 5)
	map:addTile("tile-background-ice-07", 13, 6)
	map:addTile("tile-ground-ice-01", 13, 7)
	map:addTile("tile-rock-ice-02", 13, 8)
	map:addTile("tile-rock-ice-03", 13, 9)
	map:addTile("tile-ground-ledge-ice-left-01", 14, 0)
	map:addTile("tile-background-ice-01", 14, 1)
	map:addTile("tile-background-ice-window-02", 14, 2)
	map:addTile("tile-ground-ice-05", 14, 3)
	map:addTile("tile-background-ice-07", 14, 4)
	map:addTile("tile-background-ice-04", 14, 5)
	map:addTile("tile-background-ice-04", 14, 6)
	map:addTile("tile-ground-ice-03", 14, 7)
	map:addTile("tile-rock-ice-03", 14, 8)
	map:addTile("tile-rock-ice-big-01", 14, 9)
	map:addTile("tile-rock-ice-03", 14, 11)
	map:addTile("tile-rock-ice-01", 15, 0)
	map:addTile("tile-rock-slope-ice-left-02", 15, 1)
	map:addTile("tile-ground-ice-05", 15, 3)
	map:addTile("tile-background-ice-07", 15, 4)
	map:addTile("tile-background-ice-07", 15, 5)
	map:addTile("tile-background-ice-04", 15, 6)
	map:addTile("tile-packagetarget-ice-01-idle", 15, 7)
	map:addTile("tile-rock-ice-02", 15, 8)
	map:addTile("tile-rock-ice-02", 15, 11)

	map:addCave("tile-cave-ice-01", 2, 5, "none", 1000)
	map:addCave("tile-cave-ice-01", 6, 2, "none", 2000)
	map:addCave("tile-cave-ice-02", 8, 2, "none", 3000)
	map:addCave("tile-cave-ice-01", 10, 8, "none", 4000)
	map:addCave("tile-cave-ice-01", 15, 2)

	map:addEmitter("tree", 0, 3, 1, 0)
	map:addEmitter("item-stone", 2, 8, 1, 0)
	map:addEmitter("item-stone", 8, 5, 1, 0)

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "true")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "12")
	map:setSetting("packagetransfercount", "6")
	map:addStartPosition("11", "8")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "30")
	map:setSetting("theme", "ice")
	map:setSetting("waterheight", "1.9")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "16")
	map:setSetting("wind", "0.0")
end
