function getName()
	return "Flying"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-rock-03", 0, 0)
	map:addTile("tile-rock-02", 0, 1)
	map:addTile("tile-rock-big-01", 0, 2)
	map:addTile("tile-rock-02", 0, 4)
	map:addTile("tile-rock-big-01", 0, 5)
	map:addTile("tile-rock-01", 0, 7)
	map:addTile("tile-rock-02", 0, 8)
	map:addTile("tile-rock-big-01", 1, 0)
	map:addTile("tile-rock-03", 1, 4)
	map:addTile("tile-rock-big-01", 1, 7)
	map:addTile("tile-rock-02", 2, 2)
	map:addTile("tile-rock-03", 2, 3)
	map:addTile("tile-rock-02", 2, 4)
	map:addTile("tile-rock-03", 2, 5)
	map:addTile("tile-rock-02", 2, 6)
	map:addTile("tile-rock-02", 3, 0)
	map:addTile("tile-rock-03", 3, 1)
	map:addTile("tile-rock-01", 3, 2)
	map:addTile("tile-rock-left-04", 3, 3)
	map:addTile("tile-ground-06", 3, 4)
	map:addTile("tile-background-03", 3, 5)
	map:addTile("tile-ground-01", 3, 6)
	map:addTile("tile-rock-02", 3, 7)
	map:addTile("tile-rock-slope-right-02", 3, 8)
	map:addTile("tile-rock-03", 4, 0)
	map:addTile("tile-rock-02", 4, 1)
	map:addTile("tile-rock-slope-right-02", 4, 2)
	map:addTile("tile-background-03", 4, 3)
	map:addTile("tile-ground-05", 4, 4)
	map:addTile("tile-background-04", 4, 5)
	map:addTile("tile-background-02", 4, 6)
	map:addTile("bridge-wall-left-01", 4, 6)
	map:addTile("tile-background-04", 4, 7)
	map:addTile("tile-background-cave-art-01", 4, 8)
	map:addTile("tile-rock-slope-right-02", 5, 0)
	map:addTile("tile-background-04", 5, 1)
	map:addTile("tile-background-04", 5, 2)
	map:addTile("tile-background-03", 5, 3)
	map:addTile("tile-background-04", 5, 4)
	map:addTile("tile-background-04", 5, 5)
	map:addTile("tile-background-02", 5, 6)
	map:addTile("bridge-wall-right-01", 5, 6)
	map:addTile("tile-background-02", 5, 7)
	map:addTile("tile-background-02", 5, 8)
	map:addTile("tile-background-02", 6, 0)
	map:addTile("tile-background-03", 6, 1)
	map:addTile("tile-background-04", 6, 2)
	map:addTile("tile-background-03", 6, 3)
	map:addTile("tile-ground-ledge-left-02", 6, 4)
	map:addTile("tile-background-04", 6, 5)
	map:addTile("tile-ground-03", 6, 6)
	map:addTile("tile-rock-slope-left-02", 6, 7)
	map:addTile("tile-background-02", 6, 8)
	map:addTile("tile-rock-shim-01", 7, 0)
	map:addTile("tile-background-04", 7, 1)
	map:addTile("tile-background-03", 7, 2)
	map:addTile("tile-background-04", 7, 3)
	map:addTile("tile-ground-ledge-right-02", 7, 4)
	map:addTile("tile-background-04", 7, 5)
	map:addTile("tile-ground-04", 7, 6)
	map:addTile("tile-rock-02", 7, 7)
	map:addTile("tile-rock-slope-left-02", 7, 8)
	map:addTile("tile-background-04", 8, 0)
	map:addTile("tile-background-04", 8, 1)
	map:addTile("tile-background-03", 8, 2)
	map:addTile("tile-background-04", 8, 3)
	map:addTile("tile-background-04", 8, 4)
	map:addTile("tile-background-03", 8, 5)
	map:addTile("tile-packagetarget-rock-01-idle", 8, 6)
	map:addTile("tile-rock-02", 8, 7)
	map:addTile("tile-rock-01", 8, 8)
	map:addTile("tile-rock-02", 9, 0)
	map:addTile("tile-rock-slope-left-02", 9, 1)
	map:addTile("tile-background-01", 9, 2)
	map:addTile("tile-background-03", 9, 3)
	map:addTile("tile-ground-ledge-left-02", 9, 4)
	map:addTile("tile-background-04", 9, 5)
	map:addTile("tile-ground-01", 9, 6)
	map:addTile("tile-rock-03", 9, 7)
	map:addTile("tile-rock-02", 9, 8)
	map:addTile("tile-rock-big-01", 10, 0)
	map:addTile("tile-rock-right-04", 10, 2)
	map:addTile("tile-rock-right-04", 10, 3)
	map:addTile("tile-rock-03", 10, 4)
	map:addTile("tile-rock-big-01", 10, 5)
	map:addTile("tile-rock-big-01", 10, 7)
	map:addTile("tile-rock-big-01", 11, 2)
	map:addTile("tile-rock-02", 11, 4)
	map:addTile("tile-rock-03", 12, 0)
	map:addTile("tile-rock-02", 12, 1)
	map:addTile("tile-rock-03", 12, 4)
	map:addTile("tile-rock-02", 12, 5)
	map:addTile("tile-rock-02", 12, 6)
	map:addTile("tile-rock-02", 12, 7)
	map:addTile("tile-rock-01", 12, 8)
	map:addEmitter("item-stone", 5, 1, 1, 4100, "")
	map:addEmitter("item-package", 8.2, 1, 1, 5000, "")

	map:setSetting("width", "13")
	map:setSetting("height", "9")
	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "true")
	map:setSetting("gravity", "9.81")
	map:setSetting("initialspawntime", "0")
	map:setSetting("introwindow", "introflying")
	map:setSetting("packagetransfercount", "1")
	map:addStartPosition("3", "5")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "20")
	map:setSetting("sideborderfail", "false")
	map:setSetting("theme", "rock")
	map:setSetting("tutorial", "true")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "0.5")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0")
end
