function getName()
	return "Find your way"
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-rock-01", 0, 0)
	map:addTile("tile-background-04", 0, 1)
	map:addTile("tile-background-01", 0, 2)
	map:addTile("tile-background-04", 0, 3)
	map:addTile("tile-ground-04", 0, 4)
	map:addTile("tile-rock-big-01", 0, 5)
	map:addTile("tile-rock-01", 1, 0)
	map:addTile("tile-rock-shim-01", 1, 1)
	map:addTile("tile-background-04", 1, 2)
	map:addTile("tile-background-03", 1, 3)
	map:addTile("tile-ground-03", 1, 4)
	map:addTile("tile-rock-slope-right-02", 2, 0)
	map:addTile("tile-background-04", 2, 1)
	map:addTile("tile-background-01", 2, 2)
	map:addTile("tile-rock-slope-left-01", 2, 3)
	map:addTile("tile-rock-slope-right-02", 2, 4)
	map:addTile("tile-background-big-01", 2, 5)
	map:addTile("tile-background-02", 3, 0)
	map:addTile("tile-background-02", 3, 1)
	map:addTile("tile-background-04", 3, 2)
	map:addTile("tile-ground-01", 3, 3)
	map:addTile("tile-background-02", 3, 4)
	map:addTile("tile-rock-shim-01", 4, 0)
	map:addTile("tile-background-03", 4, 1)
	map:addTile("tile-background-01", 4, 2)
	map:addTile("tile-ground-02", 4, 3)
	map:addTile("tile-rock-slope-left-02", 4, 4)
	map:addTile("tile-background-02", 4, 5)
	map:addTile("tile-background-02", 4, 6)
	map:addTile("tile-background-03", 5, 0)
	map:addTile("tile-background-04", 5, 1)
	map:addTile("tile-background-02", 5, 2)
	map:addTile("tile-ground-03", 5, 3)
	map:addTile("tile-rock-01", 5, 4)
	map:addTile("tile-rock-big-01", 5, 5)
	map:addTile("tile-background-04", 6, 0)
	map:addTile("tile-background-03", 6, 1)
	map:addTile("tile-background-03", 6, 2)
	map:addTile("tile-ground-02", 6, 3)
	map:addTile("tile-rock-01", 6, 4)
	map:addTile("liane-01", 6.6, 0)
	map:addTile("tile-background-03", 7, 0)
	map:addTile("tile-background-01", 7, 1)
	map:addTile("tile-background-02", 7, 2)
	map:addTile("tile-rock-slope-right-01", 7, 3)
	map:addTile("tile-rock-02", 7, 4)
	map:addTile("tile-rock-big-01", 7, 5)
	map:addTile("liane-01", 7.5, 0)
	map:addTile("tile-rock-03", 8, 0)
	map:addTile("tile-rock-slope-left-02", 8, 1)
	map:addTile("tile-background-02", 8, 2)
	map:addTile("tile-background-02", 8, 3)
	map:addTile("tile-rock-slope-right-01", 8, 4)
	map:addTile("tile-background-02", 9, 0)
	map:addTile("tile-ground-04", 9, 1)
	map:addTile("tile-rock-shim-01", 9, 2)
	map:addTile("tile-background-02", 9, 3)
	map:addTile("tile-background-04", 9, 4)
	map:addTile("tile-ground-02", 9, 5)
	map:addTile("tile-rock-03", 9, 6)
	map:addTile("tile-background-02", 10, 0)
	map:addTile("tile-ground-ledge-right-01", 10, 1)
	map:addTile("tile-background-04", 10, 2)
	map:addTile("tile-background-03", 10, 3)
	map:addTile("tile-background-02", 10, 4)
	map:addTile("tile-ground-03", 10, 5)
	map:addTile("tile-rock-02", 10, 6)
	map:addTile("tile-background-01", 11, 0)
	map:addTile("tile-ground-06", 11, 1)
	map:addTile("tile-background-02", 11, 2)
	map:addTile("tile-background-01", 11, 3)
	map:addTile("tile-background-02", 11, 4)
	map:addTile("tile-ground-02", 11, 5)
	map:addTile("tile-rock-03", 11, 6)
	map:addTile("tile-background-01", 12, 0)
	map:addTile("tile-ground-ledge-left-01", 12, 1)
	map:addTile("tile-background-03", 12, 2)
	map:addTile("tile-background-04", 12, 3)
	map:addTile("tile-background-02", 12, 4)
	map:addTile("tile-ground-03", 12, 5)
	map:addTile("tile-rock-03", 12, 6)
	map:addTile("tile-background-03", 13, 0)
	map:addTile("tile-ground-02", 13, 1)
	map:addTile("tile-rock-slope-left-02", 13, 2)
	map:addTile("tile-background-01", 13, 3)
	map:addTile("tile-background-04", 13, 4)
	map:addTile("tile-ground-02", 13, 5)
	map:addTile("tile-rock-03", 13, 6)
	map:addTile("tile-rock-03", 14, 0)
	map:addTile("tile-rock-big-01", 14, 1)
	map:addTile("tile-background-01", 14, 3)
	map:addTile("tile-waterfall-01", 14, 4)
	map:addTile("tile-rock-02", 14, 6)
	map:addTile("tile-rock-03", 15, 0)
	map:addTile("tile-background-04", 15, 3)
	map:addTile("tile-background-02", 15, 4)
	map:addTile("tile-packagetarget-rock-01-idle", 15, 5)
	map:addTile("tile-rock-03", 15, 6)

	map:addEmitter("item-package", 13, 4, 1, 0, "")

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "7")
	map:setSetting("packagetransfercount", "1")
	map:setSetting("playerX", "0")
	map:setSetting("playerY", "3")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "15")
	map:setSetting("theme", "rock")
	map:setSetting("waterheight", "1")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "16")
	map:setSetting("wind", "0.0")
	map:setSetting("tutorial", "true")
end
