function getName()
	return "Be fast"
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-02", 0, 0)
	map:addTile("tile-background-03", 0, 1)
	map:addTile("tile-background-02", 0, 2)
	map:addTile("tile-ground-01", 0, 4)
	map:addTile("tile-rock-02", 0, 5)
	map:addTile("tile-background-03", 1, 0)
	map:addTile("tile-background-01", 1, 1)
	map:addTile("tile-background-01", 1, 2)
	map:addTile("tile-background-window-02", 1, 3)
	map:addTile("tile-ground-03", 1, 4)
	map:addTile("tile-rock-02", 1, 5)
	map:addTile("liane-01", 1.1, 0)
	map:addTile("tile-background-01", 2, 0)
	map:addTile("tile-background-02", 2, 1)
	map:addTile("tile-background-02", 2, 2)
	map:addTile("tile-background-cave-art-01", 2, 3)
	map:addTile("tile-ground-01", 2, 4)
	map:addTile("tile-rock-03", 2, 5)
	map:addTile("tile-background-02", 3, 0)
	map:addTile("tile-background-01", 3, 1)
	map:addTile("tile-background-03", 3, 2)
	map:addTile("tile-background-02", 3, 3)
	map:addTile("tile-background-01", 3, 4)
	map:addTile("tile-background-02", 3, 5)
	map:addTile("tile-background-01", 4, 0)
	map:addTile("tile-background-02", 4, 1)
	map:addTile("tile-background-big-01", 4, 2)
	map:addTile("tile-background-02", 4, 4)
	map:addTile("tile-background-01", 4, 5)
	map:addTile("tile-rock-02", 5, 0)
	map:addTile("tile-background-03", 5, 1)
	map:addTile("liane-01", 5, 1)
	map:addTile("tile-packagetarget-rock-01-idle", 5, 4)
	map:addTile("tile-rock-03", 5, 5)
	map:addTile("liane-01", 5.5, 1)
	map:addTile("tile-rock-big-01", 6, 0)
	map:addTile("tile-background-big-01", 6, 2)
	map:addTile("tile-ground-01", 6, 4)
	map:addTile("tile-rock-02", 6, 5)
	map:addTile("tile-ground-02", 7, 4)
	map:addTile("tile-rock-02", 7, 5)

	map:addCave("tile-cave-01", 0, 3, "npc-man", 3000)

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "6")
	map:setSetting("packages", "3")
	map:setSetting("packagetransfercount", "1")
	map:setSetting("playerX", "2")
	map:setSetting("playerY", "3")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "10")
	map:setSetting("theme", "rock")
	map:setSetting("waterheight", "1.8")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "8")
	map:setSetting("wind", "0.0")
	map:setSetting("tutorial", "true")
end
