function getName()
	return "Package"
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-big-01", 0, 0)
	map:addTile("tile-background-big-01", 0, 2)
	map:addTile("tile-background-03", 0, 4)
	map:addTile("tile-packagetarget-rock-01-idle", 0, 5)
	map:addTile("tile-background-02", 1, 4)
	map:addTile("tile-background-02", 1, 5)
	map:addTile("bridge-wall-left-01", 1, 5)
	map:addTile("tile-background-cave-art-01", 2, 0)
	map:addTile("tile-background-02", 2, 1)
	map:addTile("tile-background-big-01", 2, 2)
	map:addTile("tile-background-02", 2, 4)
	map:addTile("tile-background-02", 2, 5)
	map:addTile("bridge-plank-01", 2, 5)
	map:addTile("tile-background-03", 3, 0)
	map:addTile("tile-background-02", 3, 1)
	map:addTile("tile-background-02", 3, 4)
	map:addTile("tile-background-02", 3, 5)
	map:addTile("bridge-wall-right-01", 3, 5)
	map:addTile("tile-background-02", 4, 0)
	map:addTile("tile-background-big-01", 4, 1)
	map:addTile("tile-background-02", 4, 3)
	map:addTile("tile-background-03", 4, 4)
	map:addTile("tile-ground-03", 4, 5)
	map:addTile("tile-background-02", 5, 0)
	map:addTile("tile-background-01", 5, 3)
	map:addTile("tile-background-cave-art-01", 5, 4)
	map:addTile("tile-ground-01", 5, 5)

	map:addEmitter("item-package", 0.2, 0, 1, 200)
	map:addEmitter("item-package", 4, 4, 1, 0)

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "6")
	map:setSetting("packagetransfercount", "2")
	map:setSetting("playerX", "4")
	map:setSetting("playerY", "3")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "10")
	map:setSetting("theme", "rock")
	map:setSetting("waterheight", "0.8")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "6")
	map:setSetting("wind", "0")
	map:setSetting("tutorial", "true")
	map:setSetting("introwindow", "intro1")
end
