function getName()
	return "Tree"
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-02", 0, 0)
	map:addTile("tile-ground-01", 0, 2)
	map:addTile("tile-background-03", 0, 3)
	map:addTile("tile-ground-01", 0, 5)
	map:addTile("tile-background-02", 1, 0)
	map:addTile("tile-background-window-02", 1, 1)
	map:addTile("tile-ground-03", 1, 2)
	map:addTile("tile-background-01", 1, 3)
	map:addTile("liane-01", 1, 3)
	map:addTile("tile-background-window-01", 1, 4)
	map:addTile("tile-ground-03", 1, 5)
	map:addTile("tile-background-02", 2, 0)
	map:addTile("tile-background-cave-art-01", 2, 1)
	map:addTile("tile-background-big-01", 2, 2)
	map:addTile("tile-background-02", 2, 4)
	map:addTile("tile-ground-02", 2, 5)
	map:addTile("tile-background-03", 3, 0)
	map:addTile("tile-background-02", 3, 1)
	map:addTile("tile-background-02", 3, 4)
	map:addTile("tile-ground-03", 3, 5)
	map:addTile("tile-background-02", 4, 0)
	map:addTile("tile-background-big-01", 4, 1)
	map:addTile("tile-background-02", 4, 3)
	map:addTile("tile-background-02", 4, 4)
	map:addTile("tile-ground-03", 4, 5)
	map:addTile("tile-background-02", 5, 0)
	map:addTile("tile-background-01", 5, 3)
	map:addTile("tile-background-cave-art-01", 5, 4)
	map:addTile("tile-ground-01", 5, 5)
	map:addTile("tile-background-01", 6, 0)
	map:addTile("tile-background-01", 6, 1)
	map:addTile("tile-background-03", 6, 2)
	map:addTile("tile-background-03", 6, 3)
	map:addTile("tile-background-03", 6, 4)
	map:addTile("tile-packagetarget-rock-01-idle", 6, 5)
	map:addTile("tile-background-03", 7, 0)
	map:addTile("tile-background-03", 7, 1)
	map:addTile("tile-background-02", 7, 2)
	map:addTile("tile-background-03", 7, 3)
	map:addTile("tile-background-cave-art-01", 7, 4)
	map:addTile("tile-ground-02", 7, 5)

	map:addCave("tile-cave-02", 0, 1, "npc-grandpa", 3000)
	map:addCave("tile-cave-01", 0, 4, "npc-grandpa", 3000)

	map:addEmitter("tree", 4, 3, 1, 0)
	map:addEmitter("item-stone", 5, 0, 1, 1000)

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "6")
	map:setSetting("packagetransfercount", "4")
	map:setSetting("playerX", "1.1")
	map:setSetting("playerY", "1")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "40")
	map:setSetting("theme", "rock")
	map:setSetting("waterheight", "0.8")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "8")
	map:setSetting("wind", "0")
	map:setSetting("tutorial", "true")
end
