function getName()
	return "Attack"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-rock-01", 0, 0)
	map:addTile("tile-rock-03", 0, 1)
	map:addTile("tile-rock-slope-left-02", 0, 2)
	map:addTile("tile-background-04", 0, 3)
	map:addTile("tile-background-03", 0, 4)
	map:addTile("tile-ground-01", 0, 5)
	map:addTile("tile-rock-slope-right-02", 1, 0)
	map:addTile("tile-background-04", 1, 1)
	map:addTile("tile-ground-01", 1, 2)
	map:addTile("tile-rock-shim-01", 1, 3)
	map:addTile("tile-background-04", 1, 4)
	map:addTile("tile-background-02", 1, 5)
	map:addTile("bridge-wall-left-01", 1, 5)
	map:addTile("tile-background-04", 2, 0)
	map:addTile("tile-background-04", 2, 1)
	map:addTile("tile-background-03", 2, 2)
	map:addTile("tile-background-04", 2, 3)
	map:addTile("tile-background-04", 2, 4)
	map:addTile("tile-background-02", 2, 5)
	map:addTile("bridge-wall-right-01", 2, 5)
	map:addTile("tile-rock-slope-left-02", 3, 0)
	map:addTile("tile-background-04", 3, 1)
	map:addTile("tile-background-03", 3, 2)
	map:addTile("tile-background-04", 3, 3)
	map:addTile("tile-background-04", 3, 4)
	map:addTile("tile-ground-03", 3, 5)
	map:addTile("tile-rock-slope-right-02", 4, 0)
	map:addTile("tile-background-03", 4, 1)
	map:addTile("tile-background-04", 4, 2)
	map:addTile("tile-background-04", 4, 3)
	map:addTile("tile-background-04", 4, 4)
	map:addTile("tile-ground-04", 4, 5)
	map:addTile("tile-background-04", 5, 0)
	map:addTile("tile-background-03", 5, 1)
	map:addTile("tile-background-04", 5, 2)
	map:addTile("tile-background-04", 5, 3)
	map:addTile("tile-background-03", 5, 4)
	map:addTile("tile-packagetarget-rock-01-idle", 5, 5)
	map:addTile("tile-background-04", 6, 0)
	map:addTile("tile-background-01", 6, 1)
	map:addTile("tile-rock-slope-left-01", 6, 2)
	map:addTile("tile-background-04", 6, 3)
	map:addTile("tile-background-04", 6, 4)
	map:addTile("tile-ground-01", 6, 5)
	map:addTile("tile-background-04", 7, 0)
	map:addTile("tile-background-03", 7, 1)
	map:addTile("tile-ground-01", 7, 2)
	map:addTile("tile-background-03", 7, 3)
	map:addTile("tile-background-04", 7, 4)
	map:addTile("tile-ground-02", 7, 5)
	map:addTile("tile-background-02", 8, 0)
	map:addTile("tile-background-04", 8, 1)
	map:addTile("tile-ground-02", 8, 2)
	map:addTile("tile-background-04", 8, 3)
	map:addTile("tile-background-cave-art-01", 8, 4)
	map:addTile("tile-ground-03", 8, 5)
	map:addTile("tile-rock-slope-left-02", 9, 0)
	map:addTile("tile-background-01", 9, 1)
	map:addTile("tile-ground-01", 9, 2)
	map:addTile("tile-background-04", 9, 3)
	map:addTile("tile-background-cave-art-01", 9, 4)
	map:addTile("tile-ground-01", 9, 5)

	map:addEmitter("item-stone", 2, 0, 1, 2500, "")
	map:addEmitter("tree", 3, 3, 1, 0, "")
	map:addEmitter("item-package", 5.2, 0, 1, 4000, "")
	map:addEmitter("npc-walking", 8, 4, 1, 0, "right=false")

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "6")
	map:setSetting("packagetransfercount", "1")
	map:setSetting("playerX", "0")
	map:setSetting("playerY", "4")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "20")
	map:setSetting("theme", "rock")
	map:setSetting("tutorial", "true")
	map:setSetting("waterheight", "0.5")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "10")
	map:setSetting("wind", "0")
end
