function getName()
	return "Getting narrow"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-rock-ice-02", 0, 0)
	map:addTile("tile-rock-ice-01", 0, 1)
	map:addTile("tile-background-ice-04", 0, 2)
	map:addTile("tile-ground-ice-03", 0, 4)
	map:addTile("tile-rock-ice-02", 0, 5)
	map:addTile("tile-rock-ice-01", 0, 6)
	map:addTile("tile-background-ice-07", 0, 7)
	map:addTile("tile-ground-ice-03", 0, 9)
	map:addTile("tile-rock-ice-01", 0, 10)
	map:addTile("tile-rock-ice-02", 0, 11)
	map:addTile("tile-rock-ice-01", 1, 0)
	map:addTile("tile-rock-slope-ice-right-02", 1, 1)
	map:addTile("tile-background-ice-07", 1, 2)
	map:addTile("tile-background-ice-window-02", 1, 3)
	map:addTile("tile-ground-ledge-ice-right-02", 1, 4)
	map:addTile("tile-waterfall-ice-01", 1, 5)
	map:addTile("tile-background-ice-06", 1, 7)
	map:addTile("tile-background-ice-cave-art-01", 1, 8)
	map:addTile("tile-background-ice-04", 1, 9)
	map:addTile("bridge-wall-ice-left-01", 1, 9)
	map:addTile("tile-background-ice-06", 1, 10)
	map:addTile("tile-rock-ice-01", 1, 11)
	map:addTile("tile-rock-ice-02", 2, 0)
	map:addTile("tile-background-ice-06", 2, 1)
	map:addTile("tile-background-ice-05", 2, 2)
	map:addTile("tile-background-ice-07", 2, 3)
	map:addTile("tile-ground-ice-05", 2, 4)
	map:addTile("tile-background-ice-07", 2, 5)
	map:addTile("tile-ground-ice-03", 2, 6)
	map:addTile("tile-background-ice-04", 2, 7)
	map:addTile("tile-background-ice-window-02", 2, 8)
	map:addTile("tile-background-ice-04", 2, 9)
	map:addTile("bridge-plank-ice-01", 2, 9)
	map:addTile("tile-rock-ice-big-01", 2, 10)
	map:addTile("tile-rock-ice-01", 3, 0)
	map:addTile("tile-background-ice-05", 3, 1)
	map:addTile("tile-background-ice-07", 3, 2)
	map:addTile("tile-background-ice-06", 3, 3)
	map:addTile("tile-background-ice-03", 3, 4)
	map:addTile("tile-background-ice-05", 3, 5)
	map:addTile("tile-background-ice-04", 3, 6)
	map:addTile("tile-background-ice-06", 3, 7)
	map:addTile("tile-background-ice-03", 3, 8)
	map:addTile("tile-background-ice-04", 3, 9)
	map:addTile("tile-rock-ice-big-01", 4, 0)
	map:addTile("tile-background-ice-03", 4, 2)
	map:addTile("tile-background-ice-05", 4, 3)
	map:addTile("tile-background-ice-07", 4, 4)
	map:addTile("tile-background-ice-06", 4, 5)
	map:addTile("tile-background-ice-06", 4, 6)
	map:addTile("tile-background-ice-04", 4, 7)
	map:addTile("tile-background-ice-07", 4, 8)
	map:addTile("tile-background-ice-06", 4, 9)
	map:addTile("tile-rock-ice-left-05", 4, 10)
	map:addTile("tile-rock-ice-01", 4, 11)
	map:addTile("tile-rock-slope-ice-left-02", 5, 2)
	map:addTile("tile-background-ice-06", 5, 3)
	map:addTile("tile-background-ice-03", 5, 4)
	map:addTile("tile-background-ice-07", 5, 5)
	map:addTile("tile-background-ice-04", 5, 6)
	map:addTile("tile-background-ice-03", 5, 7)
	map:addTile("tile-background-ice-06", 5, 8)
	map:addTile("tile-ground-ledge-ice-left-01", 5, 9)
	map:addTile("tile-background-ice-06", 5, 10)
	map:addTile("tile-rock-ice-02", 5, 11)
	map:addTile("tile-rock-ice-02", 6, 0)
	map:addTile("tile-rock-ice-big-01", 6, 1)
	map:addTile("tile-rock-ice-01", 6, 3)
	map:addTile("tile-rock-ice-02", 6, 4)
	map:addTile("tile-background-ice-05", 6, 5)
	map:addTile("tile-background-ice-06", 6, 6)
	map:addTile("tile-background-ice-07", 6, 7)
	map:addTile("tile-background-ice-04", 6, 8)
	map:addTile("tile-packagetarget-ice-01-idle", 6, 9)
	map:addTile("tile-rock-ice-03", 6, 10)
	map:addTile("tile-rock-ice-01", 6, 11)
	map:addTile("tile-rock-ice-01", 7, 0)
	map:addTile("tile-rock-slope-ice-right-02", 7, 3)
	map:addTile("tile-background-ice-07", 7, 4)
	map:addTile("tile-background-ice-03", 7, 5)
	map:addTile("tile-background-ice-04", 7, 6)
	map:addTile("tile-ground-ice-03", 7, 7)
	map:addTile("tile-rock-ice-big-01", 7, 8)
	map:addTile("tile-rock-ice-01", 7, 10)
	map:addTile("tile-rock-ice-03", 7, 11)
	map:addTile("tile-rock-ice-03", 8, 0)
	map:addTile("tile-rock-ice-02", 8, 1)
	map:addTile("tile-rock-ice-01", 8, 2)
	map:addTile("tile-background-ice-06", 8, 3)
	map:addTile("tile-background-ice-03", 8, 4)
	map:addTile("tile-background-ice-05", 8, 5)
	map:addTile("tile-background-ice-03", 8, 6)
	map:addTile("tile-ground-ice-04", 8, 7)
	map:addTile("tile-rock-ice-03", 8, 10)
	map:addTile("tile-rock-ice-01", 8, 11)
	map:addTile("tile-rock-ice-big-01", 9, 0)
	map:addTile("tile-rock-ice-01", 9, 2)
	map:addTile("tile-rock-slope-ice-left-02", 9, 3)
	map:addTile("tile-background-ice-05", 9, 4)
	map:addTile("tile-background-ice-06", 9, 5)
	map:addTile("tile-background-ice-06", 9, 6)
	map:addTile("tile-background-ice-03", 9, 7)
	map:addTile("tile-waterfall-ice-01", 9, 8)
	map:addTile("tile-rock-ice-01", 9, 10)
	map:addTile("tile-rock-ice-02", 9, 11)
	map:addTile("tile-rock-ice-big-01", 10, 2)
	map:addTile("tile-rock-slope-ice-left-02", 10, 4)
	map:addTile("tile-background-ice-04", 10, 5)
	map:addTile("tile-background-ice-07", 10, 6)
	map:addTile("tile-background-ice-05", 10, 7)
	map:addTile("tile-background-ice-06", 10, 8)
	map:addTile("tile-background-ice-04", 10, 9)
	map:addTile("bridge-wall-ice-left-01", 10, 9)
	map:addTile("tile-background-ice-03", 10, 10)
	map:addTile("tile-rock-ice-03", 10, 11)
	map:addTile("tile-rock-ice-01", 11, 0)
	map:addTile("tile-rock-ice-01", 11, 1)
	map:addTile("tile-rock-ice-01", 11, 4)
	map:addTile("tile-background-ice-05", 11, 5)
	map:addTile("tile-background-ice-06", 11, 6)
	map:addTile("tile-background-ice-03", 11, 7)
	map:addTile("tile-background-ice-07", 11, 8)
	map:addTile("tile-background-ice-03", 11, 9)
	map:addTile("bridge-plank-ice-01", 11, 9)
	map:addTile("tile-background-ice-05", 11, 10)
	map:addTile("tile-rock-ice-left-05", 11, 11)
	map:addTile("tile-rock-ice-left-04", 12, 0)
	map:addTile("tile-background-ice-03", 12, 1)
	map:addTile("tile-background-ice-05", 12, 2)
	map:addTile("tile-ground-ice-02", 12, 4)
	map:addTile("tile-rock-shim-ice-01", 12, 5)
	map:addTile("tile-background-ice-03", 12, 6)
	map:addTile("tile-background-ice-05", 12, 7)
	map:addTile("tile-background-ice-06", 12, 8)
	map:addTile("tile-background-ice-02", 12, 9)
	map:addTile("bridge-plank-ice-01", 12, 9)
	map:addTile("tile-background-ice-04", 12, 10)
	map:addTile("tile-background-ice-05", 12, 11)
	map:addTile("tile-background-ice-05", 13, 0)
	map:addTile("tile-background-ice-06", 13, 1)
	map:addTile("tile-background-ice-07", 13, 2)
	map:addTile("tile-background-ice-window-02", 13, 3)
	map:addTile("tile-ground-ice-01", 13, 4)
	map:addTile("tile-background-ice-07", 13, 5)
	map:addTile("tile-background-ice-06", 13, 6)
	map:addTile("tile-background-ice-04", 13, 7)
	map:addTile("tile-background-ice-cave-art-01", 13, 8)
	map:addTile("tile-background-ice-05", 13, 9)
	map:addTile("bridge-plank-ice-01", 13, 9)
	map:addTile("tile-rock-ice-right-05", 13, 10)
	map:addTile("tile-rock-ice-01", 13, 11)
	map:addTile("tile-background-ice-04", 14, 0)
	map:addTile("tile-background-ice-05", 14, 1)
	map:addTile("tile-background-ice-06", 14, 2)
	map:addTile("tile-background-ice-03", 14, 3)
	map:addTile("tile-background-ice-04", 14, 4)
	map:addTile("tile-background-ice-06", 14, 5)
	map:addTile("tile-background-ice-03", 14, 6)
	map:addTile("tile-background-ice-07", 14, 7)
	map:addTile("tile-background-ice-window-02", 14, 8)
	map:addTile("tile-background-ice-04", 14, 9)
	map:addTile("bridge-wall-ice-right-01", 14, 9)
	map:addTile("tile-rock-ice-big-01", 14, 10)
	map:addTile("tile-rock-ice-right-04", 15, 0)
	map:addTile("tile-background-ice-07", 15, 1)
	map:addTile("tile-background-ice-03", 15, 2)
	map:addTile("tile-background-ice-06", 15, 3)
	map:addTile("tile-background-ice-07", 15, 4)
	map:addTile("tile-background-ice-03", 15, 5)
	map:addTile("tile-background-ice-05", 15, 6)
	map:addTile("tile-background-ice-06", 15, 7)
	map:addTile("tile-ground-ice-03", 15, 9)

	map:addCave("tile-cave-ice-02", 0, 3, "none", 1000)
	map:addCave("tile-cave-ice-01", 0, 8, "none", 1000)
	map:addCave("tile-cave-ice-02", 12, 3, "none", 1000)
	map:addCave("tile-cave-ice-01", 15, 8, "none", 1000)

	map:addEmitter("item-stone", 1, 3, 1, 0, "")
	map:addEmitter("tree", 7, 5, 1, 0, "")
	map:addEmitter("npc-walking", 10, 8, 1, 0, "")

	map:setSetting("width", "16")
	map:setSetting("height", "12")
	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "4")
	map:addStartPosition("6", "8")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "45")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "2.7")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
