function getName()
	return "Blowing"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-07", -2, -2)
	map:addTile("tile-background-ice-04", -2, -1)
	map:addTile("tile-background-ice-03", -2, 0)
	map:addTile("tile-background-ice-04", -2, 1)
	map:addTile("tile-ground-ice-02", -2, 2)
	map:addTile("tile-rock-ice-big-01", -2, 3)
	map:addTile("tile-rock-ice-big-01", -2, 5)
	map:addTile("tile-rock-ice-02", -2, 7)
	map:addTile("tile-rock-ice-02", -2, 8)
	map:addTile("tile-rock-ice-01", -2, 9)
	map:addTile("tile-background-ice-02", -1, -2)
	map:addTile("tile-background-ice-03", -1, -1)
	map:addTile("tile-background-ice-07", -1, 0)
	map:addTile("tile-background-ice-01", -1, 1)
	map:addTile("tile-ground-ice-01", -1, 2)
	map:addTile("tile-rock-ice-02", -1, 7)
	map:addTile("tile-rock-ice-01", -1, 8)
	map:addTile("tile-rock-ice-02", -1, 9)
	map:addTile("tile-background-ice-03", 0, -2)
	map:addTile("tile-background-ice-04", 0, -1)
	map:addTile("tile-rock-ice-left-04", 0, 0)
	map:addTile("tile-rock-ice-left-05", 0, 1)
	map:addTile("tile-ground-ledge-ice-right-01", 0, 2)
	map:addTile("tile-background-ice-01", 0, 3)
	map:addTile("tile-background-ice-02", 0, 4)
	map:addTile("tile-background-ice-02", 0, 5)
	map:addTile("tile-background-ice-04", 0, 6)
	map:addTile("tile-background-ice-06", 0, 7)
	map:addTile("tile-ground-ice-03", 0, 8)
	map:addTile("tile-rock-ice-01", 0, 9)
	map:addTile("tile-background-ice-03", 1, -2)
	map:addTile("tile-background-ice-04", 1, -1)
	map:addTile("tile-background-ice-01", 1, 0)
	map:addTile("tile-background-ice-cave-art-02", 1, 1)
	map:addTile("tile-ground-ice-05", 1, 2)
	map:addTile("tile-background-ice-06", 1, 3)
	map:addTile("tile-background-ice-02", 1, 4)
	map:addTile("tile-background-ice-06", 1, 5)
	map:addTile("tile-background-ice-05", 1, 6)
	map:addTile("tile-background-ice-window-02", 1, 7)
	map:addTile("tile-ground-ice-02", 1, 8)
	map:addTile("tile-rock-ice-02", 1, 9)
	map:addTile("tile-background-ice-05", 2, -2)
	map:addTile("tile-background-ice-01", 2, -1)
	map:addTile("tile-background-ice-06", 2, 0)
	map:addTile("tile-background-ice-02", 2, 1)
	map:addTile("tile-background-ice-cave-art-02", 2, 2)
	map:addTile("tile-background-ice-07", 2, 3)
	map:addTile("tile-background-ice-03", 2, 4)
	map:addTile("tile-background-ice-04", 2, 5)
	map:addTile("tile-background-ice-02", 2, 6)
	map:addTile("tile-ground-ice-03", 2, 8)
	map:addTile("tile-rock-ice-01", 2, 9)
	map:addTile("tile-background-ice-03", 3, -2)
	map:addTile("tile-background-ice-03", 3, -1)
	map:addTile("tile-background-ice-03", 3, 0)
	map:addTile("tile-background-ice-06", 3, 1)
	map:addTile("tile-background-ice-05", 3, 2)
	map:addTile("tile-background-ice-05", 3, 3)
	map:addTile("tile-background-ice-01", 3, 4)
	map:addTile("tile-background-ice-04", 3, 5)
	map:addTile("tile-background-ice-big-01", 3, 6)
	map:addTile("tile-ground-ledge-ice-right-01", 3, 8)
	map:addTile("tile-background-ice-06", 3, 9)
	map:addTile("tile-background-ice-03", 4, -2)
	map:addTile("tile-background-ice-01", 4, -1)
	map:addTile("tile-background-ice-01", 4, 0)
	map:addTile("tile-background-ice-02", 4, 1)
	map:addTile("tile-background-ice-big-01", 4, 2)
	map:addTile("tile-background-ice-07", 4, 4)
	map:addTile("tile-ground-ice-05", 4, 5)
	map:addTile("tile-background-ice-03", 4, 8)
	map:addTile("tile-background-ice-02", 4, 9)
	map:addTile("tile-background-ice-05", 5, -2)
	map:addTile("tile-background-ice-03", 5, -1)
	map:addTile("tile-background-ice-01", 5, 0)
	map:addTile("tile-background-ice-01", 5, 1)
	map:addTile("tile-background-ice-07", 5, 4)
	map:addTile("tile-ground-ledge-ice-left-01", 5, 5)
	map:addTile("tile-background-ice-03", 5, 6)
	map:addTile("tile-background-ice-03", 5, 7)
	map:addTile("tile-background-ice-02", 5, 8)
	map:addTile("tile-background-ice-06", 5, 9)
	map:addTile("tile-background-ice-big-01", 6, -2)
	map:addTile("tile-background-ice-06", 6, 0)
	map:addTile("tile-background-ice-06", 6, 1)
	map:addTile("tile-background-ice-03", 6, 2)
	map:addTile("tile-background-ice-06", 6, 3)
	map:addTile("tile-background-ice-06", 6, 4)
	map:addTile("tile-ground-ice-01", 6, 5)
	map:addTile("tile-rock-slope-ice-left-02", 6, 6)
	map:addTile("tile-background-ice-06", 6, 7)
	map:addTile("tile-background-ice-03", 6, 8)
	map:addTile("tile-background-ice-03", 6, 9)
	map:addTile("tile-rock-ice-right-04", 7, 0)
	map:addTile("tile-background-ice-05", 7, 1)
	map:addTile("tile-background-ice-03", 7, 2)
	map:addTile("tile-background-ice-05", 7, 3)
	map:addTile("tile-background-ice-02", 7, 4)
	map:addTile("tile-ground-ice-03", 7, 5)
	map:addTile("tile-rock-ice-big-01", 7, 6)
	map:addTile("tile-rock-ice-03", 7, 8)
	map:addTile("tile-rock-ice-02", 7, 9)
	map:addTile("tile-background-ice-03", 8, -2)
	map:addTile("tile-background-ice-01", 8, -1)
	map:addTile("tile-rock-ice-03", 8, 0)
	map:addTile("tile-rock-ice-01", 8, 1)
	map:addTile("tile-rock-ice-02", 8, 2)
	map:addTile("tile-rock-ice-03", 8, 3)
	map:addTile("tile-rock-shim-ice-01", 8, 4)
	map:addTile("tile-ground-ice-04", 8, 5)
	map:addTile("tile-rock-ice-01", 8, 8)
	map:addTile("tile-rock-ice-03", 8, 9)
	map:addTile("tile-background-ice-03", 9, -2)
	map:addTile("tile-background-ice-03", 9, -1)
	map:addTile("tile-rock-ice-03", 9, 0)
	map:addTile("tile-rock-slope-ice-right-02", 9, 1)
	map:addTile("tile-background-ice-06", 9, 2)
	map:addTile("tile-rock-slope-ice-right-01", 9, 3)
	map:addTile("tile-background-ice-02", 9, 4)
	map:addTile("tile-ground-ice-03", 9, 5)
	map:addTile("tile-rock-ice-02", 9, 6)
	map:addTile("tile-rock-ice-big-01", 9, 7)
	map:addTile("tile-rock-ice-01", 9, 9)
	map:addTile("tile-background-ice-05", 10, -2)
	map:addTile("tile-background-ice-01", 10, -1)
	map:addTile("tile-rock-ice-01", 10, 0)
	map:addTile("tile-background-ice-05", 10, 1)
	map:addTile("tile-background-ice-06", 10, 2)
	map:addTile("tile-rock-slope-ice-left-02", 10, 3)
	map:addTile("tile-background-ice-04", 10, 4)
	map:addTile("tile-packagetarget-ice-01-idle", 10, 5)
	map:addTile("tile-rock-ice-02", 10, 6)
	map:addTile("tile-rock-ice-03", 10, 9)
	map:addTile("tile-background-ice-big-01", 11, -2)
	map:addTile("tile-rock-ice-02", 11, 0)
	map:addTile("tile-ground-ledge-ice-left-01", 11, 1)
	map:addTile("tile-background-ice-03", 11, 2)
	map:addTile("tile-background-ice-02", 11, 3)
	map:addTile("tile-background-ice-02", 11, 4)
	map:addTile("tile-ground-ice-01", 11, 5)
	map:addTile("tile-ground-ice-04", 11, 6)
	map:addTile("tile-rock-ice-02", 11, 7)
	map:addTile("tile-rock-ice-03", 11, 8)
	map:addTile("tile-rock-ice-01", 11, 9)
	map:addTile("tile-rock-ice-big-01", 12, 0)
	map:addTile("tile-rock-slope-ice-left-02", 12, 2)
	map:addTile("tile-background-ice-07", 12, 3)
	map:addTile("tile-rock-slope-ice-left-01", 12, 4)
	map:addTile("tile-rock-ice-03", 12, 5)
	map:addTile("tile-ground-ice-02", 12, 6)
	map:addTile("tile-rock-ice-01", 12, 7)
	map:addTile("tile-rock-ice-big-01", 12, 8)
	map:addTile("tile-background-ice-01", 13, -2)
	map:addTile("tile-background-ice-03", 13, -1)
	map:addTile("tile-rock-ice-02", 13, 2)
	map:addTile("tile-rock-ice-02", 13, 3)
	map:addTile("tile-rock-ice-02", 13, 4)
	map:addTile("tile-rock-ice-03", 13, 5)
	map:addTile("tile-rock-ice-03", 13, 6)
	map:addTile("tile-rock-ice-03", 13, 7)
	map:addTile("tile-rock-ice-03", 14, 0)
	map:addTile("tile-rock-ice-big-01", 14, 1)
	map:addTile("tile-rock-ice-03", 14, 3)
	map:addTile("tile-rock-ice-01", 14, 4)
	map:addTile("tile-rock-ice-02", 14, 5)
	map:addTile("tile-rock-ice-01", 14, 6)
	map:addTile("tile-rock-ice-big-01", 14, 7)
	map:addTile("tile-rock-ice-03", 14, 9)
	map:addTile("tile-rock-ice-02", 15, 0)
	map:addTile("tile-rock-ice-03", 15, 3)
	map:addTile("tile-rock-ice-big-01", 15, 4)
	map:addTile("tile-ground-ice-03", 15, 6)
	map:addTile("tile-rock-ice-01", 15, 9)
	map:addTile("tile-rock-ice-big-01", 16, 0)
	map:addTile("tile-rock-ice-01", 16, 2)
	map:addTile("tile-rock-ice-02", 16, 3)
	map:addTile("tile-ground-ice-01", 16, 6)
	map:addTile("tile-rock-ice-03", 16, 7)
	map:addTile("tile-rock-ice-01", 16, 8)
	map:addTile("tile-rock-ice-03", 16, 9)
	map:addTile("tile-rock-ice-02", 17, 2)
	map:addTile("tile-rock-ice-01", 17, 3)
	map:addTile("tile-rock-ice-02", 17, 4)
	map:addTile("tile-rock-ice-01", 17, 5)
	map:addTile("tile-ground-ice-04", 17, 6)
	map:addTile("tile-rock-ice-01", 17, 7)
	map:addTile("tile-rock-ice-02", 17, 8)
	map:addTile("tile-rock-ice-03", 17, 9)

	map:addCave("tile-cave-ice-01", 2, 7, "none", 1000)

	map:addEmitter("npc-blowing", 4, 3, 1, 0, "strength=10,size=4")

	map:setSetting("width", "18")
	map:setSetting("height", "10")
	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "1")
	map:addStartPosition("0", "7")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "25")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "7500")
	map:setSetting("waterheight", "1.4")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
