function getName()
	return "Second Ice 07"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-rock-ice-03", 0, 0)
	map:addTile("tile-rock-slope-ice-right-02", 0, 1)
	map:addTile("tile-background-ice-05", 0, 2)
	map:addTile("tile-background-ice-07", 0, 3)
	map:addTile("tile-background-ice-03", 0, 4)
	map:addTile("tile-background-ice-04", 0, 5)
	map:addTile("tile-background-ice-02", 0, 6)
	map:addTile("tile-background-ice-06", 0, 7)
	map:addTile("tile-background-ice-03", 0, 8)
	map:addTile("tile-background-ice-02", 0, 9)
	map:addTile("tile-ground-ice-02", 0, 10)
	map:addTile("tile-rock-ice-01", 0, 11)
	map:addTile("tile-rock-slope-ice-right-02", 1, 0)
	map:addTile("tile-background-ice-06", 1, 1)
	map:addTile("tile-background-ice-05", 1, 2)
	map:addTile("tile-background-ice-05", 1, 3)
	map:addTile("tile-background-ice-01", 1, 4)
	map:addTile("tile-background-ice-04", 1, 5)
	map:addTile("tile-background-ice-06", 1, 6)
	map:addTile("tile-background-ice-02", 1, 7)
	map:addTile("tile-background-ice-02", 1, 8)
	map:addTile("tile-background-ice-06", 1, 9)
	map:addTile("tile-ground-ice-04", 1, 10)
	map:addTile("tile-rock-ice-02", 1, 11)
	map:addTile("tile-background-ice-01", 2, 0)
	map:addTile("tile-background-ice-02", 2, 1)
	map:addTile("tile-background-ice-05", 2, 2)
	map:addTile("tile-background-ice-03", 2, 3)
	map:addTile("tile-ground-ledge-ice-left-02", 2, 4)
	map:addTile("tile-background-ice-05", 2, 5)
	map:addTile("tile-background-ice-06", 2, 6)
	map:addTile("tile-background-ice-04", 2, 7)
	map:addTile("tile-background-ice-03", 2, 8)
	map:addTile("tile-background-ice-02", 2, 9)
	map:addTile("tile-ground-ice-03", 2, 10)
	map:addTile("tile-rock-ice-02", 2, 11)
	map:addTile("tile-background-ice-01", 3, 0)
	map:addTile("tile-background-ice-01", 3, 1)
	map:addTile("tile-background-ice-05", 3, 2)
	map:addTile("tile-background-ice-05", 3, 3)
	map:addTile("tile-ground-ledge-ice-left-01", 3, 4)
	map:addTile("tile-background-ice-01", 3, 5)
	map:addTile("tile-background-ice-03", 3, 6)
	map:addTile("tile-background-ice-03", 3, 7)
	map:addTile("tile-background-ice-02", 3, 8)
	map:addTile("tile-background-ice-window-02", 3, 9)
	map:addTile("tile-ground-ice-04", 3, 10)
	map:addTile("tile-rock-ice-03", 3, 11)
	map:addTile("tile-background-ice-06", 4, 0)
	map:addTile("tile-background-ice-06", 4, 1)
	map:addTile("tile-background-ice-03", 4, 2)
	map:addTile("tile-waterfall-ice-01", 4, 3)
	map:addTile("tile-rock-slope-ice-left-02", 4, 5)
	map:addTile("tile-background-ice-06", 4, 6)
	map:addTile("tile-background-ice-06", 4, 7)
	map:addTile("tile-background-ice-03", 4, 8)
	map:addTile("tile-ground-ice-03", 4, 10)
	map:addTile("tile-rock-ice-01", 4, 11)
	map:addTile("tile-background-ice-03", 5, 0)
	map:addTile("tile-background-ice-05", 5, 1)
	map:addTile("tile-background-ice-03", 5, 2)
	map:addTile("tile-background-ice-05", 5, 3)
	map:addTile("tile-ground-ice-04", 5, 4)
	map:addTile("tile-rock-ice-big-01", 5, 5)
	map:addTile("tile-rock-slope-ice-left-02", 5, 7)
	map:addTile("tile-background-ice-06", 5, 8)
	map:addTile("tile-background-ice-01", 5, 9)
	map:addTile("tile-background-ice-02", 5, 10)
	map:addTile("tile-background-ice-06", 5, 11)
	map:addTile("tile-background-ice-04", 6, 0)
	map:addTile("tile-background-ice-01", 6, 1)
	map:addTile("tile-background-ice-big-01", 6, 2)
	map:addTile("tile-ground-ice-03", 6, 4)
	map:addTile("tile-rock-ice-02", 6, 7)
	map:addTile("tile-background-ice-06", 6, 8)
	map:addTile("tile-background-ice-06", 6, 9)
	map:addTile("tile-background-ice-01", 6, 10)
	map:addTile("tile-background-ice-01", 6, 11)
	map:addTile("tile-background-ice-01", 7, 0)
	map:addTile("tile-background-ice-01", 7, 1)
	map:addTile("tile-ground-ice-02", 7, 4)
	map:addTile("tile-rock-ice-02", 7, 5)
	map:addTile("tile-rock-ice-01", 7, 6)
	map:addTile("tile-rock-slope-ice-right-02", 7, 7)
	map:addTile("tile-background-ice-06", 7, 8)
	map:addTile("tile-background-ice-02", 7, 9)
	map:addTile("tile-background-ice-03", 7, 10)
	map:addTile("tile-background-ice-07", 7, 11)
	map:addTile("tile-rock-ice-02", 8, 0)
	map:addTile("tile-rock-ice-01", 8, 1)
	map:addTile("tile-rock-ice-02", 8, 2)
	map:addTile("tile-rock-slope-ice-left-02", 8, 3)
	map:addTile("tile-rock-slope-ice-right-01", 8, 4)
	map:addTile("tile-rock-ice-01", 8, 5)
	map:addTile("tile-rock-slope-ice-right-02", 8, 6)
	map:addTile("tile-background-ice-01", 8, 7)
	map:addTile("tile-rock-slope-ice-left-01", 8, 8)
	map:addTile("tile-rock-slope-ice-left-02", 8, 9)
	map:addTile("tile-background-ice-01", 8, 10)
	map:addTile("tile-background-ice-01", 8, 11)
	map:addTile("tile-rock-ice-big-01", 9, 0)
	map:addTile("tile-rock-ice-01", 9, 2)
	map:addTile("tile-rock-ice-03", 9, 3)
	map:addTile("tile-rock-slope-ice-left-02", 9, 4)
	map:addTile("tile-background-ice-05", 9, 5)
	map:addTile("tile-background-ice-07", 9, 6)
	map:addTile("tile-background-ice-07", 9, 7)
	map:addTile("tile-packagetarget-ice-01-idle", 9, 8)
	map:addTile("tile-rock-ice-01", 9, 9)
	map:addTile("tile-rock-ice-big-01", 9, 10)
	map:addTile("tile-rock-ice-03", 10, 2)
	map:addTile("tile-rock-ice-big-01", 10, 3)
	map:addTile("tile-rock-ice-02", 10, 5)
	map:addTile("tile-rock-ice-02", 10, 6)
	map:addTile("tile-background-ice-05", 10, 7)
	map:addTile("tile-ground-ice-04", 10, 8)
	map:addTile("tile-rock-ice-03", 10, 9)
	map:addTile("tile-rock-ice-01", 11, 0)
	map:addTile("tile-rock-ice-03", 11, 1)
	map:addTile("tile-rock-ice-02", 11, 2)
	map:addTile("tile-rock-ice-01", 11, 5)
	map:addTile("tile-background-ice-02", 11, 6)
	map:addTile("tile-background-ice-01", 11, 7)
	map:addTile("tile-ground-ice-04", 11, 8)
	map:addTile("tile-rock-ice-01", 11, 9)
	map:addTile("tile-rock-ice-03", 11, 10)
	map:addTile("tile-rock-ice-01", 11, 11)
	map:addTile("tile-rock-ice-big-01", 12, 0)
	map:addTile("tile-rock-ice-01", 12, 2)
	map:addTile("tile-ground-ice-04", 12, 3)
	map:addTile("tile-rock-ice-02", 12, 4)
	map:addTile("tile-rock-ice-02", 12, 5)
	map:addTile("tile-background-ice-03", 12, 6)
	map:addTile("tile-background-ice-06", 12, 7)
	map:addTile("tile-ground-ice-03", 12, 8)
	map:addTile("tile-rock-ice-big-01", 12, 9)
	map:addTile("tile-rock-ice-03", 12, 11)
	map:addTile("tile-rock-ice-02", 13, 2)
	map:addTile("tile-rock-ice-big-01", 13, 3)
	map:addTile("tile-rock-ice-01", 13, 5)
	map:addTile("tile-background-ice-03", 13, 6)
	map:addTile("tile-background-ice-06", 13, 7)
	map:addTile("tile-ground-ice-04", 13, 8)
	map:addTile("tile-rock-ice-01", 13, 11)
	map:addTile("tile-rock-ice-03", 14, 0)
	map:addTile("tile-rock-ice-02", 14, 1)
	map:addTile("tile-rock-ice-02", 14, 2)
	map:addTile("tile-rock-ice-01", 14, 5)
	map:addTile("tile-background-ice-03", 14, 6)
	map:addTile("tile-background-ice-07", 14, 7)
	map:addTile("tile-ground-ice-04", 14, 8)
	map:addTile("tile-rock-ice-03", 14, 9)
	map:addTile("tile-rock-ice-big-01", 14, 10)
	map:addTile("tile-rock-ice-03", 15, 0)
	map:addTile("tile-ground-ice-03", 15, 1)
	map:addTile("tile-rock-ice-03", 15, 2)
	map:addTile("tile-ground-ice-02", 15, 3)
	map:addTile("tile-rock-ice-02", 15, 4)
	map:addTile("tile-rock-ice-02", 15, 5)
	map:addTile("tile-background-ice-03", 15, 6)
	map:addTile("tile-background-ice-cave-art-01", 15, 7)
	map:addTile("tile-ground-ice-03", 15, 8)
	map:addTile("tile-rock-ice-01", 15, 9)

	map:addCave("tile-cave-ice-01", 4, 9)

	map:addEmitter("tree", 2, 2, 1, 0, "")
	map:addEmitter("npc-blowing", 11, 7, 1, 0, "right=false,size=4")

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "true")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "12")
	map:setSetting("packagetransfercount", "3")
	map:addStartPosition("6", "10")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "25")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0.0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "1.4")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "16")
	map:setSetting("wind", "0.0")
end
