function getName()
	return "Second Ice 05"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-07", -2, -2)
	map:addTile("tile-background-ice-04", -2, -1)
	map:addTile("tile-background-ice-03", -2, 0)
	map:addTile("tile-background-ice-04", -2, 1)
	map:addTile("tile-ground-ice-02", -2, 2)
	map:addTile("tile-rock-ice-big-01", -2, 3)
	map:addTile("tile-rock-ice-big-01", -2, 5)
	map:addTile("tile-rock-ice-02", -2, 7)
	map:addTile("tile-rock-ice-02", -2, 8)
	map:addTile("tile-rock-ice-01", -2, 9)
	map:addTile("tile-background-ice-02", -1, -2)
	map:addTile("tile-background-ice-03", -1, -1)
	map:addTile("tile-background-ice-07", -1, 0)
	map:addTile("tile-background-ice-01", -1, 1)
	map:addTile("tile-ground-ice-01", -1, 2)
	map:addTile("tile-rock-ice-02", -1, 7)
	map:addTile("tile-rock-ice-01", -1, 8)
	map:addTile("tile-rock-ice-02", -1, 9)
	map:addTile("tile-background-ice-03", 0, -2)
	map:addTile("tile-background-ice-04", 0, -1)
	map:addTile("tile-background-ice-07", 0, 0)
	map:addTile("tile-background-ice-03", 0, 1)
	map:addTile("tile-ground-ledge-ice-right-01", 0, 2)
	map:addTile("tile-background-ice-01", 0, 3)
	map:addTile("tile-background-ice-02", 0, 4)
	map:addTile("tile-background-ice-02", 0, 5)
	map:addTile("tile-background-ice-04", 0, 6)
	map:addTile("tile-ground-ice-02", 0, 8)
	map:addTile("tile-rock-slope-ice-right-02", 0, 9)
	map:addTile("tile-background-ice-03", 1, -2)
	map:addTile("tile-background-ice-04", 1, -1)
	map:addTile("tile-background-ice-01", 1, 0)
	map:addTile("tile-background-ice-01", 1, 1)
	map:addTile("tile-ground-ledge-ice-right-02", 1, 2)
	map:addTile("tile-background-ice-06", 1, 3)
	map:addTile("tile-background-ice-02", 1, 4)
	map:addTile("tile-background-ice-06", 1, 5)
	map:addTile("tile-background-ice-05", 1, 6)
	map:addTile("tile-background-ice-window-01", 1, 7)
	map:addTile("tile-ground-ledge-ice-right-01", 1, 8)
	map:addTile("tile-background-ice-02", 1, 9)
	map:addTile("tile-background-ice-05", 2, -2)
	map:addTile("tile-background-ice-01", 2, -1)
	map:addTile("tile-background-ice-06", 2, 0)
	map:addTile("tile-background-ice-07", 2, 1)
	map:addTile("tile-background-ice-05", 2, 2)
	map:addTile("tile-background-ice-07", 2, 3)
	map:addTile("tile-background-ice-03", 2, 4)
	map:addTile("tile-background-ice-04", 2, 5)
	map:addTile("tile-background-ice-02", 2, 6)
	map:addTile("tile-background-ice-06", 2, 7)
	map:addTile("tile-background-ice-03", 2, 8)
	map:addTile("bridge-wall-ice-left-01", 2, 8)
	map:addTile("tile-background-ice-02", 2, 9)
	map:addTile("tile-background-ice-03", 3, -2)
	map:addTile("tile-background-ice-03", 3, -1)
	map:addTile("tile-background-ice-03", 3, 0)
	map:addTile("tile-background-ice-06", 3, 1)
	map:addTile("tile-background-ice-05", 3, 2)
	map:addTile("tile-background-ice-05", 3, 3)
	map:addTile("tile-background-ice-01", 3, 4)
	map:addTile("tile-background-ice-04", 3, 5)
	map:addTile("tile-background-ice-06", 3, 6)
	map:addTile("tile-background-ice-02", 3, 7)
	map:addTile("tile-background-ice-02", 3, 8)
	map:addTile("bridge-plank-ice-01", 3, 8)
	map:addTile("tile-background-ice-06", 3, 9)
	map:addTile("tile-background-ice-03", 4, -2)
	map:addTile("tile-background-ice-01", 4, -1)
	map:addTile("tile-background-ice-01", 4, 0)
	map:addTile("tile-background-ice-02", 4, 1)
	map:addTile("tile-background-ice-05", 4, 2)
	map:addTile("tile-background-ice-03", 4, 3)
	map:addTile("tile-ground-ledge-ice-left-01", 4, 4)
	map:addTile("tile-background-ice-05", 4, 5)
	map:addTile("tile-background-ice-06", 4, 6)
	map:addTile("tile-background-ice-04", 4, 7)
	map:addTile("tile-background-ice-03", 4, 8)
	map:addTile("bridge-plank-ice-01", 4, 8)
	map:addTile("tile-background-ice-02", 4, 9)
	map:addTile("tile-background-ice-05", 5, -2)
	map:addTile("tile-background-ice-03", 5, -1)
	map:addTile("tile-background-ice-01", 5, 0)
	map:addTile("tile-background-ice-01", 5, 1)
	map:addTile("tile-background-ice-05", 5, 2)
	map:addTile("tile-background-ice-05", 5, 3)
	map:addTile("tile-ground-ice-01", 5, 4)
	map:addTile("tile-rock-slope-ice-left-02", 5, 5)
	map:addTile("tile-background-ice-03", 5, 6)
	map:addTile("tile-background-ice-03", 5, 7)
	map:addTile("tile-background-ice-02", 5, 8)
	map:addTile("bridge-wall-ice-right-01", 5, 8)
	map:addTile("tile-background-ice-06", 5, 9)
	map:addTile("tile-background-ice-big-01", 6, -2)
	map:addTile("tile-background-ice-06", 6, 0)
	map:addTile("tile-background-ice-06", 6, 1)
	map:addTile("tile-background-ice-03", 6, 2)
	map:addTile("tile-background-ice-06", 6, 3)
	map:addTile("tile-packagetarget-ice-01-idle", 6, 4)
	map:addTile("tile-rock-ice-big-01", 6, 5)
	map:addTile("tile-rock-ice-01", 6, 7)
	map:addTile("tile-rock-ice-02", 6, 8)
	map:addTile("tile-rock-ice-03", 6, 9)
	map:addTile("tile-background-ice-03", 7, 0)
	map:addTile("tile-background-ice-05", 7, 1)
	map:addTile("tile-background-ice-03", 7, 2)
	map:addTile("tile-background-ice-05", 7, 3)
	map:addTile("tile-ground-ice-02", 7, 4)
	map:addTile("tile-rock-ice-02", 7, 7)
	map:addTile("tile-rock-ice-03", 7, 8)
	map:addTile("tile-rock-ice-01", 7, 9)
	map:addTile("tile-background-ice-03", 8, -2)
	map:addTile("tile-background-ice-01", 8, -1)
	map:addTile("tile-background-ice-04", 8, 0)
	map:addTile("tile-background-ice-01", 8, 1)
	map:addTile("tile-background-ice-big-01", 8, 2)
	map:addTile("tile-ground-ice-03", 8, 4)
	map:addTile("tile-rock-slope-ice-right-02", 8, 5)
	map:addTile("tile-background-ice-01", 8, 6)
	map:addTile("tile-background-ice-02", 8, 7)
	map:addTile("tile-ground-ledge-ice-right-01", 8, 8)
	map:addTile("tile-background-ice-06", 8, 9)
	map:addTile("tile-background-ice-03", 9, -2)
	map:addTile("tile-background-ice-03", 9, -1)
	map:addTile("tile-background-ice-big-01", 9, 0)
	map:addTile("tile-ground-ledge-ice-right-01", 9, 4)
	map:addTile("tile-background-ice-05", 9, 5)
	map:addTile("tile-background-ice-04", 9, 6)
	map:addTile("tile-background-ice-04", 9, 7)
	map:addTile("tile-ground-ledge-ice-right-02", 9, 8)
	map:addTile("tile-background-ice-02", 9, 9)
	map:addTile("tile-background-ice-05", 10, -2)
	map:addTile("tile-background-ice-01", 10, -1)
	map:addTile("tile-background-ice-06", 10, 2)
	map:addTile("tile-background-ice-04", 10, 3)
	map:addTile("tile-ground-ledge-ice-right-02", 10, 4)
	map:addTile("tile-background-ice-06", 10, 5)
	map:addTile("tile-background-ice-07", 10, 6)
	map:addTile("tile-background-ice-07", 10, 7)
	map:addTile("tile-ground-ice-05", 10, 8)
	map:addTile("tile-background-ice-03", 10, 9)
	map:addTile("tile-background-ice-big-01", 11, -2)
	map:addTile("tile-background-ice-02", 11, 0)
	map:addTile("tile-background-ice-03", 11, 1)
	map:addTile("tile-background-ice-03", 11, 2)
	map:addTile("tile-background-ice-02", 11, 3)
	map:addTile("tile-background-ice-02", 11, 4)
	map:addTile("tile-background-ice-07", 11, 5)
	map:addTile("tile-background-ice-06", 11, 6)
	map:addTile("tile-geyser-ice-01-active", 11, 7)
	map:addTile("tile-rock-ice-01", 11, 9)
	map:addTile("tile-background-ice-big-01", 12, 0)
	map:addTile("tile-background-ice-07", 12, 2)
	map:addTile("tile-background-ice-07", 12, 3)
	map:addTile("tile-background-ice-06", 12, 4)
	map:addTile("tile-background-ice-05", 12, 5)
	map:addTile("tile-background-ice-06", 12, 6)
	map:addTile("tile-background-ice-03", 12, 7)
	map:addTile("tile-ground-ice-01", 12, 8)
	map:addTile("tile-rock-ice-02", 12, 9)
	map:addTile("tile-background-ice-01", 13, -2)
	map:addTile("tile-background-ice-03", 13, -1)
	map:addTile("tile-background-ice-02", 13, 2)
	map:addTile("tile-background-ice-05", 13, 3)
	map:addTile("tile-background-ice-03", 13, 4)
	map:addTile("tile-background-ice-01", 13, 5)
	map:addTile("tile-background-ice-06", 13, 6)
	map:addTile("tile-background-ice-01", 13, 7)
	map:addTile("tile-ground-ice-03", 13, 8)
	map:addTile("tile-rock-ice-01", 13, 9)

	map:addCave("tile-cave-ice-01", 0, 7)

	map:addEmitter("item-stone", 1, 1, 1, 0, "")
	map:addEmitter("tree", 4, 2, 1, 0, "")
	map:addEmitter("item-stone", 9, 3, 1, 0, "")
	map:addEmitter("item-package-ice", 9, 7, 1, 0, "")
	map:addEmitter("item-stone", 13, 7, 1, 0, "")

	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "10")
	map:setSetting("packagetransfercount", "2")
	map:setSetting("playerX", "7")
	map:setSetting("playerY", "3")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "25")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0.0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "1.4")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "14")
	map:setSetting("wind", "0.0")
end
