function getName()
	return "A long way"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-rock-ice-big-01", 0, 0)
	map:addTile("tile-rock-ice-01", 0, 2)
	map:addTile("tile-rock-ice-02", 0, 3)
	map:addTile("tile-rock-ice-03", 0, 4)
	map:addTile("tile-background-ice-04", 0, 5)
	map:addTile("tile-ground-ice-02", 0, 7)
	map:addTile("tile-rock-ice-01", 0, 8)
	map:addTile("tile-rock-ice-left-04", 0, 9)
	map:addTile("tile-rock-ice-left-05", 0, 10)
	map:addTile("tile-rock-ice-left-04", 0, 11)
	map:addTile("tile-ground-ice-02", 0, 12)
	map:addTile("tile-background-ice-07", 1, 2)
	map:addTile("tile-background-ice-window-02", 1, 3)
	map:addTile("tile-ground-ledge-ice-right-02", 1, 4)
	map:addTile("tile-background-ice-05", 1, 5)
	map:addTile("tile-background-ice-window-02", 1, 6)
	map:addTile("tile-ground-ice-03", 1, 7)
	map:addTile("tile-rock-ice-02", 1, 8)
	map:addTile("tile-background-ice-06", 1, 9)
	map:addTile("tile-background-ice-05", 1, 10)
	map:addTile("tile-background-ice-04", 1, 11)
	map:addTile("tile-packagetarget-ice-01-idle", 1, 12)
	map:addTile("tile-rock-slope-ice-right-02", 2, 0)
	map:addTile("tile-background-ice-04", 2, 1)
	map:addTile("tile-background-ice-05", 2, 2)
	map:addTile("tile-ground-ice-05", 2, 4)
	map:addTile("tile-background-ice-01", 2, 5)
	map:addTile("tile-background-ice-02", 2, 6)
	map:addTile("tile-ground-ice-04", 2, 7)
	map:addTile("tile-rock-ice-03", 2, 8)
	map:addTile("tile-background-ice-06", 2, 9)
	map:addTile("tile-background-ice-02", 2, 10)
	map:addTile("tile-background-ice-05", 2, 11)
	map:addTile("tile-ground-ice-01", 2, 12)
	map:addTile("tile-background-ice-03", 3, 0)
	map:addTile("tile-background-ice-04", 3, 1)
	map:addTile("tile-background-ice-01", 3, 2)
	map:addTile("tile-background-ice-03", 3, 3)
	map:addTile("tile-background-ice-07", 3, 4)
	map:addTile("tile-background-ice-06", 3, 5)
	map:addTile("tile-background-ice-02", 3, 6)
	map:addTile("tile-ground-ice-01", 3, 7)
	map:addTile("tile-rock-ice-01", 3, 8)
	map:addTile("tile-background-ice-02", 3, 9)
	map:addTile("tile-background-ice-06", 3, 10)
	map:addTile("tile-background-ice-07", 3, 11)
	map:addTile("tile-ground-ice-02", 3, 12)
	map:addTile("tile-background-ice-05", 4, 0)
	map:addTile("tile-background-ice-01", 4, 1)
	map:addTile("tile-background-ice-01", 4, 2)
	map:addTile("tile-background-ice-01", 4, 3)
	map:addTile("tile-background-ice-07", 4, 4)
	map:addTile("tile-background-ice-04", 4, 5)
	map:addTile("tile-background-ice-03", 4, 6)
	map:addTile("tile-ground-ice-04", 4, 7)
	map:addTile("tile-rock-ice-03", 4, 8)
	map:addTile("tile-background-ice-06", 4, 9)
	map:addTile("tile-background-ice-03", 4, 10)
	map:addTile("tile-background-ice-05", 4, 11)
	map:addTile("tile-ground-ice-01", 4, 12)
	map:addTile("tile-background-ice-03", 5, 0)
	map:addTile("tile-background-ice-03", 5, 1)
	map:addTile("tile-background-ice-03", 5, 2)
	map:addTile("tile-ground-ice-03", 5, 4)
	map:addTile("tile-background-ice-05", 5, 5)
	map:addTile("tile-background-ice-01", 5, 6)
	map:addTile("tile-background-ice-04", 5, 7)
	map:addTile("tile-ground-ice-03", 5, 8)
	map:addTile("tile-rock-slope-ice-left-02", 5, 9)
	map:addTile("tile-background-ice-02", 5, 10)
	map:addTile("tile-background-ice-05", 5, 11)
	map:addTile("tile-ground-ice-04", 5, 12)
	map:addTile("tile-background-ice-03", 6, 0)
	map:addTile("tile-background-ice-01", 6, 1)
	map:addTile("tile-background-ice-01", 6, 2)
	map:addTile("tile-background-ice-window-02", 6, 3)
	map:addTile("tile-background-ice-05", 6, 4)
	map:addTile("bridge-wall-ice-left-01", 6, 4)
	map:addTile("tile-background-ice-03", 6, 5)
	map:addTile("tile-background-ice-07", 6, 6)
	map:addTile("tile-background-ice-05", 6, 7)
	map:addTile("tile-ground-ice-04", 6, 8)
	map:addTile("tile-rock-ice-01", 6, 9)
	map:addTile("tile-background-ice-03", 6, 10)
	map:addTile("tile-background-ice-02", 6, 11)
	map:addTile("tile-background-ice-02", 6, 12)
	map:addTile("tile-background-ice-05", 7, 0)
	map:addTile("tile-background-ice-03", 7, 1)
	map:addTile("tile-background-ice-01", 7, 2)
	map:addTile("tile-background-ice-01", 7, 3)
	map:addTile("tile-background-ice-05", 7, 4)
	map:addTile("bridge-plank-ice-01", 7, 4)
	map:addTile("tile-background-ice-05", 7, 5)
	map:addTile("tile-background-ice-07", 7, 6)
	map:addTile("tile-background-ice-01", 7, 7)
	map:addTile("tile-ground-ice-03", 7, 8)
	map:addTile("tile-rock-slope-ice-right-02", 7, 9)
	map:addTile("tile-background-ice-02", 7, 10)
	map:addTile("tile-background-ice-06", 7, 11)
	map:addTile("tile-background-ice-01", 7, 12)
	map:addTile("tile-background-ice-big-01", 8, 0)
	map:addTile("tile-background-ice-06", 8, 2)
	map:addTile("tile-background-ice-06", 8, 3)
	map:addTile("tile-background-ice-03", 8, 4)
	map:addTile("bridge-wall-ice-right-01", 8, 4)
	map:addTile("tile-background-ice-06", 8, 5)
	map:addTile("tile-background-ice-06", 8, 6)
	map:addTile("tile-background-ice-window-02", 8, 7)
	map:addTile("tile-ground-ice-04", 8, 8)
	map:addTile("tile-background-ice-06", 8, 9)
	map:addTile("tile-background-ice-03", 8, 10)
	map:addTile("tile-background-ice-03", 8, 11)
	map:addTile("tile-background-ice-05", 8, 12)
	map:addTile("tile-background-ice-03", 9, 2)
	map:addTile("tile-ground-ice-03", 9, 3)
	map:addTile("tile-rock-ice-02", 9, 4)
	map:addTile("tile-background-ice-05", 9, 5)
	map:addTile("tile-background-ice-02", 9, 6)
	map:addTile("tile-ground-ice-03", 9, 8)
	map:addTile("tile-rock-slope-ice-left-02", 9, 9)
	map:addTile("tile-background-ice-06", 9, 10)
	map:addTile("tile-background-ice-01", 9, 11)
	map:addTile("tile-background-ice-03", 9, 12)
	map:addTile("tile-background-ice-03", 10, 0)
	map:addTile("tile-background-ice-01", 10, 1)
	map:addTile("tile-background-ice-04", 10, 2)
	map:addTile("tile-ground-ice-02", 10, 3)
	map:addTile("tile-rock-ice-big-01", 10, 4)
	map:addTile("tile-rock-ice-01", 10, 6)
	map:addTile("tile-rock-ice-big-01", 10, 7)
	map:addTile("tile-rock-ice-big-01", 10, 9)
	map:addTile("tile-background-ice-06", 10, 11)
	map:addTile("tile-background-ice-02", 10, 12)
	map:addTile("tile-background-ice-03", 11, 0)
	map:addTile("tile-background-ice-03", 11, 1)
	map:addTile("tile-background-ice-01", 11, 2)
	map:addTile("tile-ground-ice-02", 11, 3)
	map:addTile("tile-rock-ice-02", 11, 6)
	map:addTile("tile-background-ice-02", 11, 11)
	map:addTile("tile-background-ice-03", 11, 12)
	map:addTile("tile-background-ice-05", 12, 0)
	map:addTile("tile-background-ice-01", 12, 1)
	map:addTile("tile-background-ice-05", 12, 2)
	map:addTile("tile-background-ice-07", 12, 3)
	map:addTile("tile-background-ice-06", 12, 4)
	map:addTile("tile-background-ice-04", 12, 5)
	map:addTile("tile-background-ice-04", 12, 6)
	map:addTile("tile-background-ice-06", 12, 7)
	map:addTile("tile-background-ice-07", 12, 8)
	map:addTile("tile-rock-slope-ice-right-01", 12, 9)
	map:addTile("tile-rock-slope-ice-right-02", 12, 10)
	map:addTile("tile-background-ice-03", 12, 11)
	map:addTile("tile-background-ice-05", 12, 12)
	map:addTile("tile-rock-slope-ice-left-02", 13, 0)
	map:addTile("tile-background-ice-03", 13, 1)
	map:addTile("tile-background-ice-02", 13, 2)
	map:addTile("tile-background-ice-03", 13, 3)
	map:addTile("tile-background-ice-03", 13, 4)
	map:addTile("tile-background-ice-02", 13, 5)
	map:addTile("tile-background-ice-02", 13, 6)
	map:addTile("tile-background-ice-07", 13, 7)
	map:addTile("tile-background-ice-06", 13, 8)
	map:addTile("tile-background-ice-02", 13, 9)
	map:addTile("tile-background-ice-07", 13, 10)
	map:addTile("tile-background-ice-06", 13, 11)
	map:addTile("tile-background-ice-06", 13, 12)
	map:addTile("tile-rock-ice-big-01", 14, 0)
	map:addTile("tile-rock-ice-big-01", 14, 2)
	map:addTile("tile-background-ice-07", 14, 4)
	map:addTile("tile-background-ice-07", 14, 5)
	map:addTile("tile-ground-ice-03", 14, 6)
	map:addTile("tile-rock-slope-ice-left-02", 14, 7)
	map:addTile("tile-background-ice-06", 14, 8)
	map:addTile("tile-background-ice-03", 14, 9)
	map:addTile("tile-background-ice-06", 14, 10)
	map:addTile("tile-background-ice-03", 14, 11)
	map:addTile("tile-background-ice-07", 14, 12)
	map:addTile("tile-background-ice-02", 15, 4)
	map:addTile("tile-background-ice-05", 15, 5)
	map:addTile("tile-ground-ice-02", 15, 6)
	map:addTile("tile-rock-ice-03", 15, 7)
	map:addTile("tile-rock-ice-01", 15, 8)
	map:addTile("tile-rock-ice-02", 15, 9)
	map:addTile("tile-rock-ice-03", 15, 10)
	map:addTile("tile-rock-ice-02", 15, 11)
	map:addTile("tile-rock-ice-03", 15, 12)

	map:addCave("tile-cave-ice-01", 0, 6, "none", 2000)
	map:addCave("tile-cave-ice-01", 2, 3, "none", 2500)
	map:addCave("tile-cave-ice-01", 5, 3, "none", 1500)
	map:addCave("tile-cave-ice-02", 9, 7, "none", 2000)

	map:addEmitter("tree", 10, 1, 1, 0, "")
	map:addEmitter("npc-blowing", 14, 5, 1, 0, "right=false")

	map:setSetting("width", "16")
	map:setSetting("height", "13")
	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "4")
	map:addStartPosition("2", "10")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "75")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "1.49012e-08")
	map:setSetting("waterfallingdelay", "7500")
	map:setSetting("waterheight", "0.8")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
