function getName()
	return "Free the packages"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-07", -2, -2)
	map:addTile("tile-background-ice-04", -2, -1)
	map:addTile("tile-background-ice-03", -2, 0)
	map:addTile("tile-background-ice-04", -2, 1)
	map:addTile("tile-ground-ice-02", -2, 2)
	map:addTile("tile-rock-ice-big-01", -2, 3)
	map:addTile("tile-rock-ice-big-01", -2, 5)
	map:addTile("tile-rock-ice-02", -2, 7)
	map:addTile("tile-rock-ice-02", -2, 8)
	map:addTile("tile-rock-ice-01", -2, 9)
	map:addTile("tile-background-ice-02", -1, -2)
	map:addTile("tile-background-ice-03", -1, -1)
	map:addTile("tile-background-ice-07", -1, 0)
	map:addTile("tile-background-ice-01", -1, 1)
	map:addTile("tile-ground-ice-01", -1, 2)
	map:addTile("tile-rock-ice-02", -1, 7)
	map:addTile("tile-rock-ice-01", -1, 8)
	map:addTile("tile-rock-ice-02", -1, 9)
	map:addTile("tile-background-ice-03", 0, -2)
	map:addTile("tile-background-ice-04", 0, -1)
	map:addTile("tile-rock-ice-01", 0, 0)
	map:addTile("tile-rock-slope-ice-right-02", 0, 1)
	map:addTile("tile-background-ice-06", 0, 2)
	map:addTile("tile-background-ice-01", 0, 3)
	map:addTile("tile-background-ice-06", 0, 4)
	map:addTile("tile-background-ice-02", 0, 5)
	map:addTile("tile-background-ice-04", 0, 6)
	map:addTile("tile-background-ice-06", 0, 7)
	map:addTile("tile-background-ice-02", 0, 8)
	map:addTile("tile-background-ice-02", 0, 9)
	map:addTile("tile-background-ice-03", 0, 10)
	map:addTile("tile-background-ice-big-01", 0, 11)
	map:addTile("tile-background-ice-07", 0, 13)
	map:addTile("tile-background-ice-03", 1, -2)
	map:addTile("tile-background-ice-04", 1, -1)
	map:addTile("tile-rock-slope-ice-right-02", 1, 0)
	map:addTile("tile-background-ice-01", 1, 1)
	map:addTile("tile-background-ice-06", 1, 2)
	map:addTile("tile-background-ice-06", 1, 3)
	map:addTile("tile-background-ice-06", 1, 4)
	map:addTile("tile-background-ice-06", 1, 5)
	map:addTile("tile-background-ice-05", 1, 6)
	map:addTile("tile-background-ice-02", 1, 7)
	map:addTile("tile-background-ice-06", 1, 8)
	map:addTile("tile-background-ice-02", 1, 9)
	map:addTile("tile-background-ice-02", 1, 10)
	map:addTile("tile-background-ice-01", 1, 13)
	map:addTile("tile-background-ice-05", 2, -2)
	map:addTile("tile-background-ice-01", 2, -1)
	map:addTile("tile-background-ice-06", 2, 0)
	map:addTile("tile-background-ice-07", 2, 1)
	map:addTile("tile-background-ice-05", 2, 2)
	map:addTile("tile-background-ice-07", 2, 3)
	map:addTile("tile-ground-ledge-ice-left-02", 2, 4)
	map:addTile("tile-background-ice-04", 2, 5)
	map:addTile("tile-background-ice-02", 2, 6)
	map:addTile("tile-background-ice-06", 2, 7)
	map:addTile("tile-background-ice-03", 2, 8)
	map:addTile("tile-background-ice-02", 2, 9)
	map:addTile("tile-background-ice-06", 2, 10)
	map:addTile("tile-background-ice-06", 2, 11)
	map:addTile("tile-background-ice-05", 2, 12)
	map:addTile("tile-background-ice-04", 2, 13)
	map:addTile("tile-background-ice-03", 3, -2)
	map:addTile("tile-background-ice-03", 3, -1)
	map:addTile("tile-background-ice-03", 3, 0)
	map:addTile("tile-background-ice-06", 3, 1)
	map:addTile("tile-background-ice-05", 3, 2)
	map:addTile("tile-background-ice-05", 3, 3)
	map:addTile("tile-ground-ledge-ice-left-01", 3, 4)
	map:addTile("tile-background-ice-04", 3, 5)
	map:addTile("tile-background-ice-06", 3, 6)
	map:addTile("tile-background-ice-02", 3, 7)
	map:addTile("tile-background-ice-02", 3, 8)
	map:addTile("tile-ground-ice-05", 3, 9)
	map:addTile("tile-background-ice-07", 3, 10)
	map:addTile("tile-background-ice-04", 3, 11)
	map:addTile("tile-background-ice-03", 3, 12)
	map:addTile("tile-background-ice-03", 3, 13)
	map:addTile("tile-background-ice-03", 4, -2)
	map:addTile("tile-background-ice-01", 4, -1)
	map:addTile("tile-background-ice-01", 4, 0)
	map:addTile("tile-background-ice-02", 4, 1)
	map:addTile("tile-background-ice-05", 4, 2)
	map:addTile("tile-ground-ice-03", 4, 4)
	map:addTile("tile-rock-slope-ice-left-02", 4, 5)
	map:addTile("tile-background-ice-06", 4, 6)
	map:addTile("tile-background-ice-04", 4, 7)
	map:addTile("tile-background-ice-03", 4, 8)
	map:addTile("tile-ground-ledge-ice-left-02", 4, 9)
	map:addTile("tile-background-ice-03", 4, 10)
	map:addTile("tile-background-ice-04", 4, 11)
	map:addTile("tile-background-ice-02", 4, 12)
	map:addTile("tile-background-ice-02", 4, 13)
	map:addTile("tile-background-ice-05", 5, -2)
	map:addTile("tile-background-ice-03", 5, -1)
	map:addTile("tile-background-ice-01", 5, 0)
	map:addTile("tile-background-ice-01", 5, 1)
	map:addTile("tile-background-ice-05", 5, 2)
	map:addTile("tile-background-ice-05", 5, 3)
	map:addTile("tile-packagetarget-ice-01-idle", 5, 4)
	map:addTile("tile-rock-ice-big-01", 5, 5)
	map:addTile("tile-rock-ice-03", 5, 7)
	map:addTile("tile-rock-ice-big-01", 5, 8)
	map:addTile("tile-rock-ice-02", 5, 10)
	map:addTile("tile-rock-ice-03", 5, 11)
	map:addTile("tile-rock-ice-01", 5, 12)
	map:addTile("tile-rock-ice-03", 5, 13)
	map:addTile("tile-background-ice-big-01", 6, -2)
	map:addTile("tile-background-ice-06", 6, 0)
	map:addTile("tile-background-ice-06", 6, 1)
	map:addTile("tile-background-ice-03", 6, 2)
	map:addTile("tile-background-ice-06", 6, 3)
	map:addTile("tile-ground-ice-01", 6, 4)
	map:addTile("tile-rock-ice-02", 6, 7)
	map:addTile("tile-rock-ice-01", 6, 10)
	map:addTile("tile-rock-ice-02", 6, 11)
	map:addTile("tile-rock-ice-03", 6, 12)
	map:addTile("tile-rock-ice-01", 6, 13)
	map:addTile("tile-background-ice-03", 7, 0)
	map:addTile("tile-background-ice-05", 7, 1)
	map:addTile("tile-background-ice-03", 7, 2)
	map:addTile("tile-background-ice-05", 7, 3)
	map:addTile("tile-ground-ice-04", 7, 4)
	map:addTile("tile-rock-slope-ice-right-02", 7, 5)
	map:addTile("tile-background-ice-06", 7, 6)
	map:addTile("tile-background-ice-02", 7, 7)
	map:addTile("tile-rock-slope-ice-right-01", 7, 8)
	map:addTile("tile-background-ice-01", 7, 9)
	map:addTile("tile-background-ice-03", 7, 10)
	map:addTile("tile-background-ice-02", 7, 11)
	map:addTile("tile-background-ice-02", 7, 12)
	map:addTile("tile-background-ice-04", 7, 13)
	map:addTile("tile-background-ice-03", 8, -2)
	map:addTile("tile-background-ice-01", 8, -1)
	map:addTile("tile-background-ice-04", 8, 0)
	map:addTile("tile-background-ice-01", 8, 1)
	map:addTile("tile-background-ice-big-01", 8, 2)
	map:addTile("tile-background-ice-06", 8, 4)
	map:addTile("tile-background-ice-06", 8, 5)
	map:addTile("tile-background-ice-01", 8, 6)
	map:addTile("tile-background-ice-02", 8, 7)
	map:addTile("tile-ground-ledge-ice-left-02", 8, 8)
	map:addTile("tile-background-ice-06", 8, 9)
	map:addTile("tile-background-ice-02", 8, 10)
	map:addTile("tile-background-ice-03", 8, 11)
	map:addTile("tile-background-ice-05", 8, 12)
	map:addTile("tile-background-ice-02", 8, 13)
	map:addTile("tile-background-ice-03", 9, -2)
	map:addTile("tile-background-ice-03", 9, -1)
	map:addTile("tile-rock-slope-ice-left-02", 9, 0)
	map:addTile("tile-background-ice-06", 9, 1)
	map:addTile("tile-background-ice-02", 9, 4)
	map:addTile("tile-background-ice-05", 9, 5)
	map:addTile("tile-background-ice-04", 9, 6)
	map:addTile("tile-background-ice-04", 9, 7)
	map:addTile("tile-ground-ledge-ice-left-01", 9, 8)
	map:addTile("tile-background-ice-06", 9, 9)
	map:addTile("tile-background-ice-06", 9, 10)
	map:addTile("tile-background-ice-02", 9, 11)
	map:addTile("tile-background-ice-05", 9, 12)
	map:addTile("tile-background-ice-07", 9, 13)
	map:addTile("tile-background-ice-05", 10, -2)
	map:addTile("tile-background-ice-01", 10, -1)
	map:addTile("tile-rock-ice-02", 10, 0)
	map:addTile("tile-rock-ice-01", 10, 1)
	map:addTile("tile-rock-slope-ice-left-02", 10, 2)
	map:addTile("tile-background-ice-04", 10, 3)
	map:addTile("tile-background-ice-04", 10, 4)
	map:addTile("tile-background-ice-06", 10, 5)
	map:addTile("tile-background-ice-07", 10, 6)
	map:addTile("tile-background-ice-07", 10, 7)
	map:addTile("tile-ground-ice-03", 10, 8)
	map:addTile("tile-rock-ice-02", 10, 9)
	map:addTile("tile-rock-ice-01", 10, 10)
	map:addTile("tile-rock-ice-03", 10, 11)
	map:addTile("tile-rock-ice-02", 10, 12)
	map:addTile("tile-rock-ice-03", 10, 13)
	map:addTile("tile-background-ice-big-01", 11, -2)
	map:addTile("tile-rock-ice-03", 11, 0)
	map:addTile("tile-rock-ice-02", 11, 1)
	map:addTile("tile-rock-ice-big-01", 11, 2)
	map:addTile("tile-background-ice-02", 11, 4)
	map:addTile("tile-background-ice-07", 11, 5)
	map:addTile("tile-background-ice-06", 11, 6)
	map:addTile("tile-background-ice-02", 11, 7)
	map:addTile("tile-background-ice-07", 11, 8)
	map:addTile("bridge-wall-ice-left-01", 11, 8)
	map:addTile("tile-background-ice-06", 11, 9)
	map:addTile("tile-background-ice-04", 11, 10)
	map:addTile("tile-background-ice-05", 11, 11)
	map:addTile("tile-background-ice-big-01", 11, 12)
	map:addTile("tile-rock-ice-02", 12, 0)
	map:addTile("tile-rock-ice-03", 12, 1)
	map:addTile("tile-background-ice-06", 12, 4)
	map:addTile("tile-background-ice-05", 12, 5)
	map:addTile("tile-background-ice-06", 12, 6)
	map:addTile("tile-background-ice-03", 12, 7)
	map:addTile("tile-background-ice-06", 12, 8)
	map:addTile("bridge-plank-ice-01", 12, 8)
	map:addTile("tile-background-ice-03", 12, 9)
	map:addTile("tile-background-ice-06", 12, 10)
	map:addTile("tile-background-ice-03", 12, 11)
	map:addTile("tile-background-ice-01", 13, -2)
	map:addTile("tile-background-ice-03", 13, -1)
	map:addTile("tile-rock-ice-03", 13, 0)
	map:addTile("tile-rock-ice-02", 13, 1)
	map:addTile("tile-rock-ice-02", 13, 2)
	map:addTile("tile-rock-ice-01", 13, 3)
	map:addTile("tile-background-ice-03", 13, 4)
	map:addTile("tile-background-ice-01", 13, 5)
	map:addTile("tile-background-ice-06", 13, 6)
	map:addTile("tile-background-ice-01", 13, 7)
	map:addTile("tile-background-ice-01", 13, 8)
	map:addTile("bridge-wall-ice-right-01", 13, 8)
	map:addTile("tile-background-ice-03", 13, 9)
	map:addTile("tile-background-ice-03", 13, 10)
	map:addTile("tile-background-ice-02", 13, 11)
	map:addTile("tile-background-ice-07", 13, 12)
	map:addTile("tile-background-ice-04", 13, 13)
	map:addTile("tile-rock-ice-big-01", 14, 0)
	map:addTile("tile-rock-ice-01", 14, 2)
	map:addTile("tile-rock-ice-03", 14, 3)
	map:addTile("tile-rock-slope-ice-left-02", 14, 4)
	map:addTile("tile-background-ice-04", 14, 5)
	map:addTile("tile-background-ice-07", 14, 6)
	map:addTile("tile-background-ice-02", 14, 7)
	map:addTile("tile-ground-ice-02", 14, 8)
	map:addTile("tile-rock-ice-01", 14, 9)
	map:addTile("tile-rock-ice-02", 14, 10)
	map:addTile("tile-rock-ice-02", 14, 11)
	map:addTile("tile-rock-ice-03", 14, 12)
	map:addTile("tile-rock-ice-02", 14, 13)
	map:addTile("tile-rock-ice-02", 15, 2)
	map:addTile("tile-rock-ice-big-01", 15, 3)
	map:addTile("tile-background-ice-03", 15, 5)
	map:addTile("tile-background-ice-big-01", 15, 6)
	map:addTile("tile-background-ice-02", 15, 8)
	map:addTile("tile-background-ice-06", 15, 9)
	map:addTile("tile-background-ice-06", 15, 10)
	map:addTile("tile-background-ice-06", 15, 11)
	map:addTile("tile-background-ice-05", 15, 12)
	map:addTile("tile-background-ice-04", 15, 13)
	map:addTile("tile-rock-ice-03", 16, 0)
	map:addTile("tile-rock-ice-01", 16, 1)
	map:addTile("tile-rock-ice-03", 16, 2)
	map:addTile("tile-background-ice-03", 16, 5)
	map:addTile("tile-background-ice-02", 16, 8)
	map:addTile("tile-background-ice-06", 16, 9)
	map:addTile("tile-background-ice-01", 16, 10)
	map:addTile("tile-background-ice-02", 16, 11)
	map:addTile("tile-background-ice-05", 16, 12)
	map:addTile("tile-background-ice-05", 16, 13)
	map:addTile("tile-rock-ice-01", 17, 0)
	map:addTile("tile-rock-ice-03", 17, 1)
	map:addTile("tile-rock-ice-01", 17, 2)
	map:addTile("tile-rock-ice-03", 17, 3)
	map:addTile("tile-ground-ledge-ice-right-01", 17, 4)
	map:addTile("tile-background-ice-04", 17, 5)
	map:addTile("tile-background-ice-03", 17, 6)
	map:addTile("tile-background-ice-06", 17, 7)
	map:addTile("tile-background-ice-03", 17, 8)
	map:addTile("tile-background-ice-05", 17, 9)
	map:addTile("tile-background-ice-02", 17, 10)
	map:addTile("tile-background-ice-03", 17, 11)
	map:addTile("tile-background-ice-03", 17, 12)
	map:addTile("tile-background-ice-03", 17, 13)

	map:addCave("tile-cave-ice-01", 4, 3, "none", 100)

	map:addEmitter("tree", 2, 2, 1, 0, "")
	map:addEmitter("item-stone", 3, 8, 1, 0, "")
	map:addEmitter("item-package-ice", 8, 11, 1, 0, "")
	map:addEmitter("item-stone", 9, 7, 1, 0, "")
	map:addEmitter("item-package-ice", 9, 11, 1, 0, "")
	map:addEmitter("item-stone", 10, 7, 1, 0, "")

	map:setSetting("fishnpc", "true")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("height", "14")
	map:setSetting("packagetransfercount", "1")
	map:setSetting("playerX", "8")
	map:setSetting("playerY", "7")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "28")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0.4")
	map:setSetting("waterfallingdelay", "7500")
	map:setSetting("waterheight", "1.4")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("width", "18")
	map:setSetting("wind", "0.0")
end
