function getName()
	return ""
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-07", 0, -17)
	map:addTile("tile-background-ice-05", 0, -16)
	map:addTile("tile-background-ice-02", 0, -15)
	map:addTile("tile-background-ice-04", 0, -14)
	map:addTile("tile-background-ice-04", 0, -13)
	map:addTile("tile-background-ice-big-01", 0, -12)
	map:addTile("tile-background-ice-big-01", 0, -10)
	map:addTile("tile-background-ice-big-01", 0, -8)
	map:addTile("tile-background-ice-01", 0, -6)
	map:addTile("tile-background-ice-big-01", 0, -5)
	map:addTile("tile-background-ice-cave-art-01", 0, -3)
	map:addTile("tile-background-ice-07", 0, -2)
	map:addTile("tile-background-ice-big-01", 0, -1)
	map:addTile("tile-background-ice-01", 0, 1)
	map:addTile("tile-background-ice-08", 0, 2)
	map:addTile("tile-background-ice-cave-art-01", 0, 3)
	map:addTile("tile-background-ice-02", 0, 4)
	map:addTile("tile-background-ice-03", 0, 5)
	map:addTile("tile-ground-ice-06", 0, 6)
	map:addTile("tile-background-ice-05", 1, -17)
	map:addTile("tile-background-ice-07", 1, -16)
	map:addTile("tile-background-ice-02", 1, -15)
	map:addTile("tile-background-ice-big-01", 1, -14)
	map:addTile("tile-background-ice-06", 1, -6)
	map:addTile("tile-background-ice-01", 1, -3)
	map:addTile("tile-background-ice-01", 1, -2)
	map:addTile("tile-background-ice-05", 1, 1)
	map:addTile("tile-background-ice-06", 1, 2)
	map:addTile("tile-background-ice-cave-art-01", 1, 3)
	map:addTile("tile-background-ice-08", 1, 4)
	map:addTile("tile-background-ice-01", 1, 5)
	map:addTile("tile-ground-ice-06", 1, 6)
	map:addTile("tile-background-ice-cave-art-01", 2, -17)
	map:addTile("tile-background-ice-cave-art-02", 2, -16)
	map:addTile("tile-background-ice-cave-art-02", 2, -15)
	map:addTile("tile-background-ice-06", 2, -12)
	map:addTile("tile-background-ice-07", 2, -11)
	map:addTile("tile-background-ice-06", 2, -10)
	map:addTile("tile-background-ice-cave-art-02", 2, -9)
	map:addTile("tile-background-ice-06", 2, -8)
	map:addTile("tile-background-ice-07", 2, -7)
	map:addTile("tile-background-ice-03", 2, -6)
	map:addTile("tile-background-ice-03", 2, -5)
	map:addTile("tile-background-ice-02", 2, -4)
	map:addTile("tile-background-ice-big-01", 2, -3)
	map:addTile("tile-background-ice-04", 2, -1)
	map:addTile("tile-background-ice-cave-art-02", 2, 0)
	map:addTile("tile-background-ice-08", 2, 1)
	map:addTile("tile-background-ice-08", 2, 2)
	map:addTile("tile-background-ice-08", 2, 3)
	map:addTile("tile-background-ice-06", 2, 4)
	map:addTile("tile-background-ice-cave-art-02", 2, 5)
	map:addTile("tile-ground-ice-06", 2, 6)
	map:addTile("tile-background-ice-04", 3, -17)
	map:addTile("tile-background-ice-cave-art-01", 3, -16)
	map:addTile("tile-background-ice-02", 3, -15)
	map:addTile("tile-background-ice-03", 3, -14)
	map:addTile("tile-background-ice-07", 3, -13)
	map:addTile("tile-background-ice-cave-art-01", 3, -12)
	map:addTile("tile-background-ice-08", 3, -11)
	map:addTile("tile-background-ice-05", 3, -10)
	map:addTile("tile-background-ice-big-01", 3, -9)
	map:addTile("tile-background-ice-04", 3, -7)
	map:addTile("tile-background-ice-cave-art-02", 3, -6)
	map:addTile("tile-background-ice-05", 3, -5)
	map:addTile("tile-background-ice-03", 3, -4)
	map:addTile("tile-background-ice-cave-art-01", 3, -1)
	map:addTile("tile-background-ice-cave-art-02", 3, 0)
	map:addTile("tile-background-ice-cave-art-02", 3, 1)
	map:addTile("tile-background-ice-07", 3, 2)
	map:addTile("tile-background-ice-03", 3, 3)
	map:addTile("tile-background-ice-08", 3, 4)
	map:addTile("tile-background-ice-08", 3, 5)
	map:addTile("tile-ground-ice-06", 3, 6)
	map:addTile("tile-background-ice-cave-art-01", 4, -17)
	map:addTile("tile-background-ice-big-01", 4, -16)
	map:addTile("tile-background-ice-08", 4, -14)
	map:addTile("tile-background-ice-02", 4, -13)
	map:addTile("tile-background-ice-big-01", 4, -12)
	map:addTile("tile-background-ice-06", 4, -10)
	map:addTile("tile-background-ice-03", 4, -7)
	map:addTile("tile-background-ice-08", 4, -6)
	map:addTile("tile-background-ice-02", 4, -5)
	map:addTile("tile-background-ice-08", 4, -4)
	map:addTile("tile-background-ice-02", 4, -3)
	map:addTile("tile-background-ice-05", 4, -2)
	map:addTile("tile-background-ice-03", 4, -1)
	map:addTile("tile-background-ice-03", 4, 0)
	map:addTile("tile-background-ice-08", 4, 1)
	map:addTile("tile-background-ice-02", 4, 2)
	map:addTile("tile-background-ice-03", 4, 3)
	map:addTile("tile-background-ice-03", 4, 4)
	map:addTile("tile-background-ice-04", 4, 5)
	map:addTile("tile-ground-ice-06", 4, 6)
	map:addTile("tile-background-ice-07", 5, -17)
	map:addTile("tile-background-ice-03", 5, -14)
	map:addTile("tile-background-ice-cave-art-02", 5, -13)
	map:addTile("tile-background-ice-02", 5, -10)
	map:addTile("tile-background-ice-08", 5, -9)
	map:addTile("tile-background-ice-02", 5, -8)
	map:addTile("tile-background-ice-04", 5, -7)
	map:addTile("tile-background-ice-07", 5, -6)
	map:addTile("tile-background-ice-cave-art-01", 5, -5)
	map:addTile("tile-background-ice-04", 5, -4)
	map:addTile("tile-background-ice-07", 5, -3)
	map:addTile("tile-background-ice-04", 5, -2)
	map:addTile("tile-background-ice-01", 5, -1)
	map:addTile("tile-background-ice-06", 5, 0)
	map:addTile("tile-background-ice-06", 5, 1)
	map:addTile("tile-background-ice-01", 5, 2)
	map:addTile("tile-background-ice-04", 5, 3)
	map:addTile("tile-background-ice-06", 5, 4)
	map:addTile("tile-background-ice-06", 5, 5)
	map:addTile("tile-packagetarget-ice-01-idle", 5, 6)

	map:addEmitter("item-package-ice", 4, 5, 1, 0, "")

	map:setSetting("width", "6")
	map:setSetting("height", "7")
	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "3")
	map:addStartPosition("0", "0")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "30")
	map:setSetting("sideborderfail", "false")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "1")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
