function getName()
	return "Map 05"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-cave-art-02", 0, 0)
	map:addTile("tile-background-ice-07", 0, 1)
	map:addTile("tile-background-ice-06", 0, 2)
	map:addTile("tile-background-ice-05", 0, 3)
	map:addTile("tile-background-ice-04", 0, 4)
	map:addTile("tile-ground-ice-big-01", 0, 5)
	map:addTile("tile-rock-ice-02", 0, 7)
	map:addTile("tile-rock-ice-01", 0, 8)
	map:addTile("tile-rock-ice-02", 0, 9)
	map:addTile("tile-rock-ice-big-01", 0, 10)
	map:addTile("tile-background-ice-03", 1, 0)
	map:addTile("tile-background-ice-cave-art-02", 1, 1)
	map:addTile("tile-background-ice-big-01", 1, 2)
	map:addTile("tile-background-ice-08", 1, 4)
	map:addTile("tile-rock-ice-01", 1, 7)
	map:addTile("tile-rock-ice-big-01", 1, 8)
	map:addTile("tile-background-ice-08", 2, 0)
	map:addTile("tile-background-ice-04", 2, 1)
	map:addTile("tile-background-ice-big-01", 2, 4)
	map:addTile("tile-background-ice-cave-art-02", 2, 6)
	map:addTile("tile-rock-slope-ice-right-01", 2, 7)
	map:addTile("tile-rock-ice-01", 2, 10)
	map:addTile("tile-rock-ice-02", 2, 11)
	map:addTile("tile-background-ice-04", 3, 0)
	map:addTile("tile-background-ice-big-01", 3, 1)
	map:addTile("tile-ground-ledge-ice-left-01", 3, 3)
	map:addTile("tile-background-ice-07", 3, 6)
	map:addTile("tile-background-ice-01", 3, 7)
	map:addTile("tile-background-ice-02", 3, 8)
	map:addTile("tile-packagetarget-ice-01-idle", 3, 9)
	map:addTile("tile-rock-ice-02", 3, 10)
	map:addTile("tile-rock-ice-01", 3, 11)
	map:addTile("tile-background-ice-03", 4, 0)
	map:addTile("tile-ground-ice-01", 4, 3)
	map:addTile("tile-rock-ice-right-05", 4, 4)
	map:addTile("tile-rock-ice-right-04", 4, 5)
	map:addTile("tile-background-ice-04", 4, 6)
	map:addTile("tile-background-ice-05", 4, 7)
	map:addTile("tile-rock-slope-ice-left-01", 4, 8)
	map:addTile("tile-rock-ice-02", 4, 9)
	map:addTile("tile-rock-ice-03", 4, 10)
	map:addTile("tile-rock-ice-02", 4, 11)
	map:addTile("tile-background-ice-07", 5, 0)
	map:addTile("tile-background-ice-08", 5, 1)
	map:addTile("tile-geyser-ice-01-active", 5, 2)
	map:addTile("tile-rock-ice-02", 5, 4)
	map:addTile("tile-rock-ice-02", 5, 5)
	map:addTile("tile-background-ice-04", 5, 6)
	map:addTile("tile-background-ice-04", 5, 7)
	map:addTile("tile-ground-ice-06", 5, 8)
	map:addTile("tile-rock-ice-03", 5, 9)
	map:addTile("tile-rock-ice-02", 5, 10)
	map:addTile("tile-rock-ice-01", 5, 11)
	map:addTile("tile-background-ice-big-01", 6, 0)
	map:addTile("tile-background-ice-06", 6, 2)
	map:addTile("tile-background-ice-04", 6, 3)
	map:addTile("tile-background-ice-05", 6, 4)
	map:addTile("tile-ground-ledge-ice-right-02", 6, 5)
	map:addTile("tile-background-ice-05", 6, 6)
	map:addTile("tile-background-ice-01", 6, 7)
	map:addTile("tile-ground-ice-04", 6, 8)
	map:addTile("tile-rock-ice-03", 6, 9)
	map:addTile("tile-rock-ice-02", 6, 10)
	map:addTile("tile-rock-ice-02", 6, 11)
	map:addTile("tile-background-ice-04", 7, 2)
	map:addTile("tile-background-ice-01", 7, 3)
	map:addTile("tile-background-ice-01", 7, 4)
	map:addTile("tile-background-ice-03", 7, 5)
	map:addTile("bridge-plank-ice-01", 7, 5)
	map:addTile("tile-background-ice-05", 7, 6)
	map:addTile("tile-background-ice-03", 7, 7)
	map:addTile("tile-ground-ice-06", 7, 8)
	map:addTile("tile-rock-ice-03", 7, 9)
	map:addTile("tile-rock-ice-big-01", 7, 10)
	map:addTile("tile-background-ice-07", 8, 0)
	map:addTile("tile-ground-ice-02", 8, 2)
	map:addTile("tile-rock-slope-ice-left-02", 8, 3)
	map:addTile("tile-background-ice-07", 8, 4)
	map:addTile("tile-background-ice-02", 8, 5)
	map:addTile("bridge-plank-ice-01", 8, 5)
	map:addTile("tile-background-ice-04", 8, 6)
	map:addTile("tile-ground-ice-03", 8, 8)
	map:addTile("tile-rock-ice-03", 8, 9)
	map:addTile("tile-background-ice-08", 9, 0)
	map:addTile("tile-background-ice-window-02", 9, 1)
	map:addTile("tile-ground-ice-01", 9, 2)
	map:addTile("tile-rock-ice-big-01", 9, 3)
	map:addTile("tile-rock-shim-ice-01", 9, 5)
	map:addTile("tile-background-ice-07", 9, 6)
	map:addTile("tile-background-ice-window-02", 9, 7)
	map:addTile("tile-ground-ice-01", 9, 8)
	map:addTile("tile-rock-ice-02", 9, 9)
	map:addTile("tile-rock-ice-02", 9, 10)
	map:addTile("tile-rock-ice-01", 9, 11)
	map:addTile("tile-background-ice-cave-art-02", 10, 0)
	map:addTile("tile-background-ice-08", 10, 1)
	map:addTile("tile-ground-ice-01", 10, 2)
	map:addTile("tile-background-ice-05", 10, 5)
	map:addTile("tile-background-ice-07", 10, 6)
	map:addTile("tile-background-ice-08", 10, 7)
	map:addTile("tile-rock-slope-ice-right-01", 10, 8)
	map:addTile("tile-rock-ice-02", 10, 9)
	map:addTile("tile-rock-ice-big-01", 10, 10)
	map:addTile("tile-background-ice-03", 11, 0)
	map:addTile("tile-background-ice-02", 11, 1)
	map:addTile("tile-ground-ice-06", 11, 2)
	map:addTile("tile-rock-ice-big-01", 11, 3)
	map:addTile("tile-background-ice-08", 11, 5)
	map:addTile("tile-background-ice-04", 11, 6)
	map:addTile("tile-background-ice-02", 11, 7)
	map:addTile("tile-background-ice-08", 11, 8)
	map:addTile("tile-rock-slope-ice-right-01", 11, 9)
	map:addTile("tile-background-ice-07", 12, 0)
	map:addTile("tile-background-ice-02", 12, 1)
	map:addTile("tile-ground-ice-01", 12, 2)
	map:addTile("tile-rock-ice-02", 12, 5)
	map:addTile("tile-background-ice-07", 12, 6)
	map:addTile("tile-background-ice-05", 12, 7)
	map:addTile("tile-background-ice-04", 12, 8)
	map:addTile("tile-background-ice-02", 12, 9)
	map:addTile("tile-background-ice-05", 12, 10)
	map:addTile("tile-background-ice-08", 12, 11)
	map:addTile("tile-background-ice-03", 13, 0)
	map:addTile("tile-background-ice-08", 13, 1)
	map:addTile("tile-ground-ice-06", 13, 2)
	map:addTile("tile-rock-ice-02", 13, 3)
	map:addTile("tile-rock-ice-big-01", 13, 4)
	map:addTile("tile-rock-ice-02", 13, 6)
	map:addTile("tile-background-ice-03", 13, 7)
	map:addTile("tile-background-ice-cave-art-02", 13, 8)
	map:addTile("tile-background-ice-04", 13, 9)
	map:addTile("tile-background-ice-01", 13, 10)
	map:addTile("tile-background-ice-05", 13, 11)
	map:addTile("tile-background-ice-06", 14, 0)
	map:addTile("tile-background-ice-04", 14, 1)
	map:addTile("tile-ground-ice-01", 14, 2)
	map:addTile("tile-rock-ice-02", 14, 3)
	map:addTile("tile-rock-ice-03", 14, 6)
	map:addTile("tile-background-ice-03", 14, 7)
	map:addTile("tile-background-ice-03", 14, 8)
	map:addTile("tile-background-ice-07", 14, 9)
	map:addTile("tile-background-ice-cave-art-02", 14, 10)
	map:addTile("tile-background-ice-02", 14, 11)
	map:addTile("tile-background-ice-02", 15, 0)
	map:addTile("tile-background-ice-06", 15, 1)
	map:addTile("tile-rock-ice-03", 15, 2)
	map:addTile("tile-rock-ice-01", 15, 3)
	map:addTile("tile-rock-ice-03", 15, 4)
	map:addTile("tile-rock-ice-02", 15, 5)
	map:addTile("tile-rock-ice-03", 15, 6)
	map:addTile("tile-background-ice-03", 15, 7)
	map:addTile("tile-background-ice-07", 15, 8)
	map:addTile("tile-background-ice-04", 15, 9)
	map:addTile("tile-background-ice-08", 15, 10)
	map:addTile("tile-background-ice-04", 15, 11)

	map:addCave("tile-cave-ice-01", 8, 1, "npc-grandpa", 1000)
	map:addCave("tile-cave-ice-01", 8, 7, "none", 6000)

	map:addEmitter("tree", 0, 3, 1, 0, "")
	map:addEmitter("item-stone", 7, 4, 1, 0, "")
	map:addEmitter("npc-blowing", 13, 1, 1, 0, "right=false,size=5,strength=6")

	map:setSetting("width", "16")
	map:setSetting("height", "12")
	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "6")
	map:addStartPosition("4", "2")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "40")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "1")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
