function getName()
	return "Map 02"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-08", 0, 0)
	map:addTile("tile-background-ice-05", 0, 1)
	map:addTile("tile-background-ice-big-01", 0, 2)
	map:addTile("tile-background-ice-01", 0, 4)
	map:addTile("tile-ground-ice-03", 0, 5)
	map:addTile("tile-rock-slope-ice-right-02", 0, 6)
	map:addTile("tile-background-ice-05", 0, 7)
	map:addTile("tile-background-ice-06", 0, 8)
	map:addTile("tile-background-ice-05", 0, 9)
	map:addTile("tile-background-ice-cave-art-02", 0, 10)
	map:addTile("tile-background-ice-05", 0, 11)
	map:addTile("tile-background-ice-01", 1, 0)
	map:addTile("tile-background-ice-05", 1, 1)
	map:addTile("tile-background-ice-01", 1, 4)
	map:addTile("tile-ground-ice-03", 1, 5)
	map:addTile("tile-rock-slope-ice-left-02", 1, 6)
	map:addTile("tile-background-ice-08", 1, 7)
	map:addTile("tile-background-ice-05", 1, 8)
	map:addTile("tile-background-ice-07", 1, 9)
	map:addTile("tile-background-ice-07", 1, 10)
	map:addTile("tile-background-ice-04", 1, 11)
	map:addTile("tile-background-ice-02", 2, 0)
	map:addTile("tile-background-ice-01", 2, 1)
	map:addTile("tile-ground-ice-03", 2, 3)
	map:addTile("tile-rock-ice-big-01", 2, 4)
	map:addTile("tile-rock-ice-01", 2, 6)
	map:addTile("tile-rock-ice-01", 2, 7)
	map:addTile("tile-rock-ice-02", 2, 8)
	map:addTile("tile-rock-slope-ice-left-02", 2, 9)
	map:addTile("tile-background-ice-04", 2, 10)
	map:addTile("tile-background-ice-06", 2, 11)
	map:addTile("tile-background-ice-04", 3, 0)
	map:addTile("tile-background-ice-cave-art-02", 3, 1)
	map:addTile("tile-background-ice-window-01", 3, 2)
	map:addTile("tile-ground-ice-04", 3, 3)
	map:addTile("tile-rock-ice-01", 3, 6)
	map:addTile("tile-rock-ice-01", 3, 7)
	map:addTile("tile-rock-ice-big-01", 3, 8)
	map:addTile("tile-background-ice-cave-art-02", 3, 10)
	map:addTile("tile-background-ice-cave-art-02", 3, 11)
	map:addTile("tile-background-ice-03", 4, 0)
	map:addTile("tile-background-ice-07", 4, 1)
	map:addTile("tile-background-ice-07", 4, 2)
	map:addTile("tile-ground-ice-03", 4, 3)
	map:addTile("tile-rock-ice-01", 4, 4)
	map:addTile("tile-rock-ice-02", 4, 5)
	map:addTile("tile-rock-ice-01", 4, 6)
	map:addTile("tile-rock-ice-02", 4, 7)
	map:addTile("tile-rock-slope-ice-left-02", 4, 10)
	map:addTile("tile-background-ice-05", 4, 11)
	map:addTile("tile-background-ice-01", 5, 0)
	map:addTile("tile-background-ice-05", 5, 1)
	map:addTile("tile-background-ice-08", 5, 2)
	map:addTile("tile-background-ice-08", 5, 3)
	map:addTile("tile-background-ice-03", 5, 4)
	map:addTile("tile-background-ice-05", 5, 5)
	map:addTile("tile-background-ice-01", 5, 6)
	map:addTile("tile-ground-ice-02", 5, 8)
	map:addTile("tile-rock-ice-01", 5, 9)
	map:addTile("tile-rock-ice-01", 5, 10)
	map:addTile("tile-rock-ice-01", 5, 11)
	map:addTile("tile-background-ice-07", 6, 0)
	map:addTile("tile-background-ice-01", 6, 1)
	map:addTile("tile-background-ice-03", 6, 2)
	map:addTile("tile-background-ice-08", 6, 3)
	map:addTile("tile-background-ice-01", 6, 4)
	map:addTile("tile-background-ice-05", 6, 5)
	map:addTile("tile-background-ice-04", 6, 6)
	map:addTile("tile-background-ice-window-02", 6, 7)
	map:addTile("tile-ground-ice-01", 6, 8)
	map:addTile("tile-rock-ice-big-01", 6, 9)
	map:addTile("tile-rock-ice-02", 6, 11)
	map:addTile("tile-background-ice-06", 7, 0)
	map:addTile("tile-background-ice-04", 7, 1)
	map:addTile("tile-background-ice-window-01", 7, 2)
	map:addTile("tile-ground-ice-big-01", 7, 3)
	map:addTile("tile-rock-shim-ice-01", 7, 5)
	map:addTile("tile-background-ice-05", 7, 6)
	map:addTile("tile-background-ice-06", 7, 7)
	map:addTile("tile-ground-ice-01", 7, 8)
	map:addTile("tile-rock-ice-02", 7, 11)
	map:addTile("tile-background-ice-01", 8, 0)
	map:addTile("tile-background-ice-08", 8, 1)
	map:addTile("tile-background-ice-06", 8, 5)
	map:addTile("tile-background-ice-06", 8, 6)
	map:addTile("tile-background-ice-03", 8, 7)
	map:addTile("tile-ground-ice-02", 8, 8)
	map:addTile("tile-rock-ice-01", 8, 9)
	map:addTile("tile-rock-ice-big-01", 8, 10)
	map:addTile("tile-background-ice-06", 9, 0)
	map:addTile("tile-background-ice-05", 9, 1)
	map:addTile("tile-ground-ice-03", 9, 2)
	map:addTile("tile-rock-ice-01", 9, 3)
	map:addTile("tile-rock-slope-ice-right-02", 9, 4)
	map:addTile("tile-background-ice-02", 9, 5)
	map:addTile("tile-background-ice-03", 9, 6)
	map:addTile("tile-ground-ice-big-01", 9, 7)
	map:addTile("tile-rock-ice-01", 9, 9)
	map:addTile("tile-background-ice-04", 10, 0)
	map:addTile("tile-background-ice-02", 10, 1)
	map:addTile("tile-ground-ice-01", 10, 2)
	map:addTile("tile-rock-ice-03", 10, 3)
	map:addTile("tile-background-ice-01", 10, 4)
	map:addTile("tile-background-ice-cave-art-02", 10, 5)
	map:addTile("tile-background-ice-07", 10, 6)
	map:addTile("tile-rock-ice-01", 10, 9)
	map:addTile("tile-rock-ice-01", 10, 10)
	map:addTile("tile-rock-ice-02", 10, 11)
	map:addTile("tile-background-ice-05", 11, 0)
	map:addTile("tile-background-ice-08", 11, 1)
	map:addTile("tile-ground-ice-04", 11, 2)
	map:addTile("tile-rock-slope-ice-right-02", 11, 3)
	map:addTile("tile-background-ice-02", 11, 4)
	map:addTile("tile-background-ice-01", 11, 5)
	map:addTile("tile-rock-slope-ice-left-01", 11, 6)
	map:addTile("tile-rock-ice-02", 11, 7)
	map:addTile("tile-rock-ice-02", 11, 8)
	map:addTile("tile-rock-ice-02", 11, 9)
	map:addTile("tile-rock-ice-big-01", 11, 10)
	map:addTile("tile-background-ice-05", 12, 0)
	map:addTile("tile-background-ice-window-02", 12, 1)
	map:addTile("tile-ground-ice-01", 12, 2)
	map:addTile("tile-background-ice-02", 12, 3)
	map:addTile("tile-background-ice-08", 12, 4)
	map:addTile("tile-background-ice-06", 12, 5)
	map:addTile("tile-ground-ice-01", 12, 6)
	map:addTile("tile-rock-ice-03", 12, 7)
	map:addTile("tile-background-ice-02", 12, 8)
	map:addTile("tile-rock-slope-ice-right-01", 12, 9)
	map:addTile("tile-background-ice-05", 13, 0)
	map:addTile("tile-ground-ice-01", 13, 2)
	map:addTile("tile-background-ice-08", 13, 3)
	map:addTile("tile-background-ice-cave-art-02", 13, 4)
	map:addTile("tile-background-ice-01", 13, 5)
	map:addTile("tile-rock-slope-ice-right-01", 13, 6)
	map:addTile("tile-rock-slope-ice-right-02", 13, 7)
	map:addTile("tile-background-ice-02", 13, 8)
	map:addTile("tile-background-ice-07", 13, 9)
	map:addTile("tile-packagetarget-ice-01-idle", 13, 10)
	map:addTile("tile-rock-ice-02", 13, 11)
	map:addTile("tile-rock-ice-01", 14, 0)
	map:addTile("tile-rock-ice-big-01", 14, 1)
	map:addTile("tile-rock-slope-ice-left-02", 14, 3)
	map:addTile("tile-background-ice-08", 14, 4)
	map:addTile("tile-background-ice-02", 14, 5)
	map:addTile("tile-background-ice-08", 14, 6)
	map:addTile("tile-background-ice-big-01", 14, 7)
	map:addTile("tile-background-ice-08", 14, 9)
	map:addTile("tile-ground-ice-01", 14, 10)
	map:addTile("tile-rock-ice-01", 14, 11)
	map:addTile("tile-rock-ice-03", 15, 0)
	map:addTile("tile-rock-ice-01", 15, 3)
	map:addTile("tile-rock-ice-02", 15, 4)
	map:addTile("tile-rock-slope-ice-left-02", 15, 5)
	map:addTile("tile-background-ice-03", 15, 6)
	map:addTile("tile-waterfall-ice-01", 15, 9)
	map:addTile("tile-rock-ice-01", 15, 11)

	map:addCave("tile-cave-ice-01", 2, 2, "none", 4000)
	map:addCave("tile-cave-ice-02", 5, 7, "none", 4000)
	map:addCave("tile-cave-ice-01", 8, 2, "none", 5000)
	map:addCave("tile-cave-ice-02", 13, 1, "none", 7500)

	map:addEmitter("tree", 0, 3, 1, 0, "")
	map:addEmitter("tree", 9, 5, 1, 0, "")

	map:setSetting("width", "16")
	map:setSetting("height", "12")
	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "3")
	map:addStartPosition("14", "9")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "30")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "1")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
