function getName()
	return "Map 15"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-03", 0, 0)
	map:addTile("tile-background-ice-01", 0, 1)
	map:addTile("tile-background-ice-01", 0, 2)
	map:addTile("tile-ground-ice-01", 0, 3)
	map:addTile("tile-rock-ice-big-01", 0, 4)
	map:addTile("tile-rock-slope-ice-right-02", 0, 6)
	map:addTile("tile-background-ice-08", 0, 7)
	map:addTile("tile-background-ice-02", 0, 8)
	map:addTile("tile-ground-ice-06", 0, 9)
	map:addTile("tile-rock-ice-01", 0, 10)
	map:addTile("tile-rock-ice-01", 0, 11)
	map:addTile("tile-background-ice-07", 1, 0)
	map:addTile("tile-background-ice-04", 1, 1)
	map:addTile("tile-background-ice-05", 1, 2)
	map:addTile("tile-ground-ice-04", 1, 3)
	map:addTile("tile-background-ice-03", 1, 6)
	map:addTile("tile-background-ice-07", 1, 7)
	map:addTile("tile-background-ice-06", 1, 8)
	map:addTile("tile-rock-ice-03", 1, 9)
	map:addTile("tile-rock-ice-02", 1, 10)
	map:addTile("tile-rock-ice-02", 1, 11)
	map:addTile("tile-background-ice-04", 2, 0)
	map:addTile("tile-background-ice-big-01", 2, 1)
	map:addTile("tile-ground-ice-01", 2, 3)
	map:addTile("tile-rock-ice-01", 2, 4)
	map:addTile("tile-rock-slope-ice-right-02", 2, 5)
	map:addTile("tile-background-ice-08", 2, 6)
	map:addTile("tile-background-ice-08", 2, 7)
	map:addTile("tile-background-ice-01", 2, 8)
	map:addTile("tile-ground-ice-06", 2, 9)
	map:addTile("tile-ground-ice-02", 2, 10)
	map:addTile("tile-rock-ice-01", 2, 11)
	map:addTile("tile-background-ice-03", 3, 0)
	map:addTile("tile-ground-ice-02", 3, 3)
	map:addTile("tile-rock-ice-02", 3, 4)
	map:addTile("tile-background-ice-07", 3, 5)
	map:addTile("tile-background-ice-02", 3, 6)
	map:addTile("tile-background-ice-04", 3, 7)
	map:addTile("tile-background-ice-01", 3, 8)
	map:addTile("tile-rock-ice-03", 3, 9)
	map:addTile("tile-rock-ice-02", 3, 10)
	map:addTile("tile-rock-ice-02", 3, 11)
	map:addTile("tile-background-ice-05", 4, 0)
	map:addTile("tile-background-ice-08", 4, 1)
	map:addTile("tile-background-ice-08", 4, 2)
	map:addTile("tile-ground-ice-02", 4, 3)
	map:addTile("tile-rock-ice-02", 4, 4)
	map:addTile("tile-rock-slope-ice-left-02", 4, 5)
	map:addTile("tile-background-ice-08", 4, 6)
	map:addTile("tile-background-ice-04", 4, 7)
	map:addTile("tile-background-ice-06", 4, 8)
	map:addTile("tile-ground-ice-03", 4, 9)
	map:addTile("tile-rock-ice-03", 4, 10)
	map:addTile("tile-rock-ice-01", 4, 11)
	map:addTile("tile-background-ice-08", 5, 0)
	map:addTile("tile-background-ice-06", 5, 1)
	map:addTile("tile-background-ice-big-01", 5, 2)
	map:addTile("tile-background-ice-01", 5, 4)
	map:addTile("tile-ground-ice-06", 5, 5)
	map:addTile("tile-rock-slope-ice-left-02", 5, 6)
	map:addTile("tile-background-ice-01", 5, 7)
	map:addTile("tile-background-ice-cave-art-02", 5, 8)
	map:addTile("tile-ground-ice-06", 5, 9)
	map:addTile("tile-rock-ice-03", 5, 10)
	map:addTile("tile-rock-ice-02", 5, 11)
	map:addTile("tile-background-ice-08", 6, 0)
	map:addTile("tile-background-ice-cave-art-02", 6, 1)
	map:addTile("tile-background-ice-08", 6, 4)
	map:addTile("tile-ground-ice-02", 6, 5)
	map:addTile("tile-rock-ice-02", 6, 6)
	map:addTile("tile-rock-shim-ice-01", 6, 7)
	map:addTile("tile-background-ice-06", 6, 8)
	map:addTile("tile-ground-ice-04", 6, 9)
	map:addTile("tile-rock-ice-big-01", 6, 10)
	map:addTile("tile-background-ice-05", 7, 0)
	map:addTile("tile-background-ice-03", 7, 1)
	map:addTile("tile-background-ice-08", 7, 2)
	map:addTile("tile-background-ice-07", 7, 3)
	map:addTile("tile-background-ice-06", 7, 4)
	map:addTile("tile-rock-ice-left-05", 7, 5)
	map:addTile("tile-rock-ice-left-04", 7, 6)
	map:addTile("tile-background-ice-08", 7, 7)
	map:addTile("tile-background-ice-01", 7, 8)
	map:addTile("tile-rock-ice-03", 7, 9)
	map:addTile("tile-background-ice-07", 8, 0)
	map:addTile("tile-background-ice-08", 8, 1)
	map:addTile("tile-background-ice-08", 8, 2)
	map:addTile("tile-background-ice-03", 8, 3)
	map:addTile("tile-background-ice-04", 8, 4)
	map:addTile("tile-background-ice-cave-art-01", 8, 5)
	map:addTile("tile-background-ice-04", 8, 6)
	map:addTile("tile-ground-ice-05", 8, 7)
	map:addTile("tile-background-ice-07", 8, 8)
	map:addTile("tile-ground-ice-04", 8, 9)
	map:addTile("tile-rock-ice-02", 8, 10)
	map:addTile("tile-rock-ice-01", 8, 11)
	map:addTile("tile-background-ice-02", 9, 0)
	map:addTile("tile-background-ice-cave-art-02", 9, 1)
	map:addTile("tile-background-ice-04", 9, 2)
	map:addTile("tile-background-ice-07", 9, 3)
	map:addTile("tile-background-ice-07", 9, 4)
	map:addTile("tile-background-ice-04", 9, 5)
	map:addTile("tile-background-ice-04", 9, 6)
	map:addTile("tile-ground-ledge-ice-left-01", 9, 7)
	map:addTile("tile-background-ice-08", 9, 8)
	map:addTile("tile-ground-ice-04", 9, 9)
	map:addTile("tile-rock-ice-01", 9, 10)
	map:addTile("tile-rock-ice-02", 9, 11)
	map:addTile("tile-background-ice-05", 10, 0)
	map:addTile("tile-background-ice-07", 10, 1)
	map:addTile("tile-background-ice-06", 10, 2)
	map:addTile("tile-background-ice-01", 10, 3)
	map:addTile("tile-background-ice-08", 10, 4)
	map:addTile("tile-background-ice-07", 10, 5)
	map:addTile("tile-rock-slope-ice-left-01", 10, 6)
	map:addTile("tile-rock-slope-ice-right-02", 10, 7)
	map:addTile("tile-rock-slope-ice-left-01", 10, 8)
	map:addTile("tile-rock-ice-03", 10, 9)
	map:addTile("tile-rock-ice-02", 10, 10)
	map:addTile("tile-rock-ice-02", 10, 11)
	map:addTile("tile-background-ice-02", 11, 0)
	map:addTile("tile-background-ice-03", 11, 1)
	map:addTile("tile-background-ice-02", 11, 2)
	map:addTile("tile-background-ice-big-01", 11, 3)
	map:addTile("tile-background-ice-04", 11, 5)
	map:addTile("tile-ground-ice-02", 11, 6)
	map:addTile("tile-background-ice-07", 11, 7)
	map:addTile("tile-rock-slope-ice-right-01", 11, 8)
	map:addTile("tile-rock-ice-03", 11, 9)
	map:addTile("tile-rock-ice-big-01", 11, 10)
	map:addTile("tile-background-ice-01", 12, 0)
	map:addTile("tile-background-ice-08", 12, 1)
	map:addTile("tile-background-ice-01", 12, 2)
	map:addTile("tile-background-ice-06", 12, 5)
	map:addTile("tile-ground-ice-02", 12, 6)
	map:addTile("tile-rock-slope-ice-left-02", 12, 7)
	map:addTile("tile-background-ice-07", 12, 8)
	map:addTile("tile-rock-ice-03", 12, 9)
	map:addTile("tile-background-ice-08", 13, 0)
	map:addTile("tile-background-ice-03", 13, 1)
	map:addTile("tile-background-ice-08", 13, 2)
	map:addTile("tile-background-ice-08", 13, 3)
	map:addTile("tile-background-ice-08", 13, 4)
	map:addTile("tile-background-ice-cave-art-02", 13, 5)
	map:addTile("tile-ground-ice-02", 13, 6)
	map:addTile("tile-rock-ice-02", 13, 7)
	map:addTile("tile-background-ice-07", 13, 8)
	map:addTile("tile-rock-ice-03", 13, 9)
	map:addTile("tile-rock-ice-02", 13, 10)
	map:addTile("tile-rock-ice-01", 13, 11)
	map:addTile("tile-background-ice-big-01", 14, 0)
	map:addTile("tile-background-ice-01", 14, 2)
	map:addTile("tile-ground-ice-04", 14, 3)
	map:addTile("tile-rock-ice-02", 14, 4)
	map:addTile("tile-rock-ice-01", 14, 5)
	map:addTile("tile-rock-ice-01", 14, 6)
	map:addTile("tile-rock-ice-01", 14, 7)
	map:addTile("tile-background-ice-07", 14, 8)
	map:addTile("tile-background-ice-07", 14, 9)
	map:addTile("tile-rock-slope-ice-right-01", 14, 10)
	map:addTile("tile-rock-ice-02", 14, 11)
	map:addTile("tile-background-ice-cave-art-02", 15, 2)
	map:addTile("tile-ground-ice-02", 15, 3)
	map:addTile("tile-rock-ice-02", 15, 4)
	map:addTile("tile-rock-ice-02", 15, 5)
	map:addTile("tile-ground-ice-04", 15, 6)
	map:addTile("tile-rock-ice-03", 15, 7)
	map:addTile("tile-rock-ice-02", 15, 8)
	map:addTile("tile-rock-ice-02", 15, 9)
	map:addTile("tile-packagetarget-ice-01-idle", 15, 10, 270)
	map:addTile("tile-rock-ice-02", 15, 11)

	map:addEmitter("npc-walking", 3, 2, 1, 0, "")
	map:addEmitter("npc-blowing", 3, 8, 1, 0, "size=3")
	map:addEmitter("tree", 5.8, 3, 1, 0, "")
	map:addEmitter("tree", 8, 5, 1, 0, "")
	map:addEmitter("item-stone", 11, 5, 1, 0, "")
	map:addEmitter("item-package-ice", 13.6, 8, 1, 0, "")

	map:setSetting("width", "16")
	map:setSetting("height", "12")
	map:setSetting("fishnpc", "false")
	map:setSetting("flyingnpc", "false")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "1")
	map:setSetting("playerX", "13")
	map:setSetting("playerY", "5")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "30")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "1")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
