function getName()
	return "Map 12"
end

function onMapLoaded()
end

function initMap()
	-- get the current map context
	local map = Map.get()
	map:addTile("tile-background-ice-05", 0, 0)
	map:addTile("tile-background-ice-05", 0, 1)
	map:addTile("tile-background-ice-06", 0, 2)
	map:addTile("tile-background-ice-06", 0, 3)
	map:addTile("tile-background-ice-02", 0, 4)
	map:addTile("tile-background-ice-07", 0, 5)
	map:addTile("tile-background-ice-08", 0, 6)
	map:addTile("tile-background-ice-02", 0, 7)
	map:addTile("tile-background-ice-08", 0, 8)
	map:addTile("tile-ground-ice-01", 0, 9)
	map:addTile("tile-rock-ice-02", 0, 10)
	map:addTile("tile-rock-ice-02", 0, 11)
	map:addTile("tile-background-ice-07", 1, 0)
	map:addTile("tile-background-ice-03", 1, 1)
	map:addTile("tile-background-ice-cave-art-02", 1, 2)
	map:addTile("tile-background-ice-big-01", 1, 3)
	map:addTile("tile-background-ice-05", 1, 5)
	map:addTile("tile-background-ice-03", 1, 6)
	map:addTile("tile-background-ice-08", 1, 7)
	map:addTile("tile-background-ice-cave-art-02", 1, 8)
	map:addTile("tile-ground-ice-01", 1, 9)
	map:addTile("tile-rock-ice-big-01", 1, 10)
	map:addTile("tile-background-ice-02", 2, 0)
	map:addTile("tile-background-ice-06", 2, 1)
	map:addTile("tile-background-ice-04", 2, 2)
	map:addTile("tile-background-ice-cave-art-02", 2, 5)
	map:addTile("tile-background-ice-06", 2, 6)
	map:addTile("tile-background-ice-02", 2, 7)
	map:addTile("tile-ground-ice-02", 2, 8)
	map:addTile("tile-rock-ice-03", 2, 9)
	map:addTile("tile-background-ice-02", 3, 0)
	map:addTile("tile-ground-ledge-ice-left-02", 3, 2)
	map:addTile("tile-background-ice-cave-art-02", 3, 3)
	map:addTile("tile-background-ice-cave-art-02", 3, 4)
	map:addTile("tile-background-ice-07", 3, 5)
	map:addTile("tile-background-ice-01", 3, 6)
	map:addTile("tile-ground-ice-02", 3, 8)
	map:addTile("tile-rock-ice-01", 3, 9)
	map:addTile("tile-rock-ice-03", 3, 10)
	map:addTile("tile-rock-ice-02", 3, 11)
	map:addTile("tile-background-ice-06", 4, 0)
	map:addTile("tile-background-ice-window-01", 4, 1)
	map:addTile("tile-ground-ledge-ice-left-01", 4, 2)
	map:addTile("tile-background-ice-01", 4, 3)
	map:addTile("tile-background-ice-03", 4, 4)
	map:addTile("tile-background-ice-03", 4, 5)
	map:addTile("tile-background-ice-06", 4, 6)
	map:addTile("tile-background-ice-window-02", 4, 7)
	map:addTile("tile-ground-ice-big-01", 4, 8)
	map:addTile("tile-rock-ice-03", 4, 10)
	map:addTile("tile-rock-ice-02", 4, 11)
	map:addTile("tile-background-ice-01", 5, 0)
	map:addTile("tile-background-ice-02", 5, 1)
	map:addTile("tile-ground-ice-04", 5, 2)
	map:addTile("tile-rock-slope-ice-left-02", 5, 3)
	map:addTile("tile-background-ice-02", 5, 4)
	map:addTile("tile-background-ice-01", 5, 5)
	map:addTile("tile-background-ice-04", 5, 6)
	map:addTile("tile-background-ice-02", 5, 7)
	map:addTile("tile-rock-ice-03", 5, 10)
	map:addTile("tile-rock-ice-02", 5, 11)
	map:addTile("tile-background-ice-04", 6, 0)
	map:addTile("tile-background-ice-08", 6, 1)
	map:addTile("tile-ground-ice-big-01", 6, 2)
	map:addTile("tile-ground-ice-03", 6, 4)
	map:addTile("tile-rock-slope-ice-left-02", 6, 5)
	map:addTile("tile-background-ice-05", 6, 6)
	map:addTile("tile-background-ice-05", 6, 7)
	map:addTile("tile-rock-slope-ice-right-01", 6, 8)
	map:addTile("tile-rock-ice-03", 6, 9)
	map:addTile("tile-rock-slope-ice-right-02", 6, 10)
	map:addTile("tile-background-ice-02", 6, 11)
	map:addTile("tile-background-ice-06", 7, 0)
	map:addTile("tile-background-ice-08", 7, 1)
	map:addTile("tile-rock-ice-01", 7, 4)
	map:addTile("tile-rock-ice-03", 7, 5)
	map:addTile("tile-background-ice-01", 7, 6)
	map:addTile("tile-background-ice-05", 7, 7)
	map:addTile("tile-background-ice-03", 7, 8)
	map:addTile("tile-background-ice-05", 7, 9)
	map:addTile("tile-background-ice-01", 7, 10)
	map:addTile("tile-background-ice-03", 7, 11)
	map:addTile("tile-background-ice-08", 8, 0)
	map:addTile("tile-background-ice-cave-art-02", 8, 1)
	map:addTile("tile-ground-ice-06", 8, 2)
	map:addTile("tile-rock-ice-01", 8, 3)
	map:addTile("tile-rock-ice-03", 8, 4)
	map:addTile("tile-rock-ice-03", 8, 5)
	map:addTile("tile-background-ice-02", 8, 6)
	map:addTile("tile-background-ice-big-01", 8, 7)
	map:addTile("tile-background-ice-cave-art-02", 8, 9)
	map:addTile("tile-background-ice-02", 8, 10)
	map:addTile("tile-background-ice-03", 8, 11)
	map:addTile("tile-background-ice-cave-art-02", 9, 0)
	map:addTile("tile-ground-ice-04", 9, 2)
	map:addTile("tile-rock-ice-01", 9, 3)
	map:addTile("tile-rock-ice-03", 9, 4)
	map:addTile("tile-rock-ice-03", 9, 5)
	map:addTile("tile-background-ice-08", 9, 6)
	map:addTile("tile-background-ice-03", 9, 9)
	map:addTile("tile-background-ice-cave-art-02", 9, 10)
	map:addTile("tile-background-ice-01", 9, 11)
	map:addTile("tile-background-ice-04", 10, 0)
	map:addTile("tile-background-ice-window-01", 10, 1)
	map:addTile("tile-ground-ice-06", 10, 2)
	map:addTile("tile-rock-ice-03", 10, 3)
	map:addTile("tile-rock-ice-03", 10, 4)
	map:addTile("tile-rock-slope-ice-right-02", 10, 5)
	map:addTile("tile-background-ice-03", 10, 6)
	map:addTile("tile-background-ice-big-01", 10, 7)
	map:addTile("tile-rock-slope-ice-left-01", 10, 9)
	map:addTile("tile-rock-ice-big-01", 10, 10)
	map:addTile("tile-background-ice-03", 11, 0)
	map:addTile("tile-background-ice-01", 11, 1)
	map:addTile("tile-ground-ice-06", 11, 2)
	map:addTile("tile-rock-ice-left-04", 11, 3)
	map:addTile("tile-ground-ledge-ice-right-02", 11, 4)
	map:addTile("tile-background-ice-big-01", 11, 5)
	map:addTile("tile-packagetarget-ice-01-idle", 11, 9)
	map:addTile("tile-background-ice-08", 12, 0)
	map:addTile("tile-background-ice-08", 12, 1)
	map:addTile("tile-ground-ledge-ice-right-01", 12, 2)
	map:addTile("tile-background-ice-big-01", 12, 3)
	map:addTile("tile-background-ice-cave-art-02", 12, 7)
	map:addTile("tile-background-ice-04", 12, 8)
	map:addTile("tile-rock-slope-ice-right-01", 12, 9)
	map:addTile("tile-rock-ice-03", 12, 10)
	map:addTile("tile-rock-ice-02", 12, 11)
	map:addTile("tile-background-ice-04", 13, 0)
	map:addTile("tile-background-ice-05", 13, 1)
	map:addTile("tile-background-ice-02", 13, 2)
	map:addTile("tile-background-ice-02", 13, 5)
	map:addTile("tile-background-ice-cave-art-02", 13, 6)
	map:addTile("tile-background-ice-03", 13, 7)
	map:addTile("tile-background-ice-big-01", 13, 8)
	map:addTile("tile-rock-slope-ice-right-01", 13, 10)
	map:addTile("tile-rock-ice-03", 13, 11)
	map:addTile("tile-background-ice-cave-art-02", 14, 0)
	map:addTile("tile-background-ice-02", 14, 1)
	map:addTile("tile-background-ice-05", 14, 2)
	map:addTile("tile-background-ice-07", 14, 3)
	map:addTile("tile-background-ice-02", 14, 4)
	map:addTile("tile-background-ice-08", 14, 5)
	map:addTile("tile-background-ice-05", 14, 6)
	map:addTile("tile-background-ice-02", 14, 7)
	map:addTile("tile-rock-slope-ice-left-01", 14, 10)
	map:addTile("tile-rock-ice-02", 14, 11)
	map:addTile("tile-rock-ice-right-04", 15, 0)
	map:addTile("tile-rock-ice-right-05", 15, 1)
	map:addTile("tile-rock-ice-right-04", 15, 2)
	map:addTile("tile-ground-ledge-ice-left-02", 15, 3)
	map:addTile("tile-background-ice-cave-art-02", 15, 4)
	map:addTile("tile-background-ice-05", 15, 5)
	map:addTile("tile-background-ice-cave-art-02", 15, 6)
	map:addTile("tile-ground-ice-05", 15, 7)
	map:addTile("tile-background-ice-03", 15, 8)
	map:addTile("tile-rock-slope-ice-left-01", 15, 9)
	map:addTile("tile-rock-ice-03", 15, 10)
	map:addTile("tile-rock-ice-03", 15, 11)

	map:addCave("tile-cave-ice-01", 3, 1)
	map:addCave("tile-cave-ice-01", 3, 7)
	map:addCave("tile-cave-ice-01", 9, 1, "none", 1000)

	map:addEmitter("tree", 0, 7, 1, 0, "")
	map:addEmitter("tree", 0, 7, 1, 0, "")
	map:addEmitter("npc-blowing", 14, 6, 1, 0, "right=false")

	map:setSetting("width", "16")
	map:setSetting("height", "12")
	map:setSetting("fishnpc", "true")
	map:setSetting("flyingnpc", "true")
	map:setSetting("gravity", "9.81")
	map:setSetting("packagetransfercount", "3")
	map:addStartPosition("5", "1")
	map:setSetting("points", "100")
	map:setSetting("referencetime", "30")
	map:setSetting("theme", "ice")
	map:setSetting("waterchangespeed", "0")
	map:setSetting("waterfallingdelay", "0")
	map:setSetting("waterheight", "1.6")
	map:setSetting("waterrisingdelay", "0")
	map:setSetting("wind", "0.0")
end
