set(FRAMEWORKS Foundation IOKit OpenGL Cocoa CoreVideo OpenAL)
foreach(FW ${FRAMEWORKS})
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -framework ${FW}")
endforeach()
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++11")
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")

macro(set_xcode_properties PROJECTNAME)
	set_target_properties(${PROJECTNAME} PROPERTIES
		XCODE_ATTRIBUTE_INFOPLIST_PREPROCESS YES
		XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "iPhone Developer"
		XCODE_ATTRIBUTE_DEBUG_INFORMATION_FORMAT "dwarf-with-dsym"
		XCODE_ATTRIBUTE_COMBINE_HIDPI_IMAGES NO
		XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET 7.1
		XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2" # iPhone/iPad
		MACOSX_BUNDLE_GUI_IDENTIFIER "org.caveproductions.${PROJECTNAME}"
		MACOSX_BUNDLE_INFO_PLIST ${CMAKE_SOURCE_DIR}/cmake/iOSBundleInfo.plist.template
	)
endmacro()
