# Detect Box2D major.minor.micro for cp-config.h (SDL-style CP_BOX2D_VERSION_*).
#
# Priority:
#  1. source CMakeLists.txt `project(box2d VERSION x.y.z)` (FetchContent / git tree)
#  2. HINT from CMake package or pkg-config
#  3. B2_VERSION_* in installed headers (3.2+)
#  4. FetchContent GIT_TAG (v3.1.1)
#  5. header fingerprint (3.1 vs 3.0 vs 2.4)
#  6. default 2.4.2

function(cp_box2d_set_version major minor micro)
	if (minor STREQUAL "")
		set(minor 0)
	endif()
	if (micro STREQUAL "")
		set(micro 0)
	endif()
	set(CP_BOX2D_MAJOR "${major}" CACHE INTERNAL "Box2D major version")
	set(CP_BOX2D_MINOR "${minor}" CACHE INTERNAL "Box2D minor version")
	set(CP_BOX2D_MICRO "${micro}" CACHE INTERNAL "Box2D micro/patch version")
	set(box2d_VERSION "${major}.${minor}.${micro}" CACHE STRING "Detected Box2D version" FORCE)
	message(STATUS "Box2D ${box2d_VERSION}")
endfunction()

function(cp_box2d_parse_semver version_string out_major out_minor out_micro out_ok)
	set(${out_ok} FALSE PARENT_SCOPE)
	if (NOT version_string)
		return()
	endif()
	string(REGEX REPLACE "^[vV]" "" version_string "${version_string}")
	if (version_string MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)")
		set(${out_major} "${CMAKE_MATCH_1}" PARENT_SCOPE)
		set(${out_minor} "${CMAKE_MATCH_2}" PARENT_SCOPE)
		set(${out_micro} "${CMAKE_MATCH_3}" PARENT_SCOPE)
		set(${out_ok} TRUE PARENT_SCOPE)
	elseif (version_string MATCHES "^([0-9]+)\\.([0-9]+)")
		set(${out_major} "${CMAKE_MATCH_1}" PARENT_SCOPE)
		set(${out_minor} "${CMAKE_MATCH_2}" PARENT_SCOPE)
		set(${out_micro} "0" PARENT_SCOPE)
		set(${out_ok} TRUE PARENT_SCOPE)
	endif()
endfunction()

function(cp_box2d_detect_from_cmakelists source_dir out_major out_minor out_micro out_ok)
	set(${out_ok} FALSE PARENT_SCOPE)
	if (NOT source_dir OR NOT EXISTS "${source_dir}/CMakeLists.txt")
		return()
	endif()
	file(READ "${source_dir}/CMakeLists.txt" _txt)
	if (_txt MATCHES "project\\([ \t\r\n]*box2d[ \t\r\n]+VERSION[ \t\r\n]+([0-9]+)\\.([0-9]+)\\.([0-9]+)")
		set(${out_major} "${CMAKE_MATCH_1}" PARENT_SCOPE)
		set(${out_minor} "${CMAKE_MATCH_2}" PARENT_SCOPE)
		set(${out_micro} "${CMAKE_MATCH_3}" PARENT_SCOPE)
		set(${out_ok} TRUE PARENT_SCOPE)
	endif()
endfunction()

function(cp_box2d_detect_from_headers include_dirs out_major out_minor out_micro out_ok)
	set(${out_ok} FALSE PARENT_SCOPE)
	find_file(_cp_b2_base NAMES box2d/base.h PATHS ${include_dirs} NO_DEFAULT_PATH)
	if (_cp_b2_base)
		file(READ "${_cp_b2_base}" _cp_b2_base_txt)
		if (_cp_b2_base_txt MATCHES "#define[ \t]+B2_VERSION_MAJOR[ \t]+([0-9]+)")
			set(_maj "${CMAKE_MATCH_1}")
			set(_min 0)
			set(_mic 0)
			if (_cp_b2_base_txt MATCHES "#define[ \t]+B2_VERSION_MINOR[ \t]+([0-9]+)")
				set(_min "${CMAKE_MATCH_1}")
			endif()
			if (_cp_b2_base_txt MATCHES "#define[ \t]+B2_VERSION_REVISION[ \t]+([0-9]+)")
				set(_mic "${CMAKE_MATCH_1}")
			endif()
			set(${out_major} "${_maj}" PARENT_SCOPE)
			set(${out_minor} "${_min}" PARENT_SCOPE)
			set(${out_micro} "${_mic}" PARENT_SCOPE)
			set(${out_ok} TRUE PARENT_SCOPE)
			unset(_cp_b2_base CACHE)
			return()
		endif()
	endif()
	unset(_cp_b2_base CACHE)

	find_file(_cp_b2_id NAMES box2d/id.h PATHS ${include_dirs} NO_DEFAULT_PATH)
	if (NOT _cp_b2_id)
		set(${out_major} "2" PARENT_SCOPE)
		set(${out_minor} "4" PARENT_SCOPE)
		set(${out_micro} "0" PARENT_SCOPE)
		set(${out_ok} TRUE PARENT_SCOPE)
		return()
	endif()
	unset(_cp_b2_id CACHE)

	# 3.0 vs 3.1: 3.1 renamed b2_maxPolygonVertices to B2_MAX_POLYGON_VERTICES.
	find_file(_cp_b2_col NAMES box2d/collision.h PATHS ${include_dirs} NO_DEFAULT_PATH)
	set(_is_31 FALSE)
	if (_cp_b2_col)
		file(READ "${_cp_b2_col}" _cp_b2_col_txt)
		if (_cp_b2_col_txt MATCHES "B2_MAX_POLYGON_VERTICES")
			set(_is_31 TRUE)
		endif()
	endif()
	unset(_cp_b2_col CACHE)

	if (_is_31)
		set(${out_major} "3" PARENT_SCOPE)
		set(${out_minor} "1" PARENT_SCOPE)
		set(${out_micro} "0" PARENT_SCOPE)
	else()
		set(${out_major} "3" PARENT_SCOPE)
		set(${out_minor} "0" PARENT_SCOPE)
		set(${out_micro} "0" PARENT_SCOPE)
	endif()
	set(${out_ok} TRUE PARENT_SCOPE)
endfunction()

function(cp_box2d_collect_include_dirs out_var)
	set(_inc "")
	foreach (_tgt box2d::box2d box2d)
		if (TARGET ${_tgt})
			get_target_property(_tgt_inc ${_tgt} INTERFACE_INCLUDE_DIRECTORIES)
			if (_tgt_inc)
				list(APPEND _inc ${_tgt_inc})
			endif()
		endif()
	endforeach()
	if (BOX2D_INCLUDE_DIRS)
		list(APPEND _inc ${BOX2D_INCLUDE_DIRS})
	endif()
	set(${out_var} "${_inc}" PARENT_SCOPE)
endfunction()

function(cp_box2d_detect_version)
	cmake_parse_arguments(B2 "" "SOURCE_DIR;HINT;TAG" "INCLUDE_DIRS" ${ARGN})

	set(_maj "")
	set(_min "")
	set(_mic "")
	set(_ok FALSE)

	if (B2_SOURCE_DIR)
		cp_box2d_detect_from_cmakelists("${B2_SOURCE_DIR}" _maj _min _mic _ok)
	endif()

	if (NOT _ok AND B2_HINT)
		cp_box2d_parse_semver("${B2_HINT}" _maj _min _mic _ok)
	endif()

	if (NOT _ok AND B2_INCLUDE_DIRS)
		cp_box2d_detect_from_headers("${B2_INCLUDE_DIRS}" _maj _min _mic _ok)
	endif()

	if (NOT _ok AND B2_SOURCE_DIR)
		cp_box2d_detect_from_headers("${B2_SOURCE_DIR}/include" _maj _min _mic _ok)
	endif()

	if (NOT _ok AND B2_TAG)
		cp_box2d_parse_semver("${B2_TAG}" _maj _min _mic _ok)
	endif()

	if (NOT _ok)
		set(_maj 2)
		set(_min 4)
		set(_mic 2)
	endif()

	cp_box2d_set_version("${_maj}" "${_min}" "${_mic}")
endfunction()
