option(HD_VERSION "Build the HD versions of the games" OFF)
set(UNITTESTS OFF)
set(TOOLS OFF)
set(USE_BUILTIN ON)
set(IOS_PROVISIONG_PROFILES_DIR "$ENV{HOME}/Library/MobileDevice/Provisioning\ Profiles/")

macro(cp_ios_get_provisioning_profiles PROFILE_NAME PROVISIONG_PROFILES_DIR RESULT)
	get_subdirs(AVAILABLE_PROFILES ${PROVISIONG_PROFILES_DIR})
	foreach(PROFILE ${AVAILABLE_PROFILES})
		file(GLOB FILES ${PROVISIONG_PROFILES_DIR}/${PROFILE})
		set(LIST "")
		foreach(FILE ${FILES})
			file(STRINGS "${FILE}" NAME REGEX "${PROFILE_NAME}")
			if (NAME)
				list(APPEND LIST ${FILE})
			endif()
		endforeach()
		if (DIRLIST)
			set(${RESULT} ${DIRLIST})
		endif()
	endforeach()
endmacro()
